'use strict';
// HUD_POLISH_CORRECTION_v0.2 — runtime acceptance (headless Chrome, mobile emulation): first-layer height unchanged, 30/20/50
// columns, resource icons ×1.20 / time icon ×1.15 (one icon, 4 px before the block, centred on it), three-row time module (年份 regular
// / 月日 · 时辰 with the 时辰 bold / 商期 label regular with bold numbers at +1 px), rows stacked and left-aligned with ≥1.5 px clearance
// to the first-layer edges, no bar / chip / third layer, nav icons ×1.45 (0.406H) with label size / weight / gap unchanged, stacks
// re-laid downward (icons start 2 px below the first layer; the HUD box grows only by the second layer), 20 % slots centred, hit area
// not smaller, states 未启程 / N日 / 22日, across phone widths. Writes measure-<viewport>.json for the patch-notes parameter table.
// Usage: node tests/browser/hud-run.js [label] [--root <dir>] [--port <http>] [--cdp <chrome port>]
const fs = require('fs'), path = require('path');
const { launch, startServer, sleep } = require('../tools/cdp');
const root = path.join(__dirname, '..', '..');
const argv = process.argv.slice(2), flag = n => { const i = argv.indexOf(n); return i >= 0 ? argv[i + 1] : null; };
const label = argv.find((a, i) => !a.startsWith('--') && (i === 0 || !argv[i - 1].startsWith('--'))) || 'hud';
const serveRoot = flag('--root') ? path.resolve(flag('--root')) : root;
const outDir = path.join(root, 'tests', 'results', 'evidence', 'hud-' + label); fs.rmSync(outDir, { recursive: true, force: true }); fs.mkdirSync(outDir, { recursive: true });
const checks = [];
const check = (name, ok, detail) => { checks.push({ name, ok: Boolean(ok), detail: detail === undefined ? '' : String(detail).slice(0, 300) }); console.log((ok ? 'PASS ' : 'FAIL ') + name + (detail !== undefined ? '  ' + String(detail).slice(0, 200) : '')); };
const VIEWPORTS = [[390, 844, 'iphone13'], [375, 667, 'iphone8'], [360, 640, 'android-small'], [430, 932, 'iphone15promax'], [320, 568, 'iphone-se1']];
const MEASURE = `(()=>{const r=e=>{const b=e.getBoundingClientRect();return {x:+b.x.toFixed(1),y:+b.y.toFixed(1),w:+b.width.toFixed(1),h:+b.height.toFixed(1),right:+b.right.toFixed(1),bottom:+b.bottom.toFixed(1)}};const cs=e=>getComputedStyle(e);const px=v=>+parseFloat(v).toFixed(2);
  const hud=document.querySelector('.global-hud'),top=hud.querySelector('.hud-top'),nav=hud.querySelector('.hud-nav');const money=hud.querySelector('.money-status'),rep=hud.querySelector('.reputation-status'),time=hud.querySelector('.time-status');
  const H=+(px(cs(top).height)/.53).toFixed(2);const mi=money.querySelector('.ui-icon'),mv=money.querySelector('.status-value'),ri=rep.querySelector('.ui-icon'),rv=rep.querySelector('.status-value'),ti=time.querySelector('.ui-icon'),block=time.querySelector('.time-block');
  const row=(sel,inner)=>{const e=time.querySelector(sel);if(!e)return null;const strong=inner?e.querySelector(inner):null;return {...r(e),font:px(cs(e).fontSize),lineHeight:px(cs(e).lineHeight),weight:cs(e).fontWeight,text:e.innerText.replace(/\s+/g,' ').trim(),overflow:e.scrollWidth-e.clientWidth,strong:strong?{font:px(cs(strong).fontSize),weight:cs(strong).fontWeight,text:strong.textContent,lineHeight:px(cs(strong).lineHeight)}:null}};
  const grp=e=>{const items=[...e.children];const a=items[0].getBoundingClientRect(),b=items[items.length-1].getBoundingClientRect();const slot=e.getBoundingClientRect();return {leftPad:+(Math.min(a.x,b.x)-slot.x).toFixed(1),rightPad:+(slot.right-Math.max(a.right,b.right)).toFixed(1)}};
  const cols=cs(top).gridTemplateColumns.split(' ').map(px);const tools=[...nav.querySelectorAll('.hud-tool')];let tokEl=hud;while(tokEl&&!tokEl.style.getPropertyValue('--hud-row-lh'))tokEl=tokEl.parentElement;const rl=tokEl?tokEl.style:{getPropertyValue:()=>''};
  return {vw:innerWidth,vh:innerHeight,H,hud:r(hud),top:r(top),nav:r(nav),navPadTop:px(cs(nav).paddingTop),cols,colRatio:cols.map(c=>+(c/r(top).w).toFixed(3)),tokens:{year:rl.getPropertyValue('--hud-year').trim(),date:rl.getPropertyValue('--hud-date').trim(),num:rl.getPropertyValue('--hud-trip-num').trim(),lh:rl.getPropertyValue('--hud-row-lh').trim()},
    money:{icon:r(mi),gap:+(r(mv).x-r(mi).right).toFixed(1),font:px(cs(mv).fontSize),center:grp(money)},rep:{icon:r(ri),gap:+(r(rv).x-r(ri).right).toFixed(1),font:px(cs(rv).fontSize),center:grp(rep)},
    time:{slot:r(time),icon:r(ti),iconCount:time.querySelectorAll('.ui-icon').length,block:r(block),rows:block.children.length,year:row('.year-line'),date:row('.date-line','.phase-strong'),trip:row('.trip-row','.trip-num'),iconGap:+(r(block).x-r(ti).right).toFixed(1),iconCenterDelta:+((r(ti).y+r(ti).h/2)-(r(block).y+r(block).h/2)).toFixed(1)},
    tools:tools.map(t=>{const i=t.querySelector('.ui-icon'),l=t.querySelector('.hud-label');return {label:l.textContent,slot:r(t).w,icon:r(i).w,iconY:r(i).y,labelFont:px(cs(l).fontSize),labelWeight:cs(l).fontWeight,labelLh:px(cs(l).lineHeight),gap:+(r(l).y-r(i).bottom).toFixed(1),stackCenter:+((r(i).x+r(i).w/2)-(r(t).x+r(t).w/2)).toFixed(1),labelCenter:+((r(l).x+r(l).w/2)-(r(i).x+r(i).w/2)).toFixed(1),hitH:r(t).h,hitW:r(t).w,bottom:r(l).bottom}}),
    hitBefore:px(cs(tools[0],'::before').height),labels:[...nav.querySelectorAll('.hud-label')].map(l=>l.textContent).join('/'),dividers:hud.querySelectorAll('hr, .hud-divider, .hud-chip, .journey-progress, progress').length}})()`;
(async () => {
  const port = Number(flag('--port')) || 8195, srv = startServer(port, serveRoot); await sleep(500);
  const shots = [];
  for (const [w, h, name] of VIEWPORTS) {
    const c = await launch({ port: (Number(flag('--cdp')) || 9415) + VIEWPORTS.findIndex(v => v[2] === name), width: w, height: h, mobile: true });
    const ev = js => c.eval(js);
    const clickText = text => ev(`(()=>{const b=[...document.querySelectorAll('button')].find(b=>!b.disabled&&b.offsetParent!==null&&b.textContent.trim()===${JSON.stringify(text)});if(!b)return false;b.click();return true})()`);
    try {
      await c.navigate('http://127.0.0.1:' + port + '/'); await sleep(900); await ev('new Promise(r=>{const t=setInterval(()=>{if(window.Silk&&Silk.app&&Silk.app.state){clearInterval(t);r()}},100)})');
      if (await ev('Boolean(Silk.app.state.progress)')) { await ev("Silk.ui.dispatch('game.reset')"); await sleep(600); }
      await clickText('启程'); await ev('new Promise(r=>{const t=setInterval(()=>{const p=Silk.app.state.progress;if(p&&p.world){clearInterval(t);r()}},100)})'); await sleep(400); await clickText('自行探索'); await sleep(500);
      // realistic labels: day 26 at dusk (display only), then a trip in progress
      await ev("(()=>{Silk.app.state.progress.world.tick=77;Silk.ui.render(Silk.app.state);})()"); await sleep(300);
      const m = await ev(MEASURE); const H = m.H; const f = (k, base) => +(H * base).toFixed(1);
      const tag = name + ' ' + w + '×' + h;
      const yearExp = Math.max(8, Math.min(12, Math.round(H * .139))), dateExp = Math.max(8, Math.min(13, Math.round(H * .139 + 1))), numExp = dateExp + 1, lhExp = +Math.max(1, Math.min(1.1, (H * .53 - 4) / (yearExp + dateExp + dateExp))).toFixed(3);
      const rowsOk = (t) => t.time.rows === 3 && t.time.year && t.time.date && t.time.trip && [t.time.year, t.time.date, t.time.trip].every(x => x.overflow <= 0) && t.time.year.bottom <= t.time.date.y + .6 && t.time.date.bottom <= t.time.trip.y + .6 && Math.abs(t.time.year.x - t.time.date.x) < .6 && Math.abs(t.time.year.x - t.time.trip.x) < .6;
      const edgeOk = (t) => t.time.block.y >= t.top.y + 1.2 && t.time.block.bottom <= t.top.bottom - 1.2 && t.time.block.right <= t.time.slot.right - 3 && t.time.icon.y >= t.top.y && t.time.icon.bottom <= t.top.bottom;
      check(tag + ' A first-layer height unchanged = 53% of --hud-height (' + m.top.h + ' px, H = ' + H + ')', Math.abs(m.top.h - h * .089 * .53) < 1 && Math.abs(H - h * .089) < 1.5, JSON.stringify({ top: m.top.h, expect: +(h * .089 * .53).toFixed(1), hudBox: m.hud.h }));
      check(tag + ' A columns 30 / 20 / 50 (of the content box)', Math.abs(m.colRatio[0] - .3) < .006 && Math.abs(m.colRatio[1] - .2) < .006 && Math.abs(m.colRatio[2] - .5) < .006, m.colRatio.join('/'));
      check(tag + ' A 铜钱 / 鼎 icons ×1.20 (' + m.money.icon.w + ' px = 0.336H), 数字 font unchanged, gap 0', Math.abs(m.money.icon.w - f(0, .336)) < .6 && Math.abs(m.rep.icon.w - f(0, .336)) < .6 && m.money.gap <= .5 && m.rep.gap <= .5 && Math.abs(m.money.font - Math.min(18, Math.max(11, H * .235))) < .3, JSON.stringify({ icon: m.money.icon.w, expect: f(0, .336), gap: m.money.gap, font: m.money.font }));
      check(tag + ' A groups centred in their slots (symmetric padding)', Math.abs(m.money.center.leftPad - m.money.center.rightPad) < 1.5 && Math.abs(m.rep.center.leftPad - m.rep.center.rightPad) < 1.5, JSON.stringify({ money: m.money.center, rep: m.rep.center }));
      check(tag + ' B one time icon ×1.15 (' + m.time.icon.w + ' px = 0.322H), 4 px before the block, centred on the three rows', m.time.iconCount === 1 && Math.abs(m.time.icon.w - f(0, .322)) < .6 && Math.abs(m.time.icon.h - f(0, .322)) < .6 && Math.abs(m.time.iconGap - 4) < .6 && Math.abs(m.time.iconCenterDelta) <= 1, JSON.stringify({ icon: [m.time.icon.w, m.time.icon.h], expect: f(0, .322), gap: m.time.iconGap, delta: m.time.iconCenterDelta }));
      check(tag + ' B row 1 年份 regular ' + (m.time.year && m.time.year.font) + ' px: ' + (m.time.year && m.time.year.text), m.time.year && m.time.year.text === '贞元十六年' && m.time.year.font === yearExp && m.time.year.weight === '400', JSON.stringify({ font: m.time.year && m.time.year.font, expect: yearExp, weight: m.time.year && m.time.year.weight }));
      check(tag + ' B row 2 日期 · 时辰 at ' + (m.time.date && m.time.date.font) + ' px, date regular / 时辰 bold: ' + (m.time.date && m.time.date.text), m.time.date && /^[一二三四五六七八九十正]+月[一二三四五六七八九十]+日 · (晨|午|暮)$/.test(m.time.date.text) && m.time.date.font === dateExp && m.time.date.weight === '400' && m.time.date.strong && m.time.date.strong.weight === '700' && /^(晨|午|暮)$/.test(m.time.date.strong.text) && m.time.date.strong.font === dateExp, JSON.stringify({ font: m.time.date && m.time.date.font, expect: dateExp, strong: m.time.date && m.time.date.strong }));
      check(tag + ' B row 3 商期　未启程 at ' + (m.time.trip && m.time.trip.font) + ' px, label + idle text regular', m.time.trip && /^商期\s*未启程$/.test(m.time.trip.text) && m.time.trip.font === dateExp && m.time.trip.weight === '400' && !m.time.trip.strong, JSON.stringify({ font: m.time.trip && m.time.trip.font, expect: dateExp, text: m.time.trip && m.time.trip.text }));
      check(tag + ' B three rows stacked, left-aligned, line-height ' + (m.time.year && m.time.year.lineHeight) + '/' + (m.time.date && m.time.date.lineHeight) + '/' + (m.time.trip && m.time.trip.lineHeight) + ' px (token ' + m.tokens.lh + ')', rowsOk(m) && Math.abs(m.time.year.lineHeight - yearExp * lhExp) < .6 && Math.abs(m.time.date.lineHeight - dateExp * lhExp) < .6 && Math.abs(m.time.trip.lineHeight - dateExp * lhExp) < .6 && Math.abs(parseFloat(m.tokens.lh) - lhExp) <= .002, JSON.stringify({ rows: m.time.rows, lh: [m.time.year && m.time.year.lineHeight, m.time.date && m.time.date.lineHeight, m.time.trip && m.time.trip.lineHeight], expect: lhExp, y: [m.time.year && m.time.year.y, m.time.date && m.time.date.y, m.time.trip && m.time.trip.y] }));
      check(tag + ' B block inside the first layer with ≥1.2 px top/bottom clearance and ≥3 px right margin (block ' + m.time.block.w + '×' + m.time.block.h + ' in slot ' + m.time.slot.w + '×' + m.time.slot.h + ')', edgeOk(m), JSON.stringify({ top: [m.top.y, m.top.bottom], block: [m.time.block.y, m.time.block.bottom, m.time.block.right], slot: m.time.slot.right }));
      check(tag + ' B no bar / chip / divider / third layer, no font shrink (date ≥ v0.1 row-1 size)', m.dividers === 0 && m.nav.y >= m.top.bottom - .5 && m.time.date.font >= Math.max(8, Math.min(13, Math.round(H * .139 + 1))), JSON.stringify({ dividers: m.dividers }));
      check(tag + ' C order 行囊/委托/消息/商号/更多, icons ×1.45 (' + m.tools[0].icon + ' px = 0.406H), label font unchanged (' + m.tools[0].labelFont + ' px, weight ' + m.tools[0].labelWeight + '), gap −3 px, 20% slots, centred on one axis', m.labels === '行囊/委托/消息/商号/更多' && m.tools.every(t => Math.abs(t.icon - f(0, .406)) < .6 && Math.abs(t.labelFont - Math.min(11, Math.max(8, H * .145))) < .3 && t.labelWeight === '600' && Math.abs(t.gap + 3) <= .6 && Math.abs(t.slot - m.nav.w / 5) < .6 && Math.abs(t.stackCenter) <= 1 && Math.abs(t.labelCenter) <= 1), JSON.stringify(m.tools.map(t => ({ icon: t.icon, gap: t.gap, slot: t.slot, c: t.stackCenter, lc: t.labelCenter }))));
      check(tag + ' C stacks grow downward: icons start 2 px below the first layer (v0.1: −0.5 px), HUD box grows only by the second layer (' + m.hud.h + ' vs ' + H + ')', m.tools.every(t => t.iconY >= m.top.bottom + 1.5 && t.iconY <= m.top.bottom + 2.6) && m.navPadTop === 2 && m.hud.h >= H - .5 && m.hud.h - H <= 9 && m.top.h < m.nav.h + 1e9, JSON.stringify({ iconY: m.tools[0].iconY, topBottom: m.top.bottom, nav: m.nav.h, hud: m.hud.h, H }));
      check(tag + ' C hit area not smaller than the v0.1 second layer (button ' + m.tools[0].hitW + '×' + m.tools[0].hitH + ' vs ' + (h * .089 * .47).toFixed(1) + ' px) and stacks inside the HUD box', m.tools.every(t => t.hitH >= m.nav.h - 3.5 && t.hitH >= h * .089 * .47 && t.hitW >= m.nav.w / 5 - .6 && t.bottom <= m.hud.bottom + .6), JSON.stringify({ hit: [m.tools[0].hitW, m.tools[0].hitH], bottom: m.tools[0].bottom, hud: m.hud.bottom }));
      if (w === 390) { const shot = path.join(outDir, '01-' + name + '-unstarted.png'); await c.screenshot(shot); shots.push(shot); }
      // trip state (display only): 商期　15日 / 22日 with bold, +1 px numbers
      await ev("(()=>{const p=Silk.app.state.progress;p.trip={id:'probe',startedAt:33,deadlineTick:99,arrivedChanganTick:null,returnStatus:null,phase:'in_city',routeIndex:1,routeHistory:['changan','dunhuang']};p.world.city='dunhuang';Silk.ui.render(Silk.app.state);})()"); await sleep(400);
      const t = await ev(MEASURE);
      check(tag + ' B trip state: 商期　15日 / 22日, numbers bold 700 at date + 1 px (' + (t.time.trip.strong && t.time.trip.strong.font) + ' px), rows unchanged, still inside the first layer', /^商期\s*15日 \/ 22日$/.test(t.time.trip.text) && t.time.trip.strong && t.time.trip.strong.weight === '700' && t.time.trip.strong.font === numExp && t.time.trip.weight === '400' && Math.abs(t.time.trip.lineHeight - dateExp * lhExp) < .6 && Math.abs(t.time.trip.strong.lineHeight - dateExp * lhExp) < .6 && rowsOk(t) && edgeOk(t) && Math.abs(t.time.block.h - m.time.block.h) < .8, JSON.stringify({ text: t.time.trip.text, strong: t.time.trip.strong, overflow: [t.time.year.overflow, t.time.date.overflow, t.time.trip.overflow], block: [t.time.block.y, t.time.block.bottom, t.time.block.h, m.time.block.h], top: [t.top.y, t.top.bottom] }));
      if (w === 390 || w === 320 || w === 430) { const shot = path.join(outDir, '02-' + name + '-trip.png'); await c.screenshot(shot); shots.push(shot); }
      fs.writeFileSync(path.join(outDir, 'measure-' + name + '.json'), JSON.stringify({ unstarted: m, trip: t }, null, 1));
      const errs = c.console.filter(m => m.type === 'error' || m.type === 'exception').map(m => m.text.slice(0, 120)); check(tag + ' no console errors', errs.length === 0, JSON.stringify(errs.slice(0, 2)));
    } catch (e) { check(name + ' script error', false, String(e && e.message || e)); }
    await c.close();
  }
  srv.stop();
  const passed = checks.filter(x => x.ok).length;
  fs.writeFileSync(path.join(outDir, 'hud-run.json'), JSON.stringify({ label, passed, total: checks.length, checks, shots }, null, 2));
  console.log(`hud browser run [${label}]: ${passed}/${checks.length} → ` + outDir);
  process.exit(passed === checks.length ? 0 : 1);
})();
