'use strict';
// 市场交易页 UI/UX — approved implementation (2026-09-13) + MARKET_UI_CORRECTION v0.2 — runtime acceptance in headless Chrome
// (390×844, mobile emulation). Covers: title / three-column status · time hint · 25/75 cards with the three-row layout · one tag
// component · buttons-only expand (no body tap) · compact unclamped stepper with live feedback · locked goods truly disabled with a
// visible reason · goodId aggregation (no lot picker; partial multi-lot refused with the pending-rule feedback) · provisions card ·
// button tiers · three bottom entries · MARKET_EXIT_CONFIRM / time advance.
// Usage: node tests/browser/market-run.js [label] [--root <dir>] [--port <http>] [--cdp <chrome port>]
const fs = require('fs'), path = require('path');
const { launch, startServer, sleep } = require('../tools/cdp');
const root = path.join(__dirname, '..', '..');
const argv = process.argv.slice(2), flag = n => { const i = argv.indexOf(n); return i >= 0 ? argv[i + 1] : null; };
const label = argv.find((a, i) => !a.startsWith('--') && (i === 0 || !argv[i - 1].startsWith('--'))) || 'market';
const serveRoot = flag('--root') ? path.resolve(flag('--root')) : root;
const outDir = path.join(root, 'tests', 'results', 'evidence', 'market-' + label); fs.rmSync(outDir, { recursive: true, force: true }); fs.mkdirSync(outDir, { recursive: true });
const checks = []; let shotIndex = 0;
const check = (name, ok, detail) => { checks.push({ name, ok: Boolean(ok), detail: detail === undefined ? '' : String(detail).slice(0, 400) }); console.log((ok ? 'PASS ' : 'FAIL ') + name + (detail !== undefined ? '  ' + String(detail).slice(0, 220) : '')); };
(async () => {
  const port = Number(flag('--port')) || 8272, srv = startServer(port, serveRoot); await sleep(500);
  const c = await launch({ port: Number(flag('--cdp')) || 9621, width: 390, height: 844, mobile: true });
  const ev = js => c.eval(js);
  const shot = async name => { const f = String(++shotIndex).padStart(2, '0') + '-' + name + '.png'; await c.screenshot(path.join(outDir, f)); return f; };
  const waitFor = async (js, ms = 8000) => { const t0 = Date.now(); while (Date.now() - t0 < ms) { if (await ev(js)) return true; await sleep(80); } return false; };
  const busyWait = () => waitFor('!Silk.app.busy', 8000);
  const M = '[data-panel-id="market"]';
  const vis = `(e=>e&&e.offsetParent!==null)`;
  const clickBtn = (scope, text) => ev(`(()=>{const s=document.querySelector(${JSON.stringify(scope)})||document;const b=[...s.querySelectorAll('button')].find(b=>!b.disabled&&b.offsetParent!==null&&b.textContent.trim().startsWith(${JSON.stringify(text)}));if(!b)return false;b.click();return true})()`);
  const cardBtn = (goodId, action) => ev(`(()=>{const b=document.querySelector('${M} .market-product[data-good-id="${goodId}"] .market-card-actions button[data-action="${action}"]');if(!b||b.disabled)return false;b.click();return true})()`);
  // open a mode without toggling an already-open one (the expand persists across trades)
  const ensureMode = async (goodId, mode) => { const cur = await ev(`(()=>{const k=document.querySelector('${M} .market-product[data-good-id="${goodId}"]');return k&&k.classList.contains('is-expanded')?k.dataset.mode:null})()`); if (cur === mode) return true; return cardBtn(goodId, mode); };
  const st = () => ev('(()=>{const p=Silk.app.state.progress;const v=p.market.visit;return {tick:p.world.tick,cash:p.cash,visit:v?{id:v.id,settled:v.settled,had:v.hadActivity}:null,result:p.presentation.activeResult?p.presentation.activeResult.kind:null,lots:p.inventory.lots.map(l=>({g:l.goodId,q:l.quantity,id:l.id})),provisions:p.inventory.provisions,used:Silk.inventory.used(p),cap:Silk.inventory.capacity(p)}})()');
  const ack = async () => { await ev(`(()=>{const p=Silk.app.state.progress;const ar=p.presentation.activeResult;if(ar)Silk.ui.dispatch('result.ack',{resultId:ar.id});})()`); await busyWait(); await sleep(250); };
  const setState = js => ev(`(()=>{const p=Silk.app.state.progress;${js};Silk.ui.render(Silk.app.state);return true})()`);
  const typeQty = text => ev(`(()=>{const i=document.querySelector('${M} .trade-expand .stepper-input');if(!i)return null;i.focus();i.value=${JSON.stringify(text)};i.dispatchEvent(new Event('input',{bubbles:true}));return i.value})()`);
  const pressPlus = () => ev(`(()=>{const b=document.querySelector('${M} .trade-expand .stepper-plus');if(!b||b.disabled)return false;b.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerId:1}));b.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,pointerId:1}));return true})()`);
  const expandInfo = () => ev(`(()=>{const card=document.querySelector('${M} .market-product.is-expanded');if(!card)return null;const te=card.querySelector('.trade-expand');const r=e=>{const b=e.getBoundingClientRect();return {x:+b.x.toFixed(1),y:+b.y.toFixed(1),w:+b.width.toFixed(1),h:+b.height.toFixed(1)}};const left=te.querySelector('.trade-summary-left'),right=te.querySelector('.trade-summary-right'),confirm=te.querySelector(':scope>.ui-button'),reason=te.querySelector('.trade-block-reason');const i=te.querySelector('.stepper-input'),plus=te.querySelector('.stepper-plus');return {goodId:card.dataset.goodId,mode:card.dataset.mode,expanded:[...document.querySelectorAll('${M} .market-product:not(.provisions-product).is-expanded')].length,buttons:[...card.querySelectorAll('.market-card-actions button')].map(b=>b.textContent.trim()),value:i.value,inputType:i.type,inputMode:i.inputMode,plusDisabled:plus.disabled,stepperH:r(plus).h,inputW:r(i).w,fieldLabel:te.querySelector('.field-label').textContent,text:te.innerText.replace(/\\s+/g,' '),left:left.textContent,right:right.textContent,leftRect:r(left),rightRect:r(right),confirmText:confirm.textContent.trim(),confirmDisabled:confirm.disabled,confirmRect:r(confirm),reason:reason.hidden?'':reason.textContent,reasonColor:getComputedStyle(reason).color,reasonRect:r(reason),reasonFont:parseFloat(getComputedStyle(reason).fontSize),lotUi:card.querySelectorAll('.lot-picker,.lot-choice').length}})()`);
  const isReddish = col => { const m = col.match(/\d+/g).map(Number); return m[0] > 140 && m[1] < 90 && m[2] < 90; };
  try {
    await c.navigate('http://127.0.0.1:' + port + '/'); await sleep(900); await ev('new Promise(r=>{const t=setInterval(()=>{if(window.Silk&&Silk.app&&Silk.app.state){clearInterval(t);r()}},100)})');
    if (await ev('Boolean(Silk.app.state.progress)')) { await ev("Silk.ui.dispatch('game.reset')"); await sleep(600); }
    await clickBtn('body', '启程'); await ev('new Promise(r=>{const t=setInterval(()=>{const p=Silk.app.state.progress;if(p&&p.world){clearInterval(t);r()}},100)})'); await sleep(400); await clickBtn('body', '自行探索'); await sleep(500);
    await ev(`document.querySelector('.city-hotspot[data-hotspot="market"]').click()`); await sleep(1000); await busyWait();
    let s = await st(); const tick0 = s.tick; check('setup: market visit open in 长安, no trade yet', s.visit && !s.visit.settled && s.visit.had === false, JSON.stringify(s.visit));
    // ---------------- title / status / hint / typography
    const head = await ev(`(()=>{const h=document.querySelector('${M}>.panel-header');const h2=h.querySelector('h2');const hr=h.getBoundingClientRect(),tr=h2.getBoundingClientRect();const cs=getComputedStyle(h2);const cells=[...h.querySelectorAll('.market-status-cell')].map(cell=>{const l=cell.querySelector('.status-label'),v=cell.querySelector('.status-value');const cr=cell.getBoundingClientRect();return {label:l.textContent.trim(),value:v.textContent,labelWeight:getComputedStyle(l).fontWeight,labelSize:parseFloat(getComputedStyle(l).fontSize),valueWeight:getComputedStyle(v).fontWeight,valueSize:parseFloat(getComputedStyle(v).fontSize),y:+cr.y.toFixed(1),icon:Boolean(cell.querySelector('img.ui-icon'))&&cell.querySelector('img.ui-icon').naturalWidth>0,clipped:cell.scrollWidth>cell.clientWidth+1}});const hint=h.querySelector('.market-time-hint');const hs=getComputedStyle(hint);return {title:h2.textContent,align:cs.textAlign,titleSize:parseFloat(cs.fontSize),titleWeight:cs.fontWeight,titleColor:cs.color,titleCenterDelta:+((tr.x+tr.width/2)-(hr.x+hr.width/2)).toFixed(1),cells,hint:{text:hint.textContent,align:hs.textAlign,color:hs.color,weight:hs.fontWeight,size:parseFloat(hs.fontSize)}}})()`);
    check('title centred, page-title tier (' + head.titleSize + ' px / ' + head.titleWeight + ', deepest warm brown)', head.align === 'center' && Math.abs(head.titleCenterDelta) <= 2 && head.titleSize >= 20 && Number(head.titleWeight) >= 600 && head.titleColor === 'rgb(60, 45, 35)', JSON.stringify({ size: head.titleSize, weight: head.titleWeight, color: head.titleColor, delta: head.titleCenterDelta }));
    check('three status columns on one row with icons; labels small regular, values larger bold; 钱 kept; 商报 ∈ 最新|历史|未购买; nothing clipped', head.cells.length === 3 && head.cells.map(x => x.label).join('|') === '可用货位|随身铜钱|商报' && head.cells.every(x => x.icon && Number(x.labelWeight) < 600 && Number(x.valueWeight) >= 600 && x.valueSize > x.labelSize && !x.clipped) && Math.max(...head.cells.map(x => x.y)) - Math.min(...head.cells.map(x => x.y)) <= 2 && head.cells[0].value === s.cap - s.used + '/' + s.cap && head.cells[1].value === s.cash.toLocaleString('zh-CN') + '钱' && ['最新', '历史', '未购买'].includes(head.cells[2].value), JSON.stringify(head.cells));
    check('time hint before any trade: 查看市价不推进时间 — small, regular, left, not red', head.hint.text === '查看市价不推进时间' && head.hint.align === 'left' && !isReddish(head.hint.color) && Number(head.hint.weight) <= 500 && head.hint.size < head.cells[0].valueSize, JSON.stringify(head.hint));
    await shot('unheld-goods-collapsed');
    // ---------------- card layout (unheld)
    const cardInfo = goodId => ev(`(()=>{const card=document.querySelector('${M} .market-product[data-good-id="${goodId}"]');if(!card)return null;const r=e=>e.getBoundingClientRect();const cr=r(card),ir=r(card.querySelector('img.goods-art')),info=r(card.querySelector('.market-info'));const cs=getComputedStyle(card);const inner=cr.width-parseFloat(cs.paddingLeft)-parseFloat(cs.paddingRight);const t=card.querySelector('.market-title');const ts=getComputedStyle(t.querySelector('.goods-name'));const tags=[...card.querySelectorAll('.market-tag')].map(x=>{const s=getComputedStyle(x);return {text:x.textContent,weight:s.fontWeight,size:parseFloat(s.fontSize),color:s.color,radius:s.borderRadius,padding:s.padding,border:s.borderWidth,h:+r(x).height.toFixed(1)}});const rows=[...card.querySelectorAll('.market-stat-line')].map(l=>({text:l.innerText.replace(/\\s+/g,' '),cls:l.className,items:[...l.querySelectorAll('.stat-item')].map(it=>{const lab=it.querySelector('.stat-label'),val=it.querySelector('.stat-value');return {label:lab.textContent.trim(),value:val.textContent,labelWeight:getComputedStyle(lab).fontWeight,valueWeight:getComputedStyle(val).fontWeight,size:parseFloat(getComputedStyle(val).fontSize),x:+r(it).x.toFixed(1),y:+r(it).y.toFixed(1)}})}));const note=card.querySelector('.locked-reason');const buy=card.querySelector('button[data-action="buy"]'),sell=card.querySelector('button[data-action="sell"]');return {goodId:card.dataset.goodId,imgRatio:+(ir.width/inner).toFixed(3),infoRatio:+(info.width/inner).toFixed(3),imgNatural:card.querySelector('img.goods-art').naturalWidth>0,titleSize:parseFloat(ts.fontSize),titleWeight:ts.fontWeight,titleColor:ts.color,tags,rows,locked:card.classList.contains('locked-product'),lockedReason:note?note.textContent:null,lockedReasonVisible:note?note.offsetParent!==null:false,lockedReasonColor:note?getComputedStyle(note).color:null,buy:{text:buy.textContent.trim(),disabled:buy.disabled,opacity:getComputedStyle(buy).opacity},sell:{text:sell.textContent.trim(),disabled:sell.disabled},expanded:card.classList.contains('is-expanded'),h:+cr.height.toFixed(1)}})()`);
    const g1 = await ev(`(()=>{const k=document.querySelector('${M} .market-product:not(.provisions-product):not(.locked-product)');return k?k.dataset.goodId:null})()`);
    let card = await cardInfo(g1);
    check('unheld card: image ≈25 % / text ≈75 % (' + card.imgRatio + ' / ' + card.infoRatio + '), image intact (contain)', card.imgRatio >= 0.22 && card.imgRatio <= 0.28 && card.infoRatio >= 0.68 && card.infoRatio <= 0.75 && card.imgNatural, JSON.stringify({ img: card.imgRatio, info: card.infoRatio }));
    check('unheld card: rows 当前价格 N钱 · 货位 n/件 / 持有 0 · 商报 未购买, no holding row, values semibold, labels regular', card.rows.length === 2 && card.rows[0].items.map(i => i.label).join('|') === '当前价格|货位' && /^\d[\d,]*钱$/.test(card.rows[0].items[0].value) && /^\d\/件$/.test(card.rows[0].items[1].value) && card.rows[1].items.map(i => i.label).join('|') === '持有|商报' && card.rows[1].items[0].value === '0' && card.rows[1].items[1].value === '未购买' && card.rows.every(r => r.items.every(i => Number(i.labelWeight) < 600 && Number(i.valueWeight) >= 600)), JSON.stringify(card.rows.map(r => r.text)));
    check('typography: card title tier between page title and body (' + card.titleSize + ' px / ' + card.titleWeight + '), body smaller (' + card.rows[0].items[0].size + ' px), row values align to fixed columns', card.titleSize < head.titleSize && card.titleSize > card.rows[0].items[0].size && Number(card.titleWeight) >= 600 && card.titleColor === 'rgb(60, 45, 35)' && card.rows[0].items[0].size <= 12.5 && Math.abs(card.rows[0].items[1].x - card.rows[1].items[1].x) <= 0.5, JSON.stringify({ title: [card.titleSize, card.titleWeight], body: card.rows[0].items[0].size, col2x: [card.rows[0].items[1].x, card.rows[1].items[1].x] }));
    const fragile = await cardInfo('唐代陶瓷');
    check('tags: one component (radius/padding/border/height), 长安特产 bold + darker, 易碎 regular + lighter, both smaller than the name', fragile && fragile.tags.length === 2 && fragile.tags[0].text === '长安特产' && fragile.tags[1].text === '易碎' && Number(fragile.tags[0].weight) >= 700 && Number(fragile.tags[1].weight) < 600 && fragile.tags[0].radius === fragile.tags[1].radius && fragile.tags[0].padding === fragile.tags[1].padding && fragile.tags[0].border === fragile.tags[1].border && Math.abs(fragile.tags[0].h - fragile.tags[1].h) <= 1 && fragile.tags.every(t => t.size < fragile.titleSize) && fragile.tags[0].color !== fragile.tags[1].color, JSON.stringify(fragile && fragile.tags));
    check('no explanatory paragraph between the provisions card and the first goods card', await ev(`(()=>{const prov=document.querySelector('${M} .provisions-product');let n=prov.nextElementSibling;return n&&n.classList.contains('market-product')})()`), 'first sibling after provisions is a goods card');
    // ---------------- locked goods
    const lockedId = await ev(`(()=>{const k=document.querySelector('${M} .market-product.locked-product');return k?k.dataset.goodId:null})()`);
    const locked = lockedId ? await cardInfo(lockedId) : null;
    check('locked good: 买入 truly disabled (aria/disabled), reason visible without any tap, secondary colour (not brick red)', locked && locked.buy.disabled && locked.lockedReasonVisible && /货源|解锁/.test(locked.lockedReason) && !isReddish(locked.lockedReasonColor) && !locked.expanded, JSON.stringify(locked && { buy: locked.buy, reason: locked.lockedReason }));
    const lockedTap = await ev(`(()=>{const b=document.querySelector('${M} .market-product[data-good-id="${lockedId}"] button[data-action="buy"]');b.click();return document.querySelectorAll('${M} .market-product.is-expanded').length})()`);
    check('locked good: programmatic click on the disabled 买入 does nothing', lockedTap === 0, lockedTap); await shot('locked-good');
    // ---------------- expand / collapse / switch (buttons only)
    const bodyTap = await ev(`(()=>{const card=document.querySelector('${M} .market-product[data-good-id="${g1}"]');card.querySelector('.market-info').click();card.querySelector('img.goods-art').click();return document.querySelectorAll('${M} .market-product.is-expanded').length})()`); await sleep(150);
    check('card body / image tap does not enter any trade mode', bodyTap === 0, bodyTap);
    await cardBtn(g1, 'buy'); await sleep(250); let x = await expandInfo();
    check('买入⌄ expands the card: 买入⌃ / 卖出⌄, 交易数量 label, compact stepper (' + (x && x.stepperH) + ' px, input ' + (x && x.inputW) + ' px), 确认买入; no 单价 / 最多 / lot UI', x && x.goodId === g1 && x.mode === 'buy' && x.buttons.join('|') === '买入⌃|卖出⌄' && x.fieldLabel === '交易数量' && x.stepperH <= 36 && x.inputW <= 72 && x.confirmText === '确认买入' && !/单价|最多/.test(x.text) && x.lotUi === 0 && x.inputMode === 'numeric', JSON.stringify(x && { b: x.buttons, h: x.stepperH, w: x.inputW, text: x.text }));
    check('buy summary one line: 本次合计 N钱 · 占用货位 M, right column fixed', /^本次合计 \d[\d,]*钱$/.test(x.left) && /^占用货位 \d+$/.test(x.right) && Math.abs(x.leftRect.y - x.rightRect.y) <= 1, JSON.stringify({ l: x.left, r: x.right }));
    const rightX1 = x.rightRect.x; await typeQty('120'); await sleep(150); x = await expandInfo();
    check('right column start unchanged with a 3-digit amount (' + rightX1 + ' → ' + x.rightRect.x + ')', Math.abs(x.rightRect.x - rightX1) <= 0.5, JSON.stringify({ before: rightX1, after: x.rightRect.x, left: x.left }));
    await shot('buy-expanded');
    // ---------------- stepper: no clamp, live feedback
    await typeQty('999'); await sleep(150); x = await expandInfo(); s = await st();
    check('typing 999: not clamped to the tradable maximum; confirm disabled; feedback 货位不足，还需 N 个货位 (N = 999×slot − available)', x && x.value === '999' && x.confirmDisabled && x.reason === '货位不足，还需 ' + (999 * 1 - (s.cap - s.used)) + ' 个货位' && isReddish(x.reasonColor) && x.reasonRect.y >= x.confirmRect.y + x.confirmRect.h - 1 && x.reasonFont < 12, JSON.stringify(x && { v: x.value, reason: x.reason, disabled: x.confirmDisabled, font: x.reasonFont }));
    await shot('feedback-slots');
    await typeQty('2'); await sleep(150); x = await expandInfo(); check('back to 2: feedback gone at once, confirm enabled', x && x.reason === '' && !x.confirmDisabled, JSON.stringify(x && { reason: x.reason, disabled: x.confirmDisabled }));
    const cashReal = (await st()).cash; await setState('p.cash=5'); await sleep(250); x = await expandInfo();
    check('cash drops while open (5钱): 随身铜钱不足 shown at once, confirm disabled; value kept (no clamp)', x && x.reason === '随身铜钱不足' && x.confirmDisabled && x.value === '2', JSON.stringify(x && { reason: x.reason, v: x.value }));
    await shot('feedback-cash');
    await setState(`p.cash=${cashReal}`); await sleep(250); x = await expandInfo(); check('cash restored: feedback disappears immediately, confirm enabled', x && x.reason === '' && !x.confirmDisabled, JSON.stringify(x && x.reason));
    await pressPlus(); await sleep(120); x = await expandInfo(); check('+ keeps working past the tradable range (3 → still no clamp, plus enabled)', x && x.value === '3' && !x.plusDisabled, JSON.stringify(x && { v: x.value, plus: x.plusDisabled }));
    await typeQty('2'); await sleep(120); let before = await st(); await clickBtn(M, '确认买入'); await busyWait(); await sleep(500); s = await st();
    check('确认买入 executes the existing rule (2 件, cash down)', s.lots.some(l => l.g === g1 && l.q === 2) && s.cash < before.cash, JSON.stringify({ lots: s.lots, cash: [before.cash, s.cash] })); await ack();
    // ---------------- held card, second lot, sell aggregation
    card = await cardInfo(g1);
    check('held card: third row 持有成本 / 可售价值 / 盈亏 with 钱 appears only now; 持有 2', card.rows.length === 3 && card.rows[1].items[0].value === '2' && card.rows[2].items.map(i => i.label).join('|') === '持有成本|可售价值|盈亏' && card.rows[2].items.every(i => /钱$/.test(i.value)), JSON.stringify(card.rows.map(r => r.text)));
    await shot('held-goods');
    const hint2 = await ev(`(()=>{const h=document.querySelector('${M} .market-time-hint');return h.textContent})()`); check('time hint after a trade: 已发生交易 · 离市后将推进半日 (tick unchanged)', hint2 === '已发生交易 · 离市后将推进半日' && (await st()).tick === tick0, hint2);
    // second purchase creates a second backend lot; the card must still aggregate by goodId
    await ensureMode(g1, 'buy'); await sleep(200); await typeQty('1'); await sleep(100); await clickBtn(M, '确认买入'); await busyWait(); await sleep(400); await ack(); s = await st();
    const lotsOfG1 = s.lots.filter(l => l.g === g1); card = await cardInfo(g1);
    check('two backend lots (metadata kept, not merged) → card shows aggregated 持有 3 and one cost/value/profit line, no batch info', lotsOfG1.length === 2 && card.rows[1].items[0].value === '3' && card.rows.length === 3 && !/批|lot/i.test(card.rows.map(r => r.text).join(' ')), JSON.stringify({ lots: lotsOfG1, row2: card.rows[1].text }));
    await ensureMode(g1, 'sell'); await sleep(250); x = await expandInfo();
    check('卖出⌄ switches to sell: 买入⌄ / 卖出⌃, 本次可得 · 释放货位, 确认出售, no lot picker / batch UI', x && x.mode === 'sell' && x.buttons.join('|') === '买入⌄|卖出⌃' && /^本次可得 \d[\d,]*钱$/.test(x.left) && /^释放货位 \d+$/.test(x.right) && x.confirmText === '确认出售' && x.lotUi === 0 && !/批|单价|最多/.test(x.text.replace(x.reason, '')), JSON.stringify(x && { b: x.buttons, l: x.left, r: x.right, text: x.text }));
    await shot('sell-expanded');
    await typeQty('2'); await sleep(150); x = await expandInfo();
    check('partial quantity over two outcome-equivalent lots: normal transaction info only, no red text, confirm enabled', x && !x.confirmDisabled && x.reason === '' && /^本次可得 \d[\d,]*钱$/.test(x.left) && x.right === '释放货位 2', JSON.stringify(x && { reason: x.reason, disabled: x.confirmDisabled, l: x.left, r: x.right }));
    await typeQty('9'); await sleep(150); x = await expandInfo(); check('quantity above 持有: 出售件数无效, not clamped', x && x.value === '9' && x.confirmDisabled && x.reason === '出售件数无效', JSON.stringify(x && { v: x.value, reason: x.reason }));
    // the undecided case: lots with different cost — confirm unavailable, no player-facing copy about lots / rules
    await setState(`const ls=Silk.market.marketableLots(p,${JSON.stringify(g1)});ls[0].acquisitionPrice+=1`); await sleep(250); await typeQty('1'); await sleep(150); x = await expandInfo();
    check('partial quantity over NON-equivalent lots (different cost): confirm unavailable, nothing red, no lot / rule copy anywhere in the card', x && x.confirmDisabled && x.reason === '' && !/批|扣减|FIFO|LIFO|规则/.test(x.text), JSON.stringify(x && { disabled: x.confirmDisabled, reason: x.reason, text: x.text }));
    await setState(`const ls=Silk.market.marketableLots(p,${JSON.stringify(g1)});ls[0].acquisitionPrice-=1`); await sleep(250); await typeQty('3'); await sleep(150); x = await expandInfo(); check('全部 3 件: confirm enabled', x && !x.confirmDisabled && x.reason === '', JSON.stringify(x && x.reason));
    await ev(`(()=>{const orig=Silk.commands.run;window.__lastDispatch=null;Silk.commands.run=function(p,command,ctx){if(command&&command.type==='market.sell')window.__lastDispatch={type:command.type,payload:JSON.parse(JSON.stringify(command.payload))};return orig.call(this,p,command,ctx)};return true})()`);
    await clickBtn(M, '确认出售'); await busyWait(); await sleep(500); const lastDispatch = await ev('window.__lastDispatch'); await ev(`(()=>{return true})()`); s = await st();
    check('UI sell payload is goodId + quantity only (no lotId); 3 件 sold across the two lots', lastDispatch && lastDispatch.type === 'market.sell' && lastDispatch.payload.goodId === g1 && lastDispatch.payload.quantity === 3 && !('lotId' in lastDispatch.payload) && !s.lots.some(l => l.g === g1), JSON.stringify({ lastDispatch, lots: s.lots })); await ack();
    await ensureMode(g1, 'buy'); await sleep(200); x = await expandInfo(); await cardBtn(g1, 'buy'); await sleep(200); const collapsed = await ev(`document.querySelectorAll('${M} .market-product:not(.provisions-product).is-expanded').length`);
    check('active 买入⌃ tapped again → collapses; only one card expands at a time', x && x.mode === 'buy' && collapsed === 0, JSON.stringify({ mode: x && x.mode, collapsed }));
    const g2 = await ev(`(()=>{const cards=[...document.querySelectorAll('${M} .market-product:not(.provisions-product):not(.locked-product)')];const o=cards.find(k=>k.dataset.goodId!=='${g1}');return o?o.dataset.goodId:null})()`);
    await cardBtn(g1, 'buy'); await sleep(150); await cardBtn(g2, 'buy'); await sleep(200); x = await expandInfo(); check('opening another card switches the single expanded card', x && x.goodId === g2 && x.expanded === 1, JSON.stringify(x && { g: x.goodId, n: x.expanded })); await cardBtn(g2, 'buy'); await sleep(150);
    // ---------------- provisions card
    const prov = await ev(`(()=>{const card=document.querySelector('${M} .provisions-product'),normal=document.querySelector('${M} .market-product:not(.provisions-product)');const lines=[...card.querySelectorAll('.market-stat-line, .provisions-head, .form-hint')].map(l=>l.innerText.replace(/\\s+/g,' '));return {bg:getComputedStyle(card).backgroundColor,normalBg:getComputedStyle(normal).backgroundColor,lines,button:card.querySelector('.market-card-actions button').textContent.trim()}})()`);
    check('provisions card unchanged: special background, lines, card-level 购买粮草⌄', prov.bg !== prov.normalBg && /粮草补给 现有补给 \d+日份/.test(prov.lines[0]) && /单价 1钱 \/ 商队日份 有补给时共用 1货位/.test(prov.lines[1]) && /下一程 长安 → 敦煌 · 基础路程3日/.test(prov.lines[2]) && prov.lines[3] === '途中事件可能延误' && prov.button === '购买粮草⌄', JSON.stringify(prov));
    await clickBtn(M + ' .provisions-product', '购买粮草'); await sleep(250); await ev(`(()=>{const i=document.querySelector('${M} .provisions-product .stepper-input');i.focus();i.value='3';i.dispatchEvent(new Event('input',{bubbles:true}));return true})()`); await sleep(150);
    const pe = await ev(`(()=>{const te=document.querySelector('${M} .provisions-product .trade-expand');return {label:te.querySelector('.field-label').textContent,left:te.querySelector('.trade-summary-left').textContent,right:te.querySelector('.trade-summary-right').textContent,confirm:te.querySelector(':scope>.ui-button').textContent.trim(),h:te.querySelector('.stepper-plus').getBoundingClientRect().height}})()`);
    check('provisions expand: 购买日份 compact stepper, 本次合计 3钱 · 购买后共有 3日份, 确认购买', pe.label === '购买日份' && pe.left === '本次合计 3钱' && pe.right === '购买后共有 3日份' && pe.confirm === '确认购买' && pe.h <= 36, JSON.stringify(pe));
    await clickBtn(M + ' .provisions-product', '确认购买'); await busyWait(); await sleep(400); s = await st(); check('确认购买 buys 3 日份', s.provisions === 3, s.provisions); await ack();
    // ---------------- tiers / bottom entries
    const sizes = await ev(`(()=>{const r=e=>e.getBoundingClientRect();const leave=[...document.querySelectorAll('${M}>.panel-footer button')].find(b=>b.textContent.trim()==='离开市场');const buy=document.querySelector('${M} .market-card-actions button[data-action="buy"]');const tools=[...document.querySelectorAll('${M} .market-tools button')];const toolsBox=document.querySelector('${M} .market-tools');toolsBox.scrollIntoView({block:'end'});const gap=parseFloat(getComputedStyle(toolsBox).columnGap||getComputedStyle(toolsBox).gap)||0;return {leaveH:+r(leave).height.toFixed(1),leaveWeight:getComputedStyle(leave).fontWeight,buyH:+r(buy).height.toFixed(1),buyFont:parseFloat(getComputedStyle(buy).fontSize),leaveFont:parseFloat(getComputedStyle(leave).fontSize),provH:+r(document.querySelector('${M} .provisions-product .market-card-actions button')).height.toFixed(1),tools:tools.map(b=>({t:b.textContent.trim(),w:+r(b).width.toFixed(1),h:+r(b).height.toFixed(1),y:+r(b).y.toFixed(1)})),gap,toolsW:+r(toolsBox).width.toFixed(1)}})()`);
    const ratio = sizes.buyH / sizes.leaveH;
    check('page-level 离开市场 (' + sizes.leaveH + ' px, ' + sizes.leaveWeight + ') clearly above the card tier (' + sizes.buyH + ' px, ratio ' + ratio.toFixed(2) + '); provisions entry same tier', ratio >= 0.68 && ratio <= 0.82 && Number(sizes.leaveWeight) >= 600 && sizes.leaveFont > sizes.buyFont && Math.abs(sizes.provH - sizes.buyH) <= 1, JSON.stringify(sizes));
    check('一键出售 / 查看委托 / 查看商情: one row, equal thirds, card tier', sizes.tools.map(t => t.t).join('|') === '一键出售|查看委托|查看商情' && Math.max(...sizes.tools.map(t => t.y)) - Math.min(...sizes.tools.map(t => t.y)) <= 1 && Math.max(...sizes.tools.map(t => t.w)) - Math.min(...sizes.tools.map(t => t.w)) <= 1 && sizes.tools.every(t => Math.abs(t.h - sizes.buyH) <= 1) && Math.abs(sizes.tools[0].w * 3 + sizes.gap * 2 - sizes.toolsW) <= 2, JSON.stringify(sizes.tools));
    // ---------------- exit flow
    s = await st(); check('trades happened, tick unchanged so far', s.visit && s.visit.had === true && s.tick === tick0, JSON.stringify({ had: s.visit && s.visit.had, tick: s.tick }));
    await clickBtn(M + '>.panel-footer', '离开市场'); await sleep(400); s = await st();
    const confirmPanel = await ev(`(()=>{const p=document.querySelector('[data-panel-id="market-exit-confirm"]');if(!p||p.offsetParent===null)return null;const h2=p.querySelector('h2');return {title:h2.textContent,titleSize:parseFloat(getComputedStyle(h2).fontSize),text:p.querySelector('.panel-body').innerText.replace(/\\s+/g,' '),footer:[...p.querySelectorAll('.panel-footer button')].map(b=>({t:b.textContent.trim(),h:+b.getBoundingClientRect().height.toFixed(1)}))}})()`);
    check('with trades: 离开市场 → MARKET_EXIT_CONFIRM (page-title tier, aggregated summary, 返回市场 | 确认离市 page-level), 0 tick, visit open', confirmPanel && confirmPanel.titleSize >= 20 && confirmPanel.footer.map(b => b.t).join('|') === '返回市场|确认离市' && confirmPanel.footer.every(b => b.h >= sizes.leaveH - 1) && /买入 .* × 3/.test(confirmPanel.text) && /卖出 .* × 3/.test(confirmPanel.text) && /补给 \+3日份/.test(confirmPanel.text) && s.tick === tick0 && s.visit && !s.visit.settled, JSON.stringify({ confirmPanel, tick: s.tick }));
    await shot('exit-confirm');
    await clickBtn('[data-panel-id="market-exit-confirm"]', '返回市场'); await sleep(300); s = await st();
    check('返回市场: same visit, 0 tick, market visible again', s.visit && s.visit.id === before.visit.id && !s.visit.settled && s.tick === tick0 && await ev(`(()=>{const v=${vis};return v(document.querySelector('${M} .market-product'))&&!v(document.querySelector('[data-panel-id="market-exit-confirm"]'))})()`), JSON.stringify({ visit: s.visit, tick: s.tick }));
    await ensureMode(g2, 'buy'); await sleep(200); await typeQty('1'); await sleep(100); await clickBtn(M, '确认买入'); await busyWait(); await sleep(400); await ack();
    await clickBtn(M + '>.panel-footer', '离开市场'); await sleep(400); const confirm2 = await ev(`(()=>{const p=document.querySelector('[data-panel-id="market-exit-confirm"]');return p?p.querySelector('.panel-body').innerText.replace(/\\s+/g,' '):null})()`);
    check('leaving again regenerates the latest summary (now includes ' + g2 + ' × 1), still 0 tick', confirm2 && new RegExp('买入 ' + g2 + ' × 1').test(confirm2) && (await st()).tick === tick0, JSON.stringify({ confirm2, tick: (await st()).tick }));
    await clickBtn('[data-panel-id="market-exit-confirm"]', '确认离市'); await busyWait(); await sleep(600); s = await st();
    check('确认离市: visit closed, exactly +1 tick, straight back to the city (no result card, no panels)', s.visit && s.visit.settled && s.tick === tick0 + 1 && s.result === null && await ev(`(()=>{const v=${vis};return !v(document.querySelector('${M}'))&&!v(document.querySelector('[data-panel-id="market-exit-confirm"]'))&&!v(document.querySelector('section.paper-panel.result-panel'))})()`), JSON.stringify({ visit: s.visit, tick: s.tick, result: s.result }));
    await shot('after-confirm-city');
    const again = await ev(`Silk.ui.dispatch('market.leave',{visitId:${JSON.stringify(s.visit.id)}}).then(r=>({r:r===null?null:r.kind}))`); await sleep(300); s = await st();
    check('repeated confirm for the same visit cannot advance again', s.tick === tick0 + 1, JSON.stringify({ again, tick: s.tick }));
    // no-trade visit
    await ev(`(()=>{const p=Silk.app.state.progress;const ev=p.eventSession;if(ev&&ev.status==='AWAITING_CHOICE'){const s=[...document.querySelectorAll('section.paper-panel')].find(x=>!x.hidden&&x.offsetParent!==null&&/商路见闻/.test(x.innerText));const btns=s?[...s.querySelectorAll('button')].filter(b=>!b.disabled&&b.offsetParent!==null&&b.closest('footer')===null):[];if(btns.length)btns[btns.length-1].click();}})()`); await busyWait(); await sleep(400); await ack();
    await ev(`(()=>{for(const s of document.querySelectorAll('section.paper-panel .close-button'))if(s.offsetParent!==null)s.click();})()`); await sleep(300);
    const opened = await ev(`(()=>{const h=document.querySelector('.city-hotspot[data-hotspot="market"]');if(!h)return false;h.click();return true})()`); await sleep(1000); await busyWait(); s = await st(); const tick1 = s.tick;
    if (opened && s.visit && !s.visit.settled) {
      await ensureMode(g2, 'buy'); await sleep(200); await typeQty('4'); await sleep(100);
      await clickBtn(M + '>.panel-footer', '离开市场'); await busyWait(); await sleep(500); s = await st();
      check('no successful trade (expand / edit only): 离开市场 → city directly, no confirm page, no summary, +0 tick', s.visit && s.visit.settled && s.tick === tick1 && s.result === null && await ev(`(()=>{const v=${vis};return !v(document.querySelector('${M}'))&&!v(document.querySelector('[data-panel-id="market-exit-confirm"]'))})()`), JSON.stringify({ visit: s.visit, tick: [tick1, s.tick], result: s.result }));
    } else check('second visit could be opened for the no-trade case', false, JSON.stringify({ opened, visit: s.visit, phase: s.tick % 3 }));
    const errs = c.console.filter(m => m.type === 'error' || m.type === 'exception').map(m => m.text.slice(0, 160)); check('no console errors', errs.length === 0, JSON.stringify(errs.slice(0, 3)));
  } catch (e) { check('script error', false, String(e && e.stack || e).slice(0, 400)); }
  await c.close(); srv.stop();
  const passed = checks.filter(x => x.ok).length;
  fs.writeFileSync(path.join(outDir, 'market-run.json'), JSON.stringify({ label, passed, total: checks.length, checks }, null, 2));
  console.log(`market browser run [${label}]: ${passed}/${checks.length} → ` + outDir);
  process.exit(passed === checks.length ? 0 : 1);
})();
