'use strict';
// 市场交易页 UI/UX (approved implementation, 2026-09-13) — runtime acceptance in headless Chrome (390×844, mobile emulation).
// Sections: 1 title + three-column status · 2 time hint · 3 card layout · 4 tags · 5 in-card expand · 6 blocking reasons ·
// 7 provisions card · 8 button tiers · 9 three bottom entries · 10 exit confirm / time advance (0 tick / once).
// Usage: node tests/browser/market-run.js [label] [--root <dir>] [--port <http>] [--cdp <chrome port>]
const fs = require('fs'), path = require('path');
const { launch, startServer, sleep } = require('../tools/cdp');
const root = path.join(__dirname, '..', '..');
const argv = process.argv.slice(2), flag = n => { const i = argv.indexOf(n); return i >= 0 ? argv[i + 1] : null; };
const label = argv.find((a, i) => !a.startsWith('--') && (i === 0 || !argv[i - 1].startsWith('--'))) || 'market';
const serveRoot = flag('--root') ? path.resolve(flag('--root')) : root;
const outDir = path.join(root, 'tests', 'results', 'evidence', 'market-' + label); fs.rmSync(outDir, { recursive: true, force: true }); fs.mkdirSync(outDir, { recursive: true });
const checks = []; let shotIndex = 0;
const check = (name, ok, detail) => { checks.push({ name, ok: Boolean(ok), detail: detail === undefined ? '' : String(detail).slice(0, 400) }); console.log((ok ? 'PASS ' : 'FAIL ') + name + (detail !== undefined ? '  ' + String(detail).slice(0, 220) : '')); };
(async () => {
  const port = Number(flag('--port')) || 8272, srv = startServer(port, serveRoot); await sleep(500);
  const c = await launch({ port: Number(flag('--cdp')) || 9621, width: 390, height: 844, mobile: true });
  const ev = js => c.eval(js);
  const shot = async name => { const f = String(++shotIndex).padStart(2, '0') + '-' + name + '.png'; await c.screenshot(path.join(outDir, f)); return f; };
  const waitFor = async (js, ms = 8000) => { const t0 = Date.now(); while (Date.now() - t0 < ms) { if (await ev(js)) return true; await sleep(80); } return false; };
  const busyWait = () => waitFor('!Silk.app.busy', 8000);
  const M = '[data-panel-id="market"]';
  const clickBtn = (scope, text) => ev(`(()=>{const s=document.querySelector(${JSON.stringify(scope)})||document;const b=[...s.querySelectorAll('button')].find(b=>!b.disabled&&b.offsetParent!==null&&b.textContent.trim().startsWith(${JSON.stringify(text)}));if(!b)return false;b.click();return true})()`);
  const cardBtn = (goodId, action) => ev(`(()=>{const b=document.querySelector('${M} .market-product[data-good-id="${goodId}"] .market-card-actions button[data-action="${action}"]');if(!b||b.disabled)return false;b.click();return true})()`);
  const st = () => ev('(()=>{const p=Silk.app.state.progress;const v=p.market.visit;return {tick:p.world.tick,cash:p.cash,visit:v?{id:v.id,settled:v.settled,had:v.hadActivity}:null,result:p.presentation.activeResult?p.presentation.activeResult.kind:null,lots:p.inventory.lots.map(l=>({g:l.goodId,q:l.quantity})),provisions:p.inventory.provisions,used:Silk.inventory.used(p),cap:Silk.inventory.capacity(p)}})()');
  const setState = js => ev(`(()=>{const p=Silk.app.state.progress;${js};Silk.ui.render(Silk.app.state);return true})()`);
  const typeQty = text => ev(`(()=>{const i=document.querySelector('${M} .trade-expand .stepper-input');if(!i)return null;i.focus();i.value=${JSON.stringify(text)};i.dispatchEvent(new Event('input',{bubbles:true}));return i.value})()`);
  const expandInfo = () => ev(`(()=>{const card=document.querySelector('${M} .market-product.is-expanded');if(!card)return null;const te=card.querySelector('.trade-expand');const r=e=>{const b=e.getBoundingClientRect();return {x:+b.x.toFixed(1),y:+b.y.toFixed(1),w:+b.width.toFixed(1),h:+b.height.toFixed(1)}};const left=te.querySelector('.trade-summary-left'),right=te.querySelector('.trade-summary-right'),confirm=te.querySelector(':scope>.ui-button'),reason=te.querySelector('.trade-block-reason');const i=te.querySelector('.stepper-input');return {goodId:card.dataset.goodId,mode:card.dataset.mode,expanded:[...document.querySelectorAll('${M} .market-product:not(.provisions-product).is-expanded')].length,buttons:[...card.querySelectorAll('.market-card-actions button')].map(b=>b.textContent.trim()),value:i.value,inputType:i.type,inputMode:i.inputMode,left:left.textContent,right:right.textContent,leftRect:r(left),rightRect:r(right),confirmText:confirm.textContent.trim(),confirmDisabled:confirm.disabled,confirmRect:r(confirm),reason:reason.hidden?'':reason.textContent,reasonColor:getComputedStyle(reason).color,reasonRect:r(reason),reasonFont:parseFloat(getComputedStyle(reason).fontSize)}})()`);
  try {
    await c.navigate('http://127.0.0.1:' + port + '/'); await sleep(900); await ev('new Promise(r=>{const t=setInterval(()=>{if(window.Silk&&Silk.app&&Silk.app.state){clearInterval(t);r()}},100)})');
    if (await ev('Boolean(Silk.app.state.progress)')) { await ev("Silk.ui.dispatch('game.reset')"); await sleep(600); }
    await clickBtn('body', '启程'); await ev('new Promise(r=>{const t=setInterval(()=>{const p=Silk.app.state.progress;if(p&&p.world){clearInterval(t);r()}},100)})'); await sleep(400); await clickBtn('body', '自行探索'); await sleep(500);
    await ev(`document.querySelector('.city-hotspot[data-hotspot="market"]').click()`); await sleep(1000); await busyWait();
    let s = await st(); const tick0 = s.tick; check('setup: market visit open in 长安, no trade yet', s.visit && !s.visit.settled && s.visit.had === false, JSON.stringify(s.visit));
    // ---------------- Section 1
    const head = await ev(`(()=>{const h=document.querySelector('${M}>.panel-header');const h2=h.querySelector('h2');const hr=h.getBoundingClientRect(),tr=h2.getBoundingClientRect();const cells=[...h.querySelectorAll('.market-status-cell')].map(cell=>{const l=cell.querySelector('.status-label'),v=cell.querySelector('.status-value');const cr=cell.getBoundingClientRect();return {label:l.textContent,value:v.textContent,labelWeight:getComputedStyle(l).fontWeight,valueWeight:getComputedStyle(v).fontWeight,y:+cr.y.toFixed(1),icon:Boolean(cell.querySelector('img.ui-icon'))&&cell.querySelector('img.ui-icon').naturalWidth>0,clipped:cell.scrollWidth>cell.clientWidth+1}});return {title:h2.textContent,align:getComputedStyle(h2).textAlign,titleCenterDelta:+((tr.x+tr.width/2)-(hr.x+hr.width/2)).toFixed(1),cells}})()`);
    check('S1 title centred (' + head.title + ')', head.align === 'center' && Math.abs(head.titleCenterDelta) <= 2 && /·/.test(head.title), JSON.stringify({ align: head.align, delta: head.titleCenterDelta }));
    check('S1 three status columns on one row: 可用货位 / 随身铜钱 / 商报 with existing icons', head.cells.length === 3 && head.cells.map(x => x.label.trim()).join('|') === '可用货位|随身铜钱|商报' && head.cells.every(x => x.icon) && Math.max(...head.cells.map(x => x.y)) - Math.min(...head.cells.map(x => x.y)) <= 2, JSON.stringify(head.cells.map(x => [x.label, x.value, x.y])));
    check('S1 label regular / value bold, 钱 unit kept, slots as available/capacity, 商报 state one of 最新|历史|未购买, nothing clipped', head.cells.every(x => Number(x.labelWeight) < 600 && Number(x.valueWeight) >= 600 && !x.clipped) && head.cells[0].value === s.cap - s.used + '/' + s.cap && head.cells[1].value === s.cash.toLocaleString('zh-CN') + '钱' && ['最新', '历史', '未购买'].includes(head.cells[2].value), JSON.stringify(head.cells));
    // ---------------- Section 2
    const hint = () => ev(`(()=>{const h=document.querySelector('${M} .market-time-hint');const cs=getComputedStyle(h);return {text:h.textContent,align:cs.textAlign,color:cs.color,weight:cs.fontWeight,size:parseFloat(cs.fontSize)}})()`);
    let h = await hint(); const isReddish = col => { const m = col.match(/\d+/g).map(Number); return m[0] > 140 && m[1] < 90 && m[2] < 90; };
    check('S2 hint before any trade: 查看市价不推进时间, left-aligned, secondary (not red)', h.text === '查看市价不推进时间' && h.align === 'left' && !isReddish(h.color) && Number(h.weight) < 600, JSON.stringify(h));
    await shot('collapsed'); 
    // ---------------- Section 3 / 4 (collapsed card)
    const card = await ev(`(()=>{const card=document.querySelector('${M} .market-product:not(.provisions-product)');const r=e=>e.getBoundingClientRect();const cr=r(card),ir=r(card.querySelector('img.goods-art')),info=r(card.querySelector('.market-info'));const cs=getComputedStyle(card);const inner=cr.width-parseFloat(cs.paddingLeft)-parseFloat(cs.paddingRight);const tags=[...card.querySelectorAll('.market-tag')].map(t=>{const s=getComputedStyle(t);return {text:t.textContent,weight:s.fontWeight,radius:s.borderRadius,padding:s.padding,border:s.borderWidth,h:+r(t).height.toFixed(1),cls:t.className}});const lines=[...card.querySelectorAll('.market-stat-line')].map(l=>l.innerText.replace(/\\s+/g,' '));return {goodId:card.dataset.goodId,imgRatio:+(ir.width/inner).toFixed(3),infoRatio:+(info.width/inner).toFixed(3),title:card.querySelector('.market-title').innerText.replace(/\\s+/g,' '),tags,lines,buttons:[...card.querySelectorAll('.market-card-actions button')].map(b=>b.textContent.trim()),expanded:card.classList.contains('is-expanded')}})()`);
    check('S3 card: image ≈35 % / info ≈65 % (' + card.imgRatio + ' / ' + card.infoRatio + ')', card.imgRatio >= 0.31 && card.imgRatio <= 0.39 && card.infoRatio >= 0.58 && card.infoRatio <= 0.68, JSON.stringify({ img: card.imgRatio, info: card.infoRatio }));
    check('S3 rows: name + specialty tag · 当前价/持有/货位 · 商报判断 未购买 · collapsed 买入⌄ / 卖出⌄', /特产/.test(card.title) && /^当前价 \d[\d,]*钱 持有 \d+ 货位 \d\/件$/.test(card.lines[0]) && card.lines[1] === '商报判断 未购买' && card.buttons.join('|') === '买入⌄|卖出⌄' && !card.expanded, JSON.stringify({ title: card.title, lines: card.lines, buttons: card.buttons }));
    const fragileCard = await ev(`(()=>{const card=document.querySelector('${M} .market-product[data-good-id="唐代陶瓷"]');if(!card)return null;const r=e=>e.getBoundingClientRect();const tags=[...card.querySelectorAll('.market-tag')].map(t=>{const s=getComputedStyle(t);return {text:t.textContent,weight:s.fontWeight,radius:s.borderRadius,padding:s.padding,border:s.borderWidth,h:+r(t).height.toFixed(1),cls:t.className}});return tags})()`);
    check('S4 tags share one component (radius / padding / border / height), 长安特产 bold, 易碎 regular', fragileCard && fragileCard.length === 2 && fragileCard[0].text === '长安特产' && fragileCard[1].text === '易碎' && Number(fragileCard[0].weight) >= 600 && Number(fragileCard[1].weight) < 600 && fragileCard[0].radius === fragileCard[1].radius && fragileCard[0].padding === fragileCard[1].padding && fragileCard[0].border === fragileCard[1].border && Math.abs(fragileCard[0].h - fragileCard[1].h) <= 1, JSON.stringify(fragileCard));
    // ---------------- Section 5 (expand / switch / single / arrows / stepper / summary)
    const g1 = card.goodId; await cardBtn(g1, 'buy'); await sleep(250); let x = await expandInfo();
    check('S5 买入 expands inside the card: 买入⌃ / 卖出⌄, editable stepper, 确认买入, no separate trade page', x && x.goodId === g1 && x.mode === 'buy' && x.buttons.join('|') === '买入⌃|卖出⌄' && x.inputType === 'text' && x.inputMode === 'numeric' && x.confirmText === '确认买入' && await ev(`!document.querySelector('[data-panel-id="trade-form"]')`), JSON.stringify(x && { b: x.buttons, v: x.value, confirm: x.confirmText }));
    check('S5 buy summary on one line: 本次合计 N钱 · 占用货位 M', /^本次合计 \d[\d,]*钱$/.test(x.left) && /^占用货位 \d+$/.test(x.right) && Math.abs(x.leftRect.y - x.rightRect.y) <= 1, JSON.stringify({ l: x.left, r: x.right }));
    const rightX1 = x.rightRect.x; await typeQty('5'); await sleep(150); x = await expandInfo();
    check('S5 right column start fixed while the amount grows (' + rightX1 + ' → ' + x.rightRect.x + ')', Math.abs(x.rightRect.x - rightX1) <= 0.5 && /^本次合计 \d[\d,]*钱$/.test(x.left), JSON.stringify({ before: rightX1, after: x.rightRect.x, left: x.left }));
    await shot('buy-expanded');
    const g2 = await ev(`(()=>{const cards=[...document.querySelectorAll('${M} .market-product:not(.provisions-product)')];const other=cards.find(k=>k.dataset.goodId!=='${g1}'&&!k.querySelector('button[data-action="buy"]').disabled);return other?other.dataset.goodId:null})()`);
    await cardBtn(g2, 'buy'); await sleep(250); x = await expandInfo();
    check('S5 opening another card switches the single expanded card (' + g2 + ')', x && x.goodId === g2 && x.expanded === 1, JSON.stringify(x && { g: x.goodId, n: x.expanded }));
    await cardBtn(g2, 'buy'); await sleep(250); const collapsed = await ev(`document.querySelectorAll('${M} .market-product:not(.provisions-product).is-expanded').length`);
    check('S5 tapping the active 买入⌃ collapses the card', collapsed === 0, collapsed);
    const bodyTap = await ev(`(()=>{const card=document.querySelector('${M} .market-product[data-good-id="${g1}"]');card.querySelector('.market-info').click();return true})()`); await sleep(250); x = await expandInfo();
    check('S5 card body tap expands the card (default mode 买入 — pending product confirmation)', bodyTap && x && x.goodId === g1 && x.mode === 'buy', JSON.stringify(x && { g: x.goodId, m: x.mode }));
    // buy 2 units to enable selling
    await typeQty('2'); await sleep(120); let before = await st(); await clickBtn(M, '确认买入'); await busyWait(); await sleep(500); s = await st();
    check('S5 确认买入 executes the existing rule (2 件 bought, cash down, result card shown)', s.lots.some(l => l.g === g1 && l.q === 2) && s.cash < before.cash && s.result === 'marketBuy', JSON.stringify({ lots: s.lots, cash: [before.cash, s.cash], result: s.result }));
    await ev(`(()=>{const p=Silk.app.state.progress;const ar=p.presentation.activeResult;if(ar)Silk.ui.dispatch('result.ack',{resultId:ar.id});})()`); await busyWait(); await sleep(300);
    h = await hint(); check('S2 hint after a successful trade: 已发生交易 · 离市后将推进半日 (still 0 tick)', h.text === '已发生交易 · 离市后将推进半日' && !isReddish(h.color) && (await st()).tick === tick0, JSON.stringify({ h: h.text, tick: (await st()).tick }));
    const holding = await ev(`(()=>{const card=document.querySelector('${M} .market-product[data-good-id="${g1}"]');const l=card.querySelector('.market-holding-line');return l?l.innerText.replace(/\\s+/g,' '):null})()`);
    check('S3 holding summary line: 持有成本 / 可售价值 / 盈亏 with 钱 (existing calculation)', holding && /^持有成本 \d[\d,]*钱 可售价值 \d[\d,]*钱 盈亏 [+-]?\d[\d,]*钱$/.test(holding), holding);
    await cardBtn(g1, 'sell'); await sleep(250); x = await expandInfo();
    check('S5 卖出 switches the same card to sell mode: 买入⌄ / 卖出⌃, 本次可得 · 释放货位, 确认出售', x && x.goodId === g1 && x.mode === 'sell' && x.buttons.join('|') === '买入⌄|卖出⌃' && /^本次可得 \d[\d,]*钱$/.test(x.left) && /^释放货位 \d+$/.test(x.right) && x.confirmText === '确认出售', JSON.stringify(x && { b: x.buttons, l: x.left, r: x.right }));
    await shot('sell-expanded');
    await cardBtn(g1, 'buy'); await sleep(250); x = await expandInfo(); check('S5 tapping the other side switches mode directly (sell → buy)', x && x.mode === 'buy' && x.buttons.join('|') === '买入⌃|卖出⌄', JSON.stringify(x && x.buttons));
    // ---------------- Section 6 (reasons: immediate, one at a time, priority, restore)
    const cashReal = (await st()).cash; await setState('p.cash=0'); await sleep(250); x = await expandInfo();
    check('S6 cash gone → 随身现钱不足 shown at once under the confirm, confirm disabled, brick-red small text', x && x.reason === '随身现钱不足' && x.confirmDisabled && isReddish(x.reasonColor) && x.reasonRect.y >= x.confirmRect.y + x.confirmRect.h - 1 && x.reasonFont <= 13, JSON.stringify(x && { reason: x.reason, disabled: x.confirmDisabled, color: x.reasonColor, y: [x.confirmRect.y + x.confirmRect.h, x.reasonRect.y] }));
    await shot('reason-cash');
    await setState('p.inventory.provisions=0;p.inventory.lots=p.inventory.lots.filter(l=>l.goodId!=="__none__");while(Silk.inventory.available(p)>0){p.inventory.lots.push({...Silk.inventory.add(Object.assign({},p,{inventory:{...p.inventory,lots:[]}}),{goodId:"绢帛",quantity:1,acquisitionPrice:1}),id:"fill-"+Silk.inventory.available(p),ownership:"playerOwned"})}'); await sleep(250); x = await expandInfo();
    check('S6 slots full + no cash → only 行囊货位不足 (priority over 铜钱不足)', x && x.reason === '行囊货位不足' && x.confirmDisabled, JSON.stringify(x && { reason: x.reason }));
    await setState(`p.inventory.lots=p.inventory.lots.filter(l=>!String(l.id).startsWith("fill-"));p.cash=${cashReal}`); await sleep(250); x = await expandInfo();
    check('S6 conditions restored → slot/cash reasons gone at once (the shared stepper had clamped the field to 0 while blocked, so only the quantity reason may remain)', x && x.reason !== '行囊货位不足' && x.reason !== '随身现钱不足' && (x.reason === '' ? !x.confirmDisabled : x.reason === '请输入正整数件数'), JSON.stringify(x && { reason: x.reason, disabled: x.confirmDisabled, value: x.value }));
    await typeQty('1'); await sleep(150); x = await expandInfo(); check('S6 quantity 1 again → no reason, confirm enabled', x && x.reason === '' && !x.confirmDisabled, JSON.stringify(x && { reason: x.reason, disabled: x.confirmDisabled }));
    await typeQty(''); await sleep(150); x = await expandInfo(); check('S6 empty quantity → 数量限制 reason (请输入正整数件数), confirm disabled', x && x.reason === '请输入正整数件数' && x.confirmDisabled, JSON.stringify(x && x.reason));
    await typeQty('1'); await sleep(150);
    const locked = await ev(`(()=>{const card=document.querySelector('${M} .market-product.locked-product');return card?card.dataset.goodId:null})()`);
    if (locked) { await cardBtn(locked, 'buy'); await sleep(250); x = await expandInfo(); check('S6 locked good → 未解锁 reason (尚未建立该货源关系) has top priority', x && x.goodId === locked && x.reason === '尚未建立该货源关系' && x.confirmDisabled, JSON.stringify(x && { g: x.goodId, reason: x.reason })); await cardBtn(locked, 'buy'); await sleep(200); }
    else check('S6 locked good present for the 未解锁 case', false, 'no locked product on this market');
    // ---------------- Section 7 (provisions special card)
    const prov = await ev(`(()=>{const card=document.querySelector('${M} .provisions-product'),normal=document.querySelector('${M} .market-product:not(.provisions-product)');const lines=[...card.querySelectorAll('.market-stat-line, .provisions-head, .form-hint')].map(l=>l.innerText.replace(/\\s+/g,' '));return {bg:getComputedStyle(card).backgroundColor,normalBg:getComputedStyle(normal).backgroundColor,lines,button:card.querySelector('.market-card-actions button').textContent.trim(),btnH:+card.querySelector('.market-card-actions button').getBoundingClientRect().height.toFixed(1)}})()`);
    check('S7 provisions card keeps its special background and the approved lines (现有补给 · 单价 1钱 / 商队日份 · 有补给时共用 1货位 · 下一程 … 基础路程N日 · 途中事件可能延误), 购买粮草⌄ card-level', prov.bg !== prov.normalBg && /粮草补给 现有补给 \d+日份/.test(prov.lines[0]) && /单价 1钱 \/ 商队日份 有补给时共用 1货位/.test(prov.lines[1]) && /下一程 长安 → 敦煌 · 基础路程3日/.test(prov.lines[2]) && prov.lines[3] === '途中事件可能延误' && prov.button === '购买粮草⌄', JSON.stringify(prov));
    await clickBtn(M + ' .provisions-product', '购买粮草'); await sleep(250);
    const pe = await ev(`(()=>{const te=document.querySelector('${M} .provisions-product .trade-expand');if(!te)return null;const i=te.querySelector('.stepper-input');i.focus();i.value='3';i.dispatchEvent(new Event('input',{bubbles:true}));return {label:te.querySelector('.field-label').textContent,left:te.querySelector('.trade-summary-left').textContent,right:te.querySelector('.trade-summary-right').textContent,confirm:te.querySelector(':scope>.ui-button').textContent.trim(),button:document.querySelector('${M} .provisions-product .market-card-actions button').textContent.trim()}})()`); await sleep(120);
    const pe2 = await ev(`(()=>{const te=document.querySelector('${M} .provisions-product .trade-expand');return {left:te.querySelector('.trade-summary-left').textContent,right:te.querySelector('.trade-summary-right').textContent}})()`);
    check('S7 expanded: 购买日份 stepper, 本次合计 3钱 · 购买后共有 3日份, 确认购买, 购买粮草⌃', pe && pe.label === '购买日份' && pe2.left === '本次合计 3钱' && pe2.right === '购买后共有 3日份' && pe.confirm === '确认购买' && pe.button === '购买粮草⌃', JSON.stringify({ pe, pe2 }));
    await shot('provisions-expanded');
    await clickBtn(M + ' .provisions-product', '确认购买'); await busyWait(); await sleep(400); s = await st(); check('S7 确认购买 buys 3 日份 for 3钱 (existing rule)', s.provisions === 3, JSON.stringify({ prov: s.provisions }));
    await ev(`(()=>{const p=Silk.app.state.progress;const ar=p.presentation.activeResult;if(ar)Silk.ui.dispatch('result.ack',{resultId:ar.id});})()`); await busyWait(); await sleep(300);
    // ---------------- Section 8 / 9 (button tiers, three bottom entries)
    const sizes = await ev(`(()=>{const r=e=>e.getBoundingClientRect();const leave=[...document.querySelectorAll('${M}>.panel-footer button')].find(b=>b.textContent.trim()==='离开市场');const buy=document.querySelector('${M} .market-card-actions button[data-action="buy"]');const tools=[...document.querySelectorAll('${M} .market-tools button')];const body=document.querySelector('${M}>.panel-body');const toolsBox=document.querySelector('${M} .market-tools');toolsBox.scrollIntoView({block:'end'});const cs=getComputedStyle(body);const inner=body.clientWidth-parseFloat(cs.paddingLeft)-parseFloat(cs.paddingRight);const gap=parseFloat(getComputedStyle(toolsBox).columnGap||getComputedStyle(toolsBox).gap)||0;return {leaveH:+r(leave).height.toFixed(1),buyH:+r(buy).height.toFixed(1),provH:+r(document.querySelector('${M} .provisions-product .market-card-actions button')).height.toFixed(1),tools:tools.map(b=>({t:b.textContent.trim(),w:+r(b).width.toFixed(1),h:+r(b).height.toFixed(1),y:+r(b).y.toFixed(1),disabled:b.disabled})),inner:+inner.toFixed(1),gap,toolsW:+r(toolsBox).width.toFixed(1)}})()`);
    const ratio = sizes.buyH / sizes.leaveH;
    check('S8 card-level buttons ≈75 % of the page-level 离开市场 (' + sizes.buyH + ' / ' + sizes.leaveH + ' = ' + ratio.toFixed(2) + '), provisions entry same tier', ratio >= 0.68 && ratio <= 0.82 && Math.abs(sizes.provH - sizes.buyH) <= 1, JSON.stringify({ leave: sizes.leaveH, buy: sizes.buyH, prov: sizes.provH }));
    check('S9 一键出售 / 查看委托 / 查看商情 in one row, equal thirds, same tier as 买入', sizes.tools.map(t => t.t).join('|') === '一键出售|查看委托|查看商情' && Math.max(...sizes.tools.map(t => t.y)) - Math.min(...sizes.tools.map(t => t.y)) <= 1 && Math.max(...sizes.tools.map(t => t.w)) - Math.min(...sizes.tools.map(t => t.w)) <= 1 && sizes.tools.every(t => Math.abs(t.h - sizes.buyH) <= 1) && Math.abs(sizes.tools[0].w * 3 + sizes.gap * 2 - sizes.toolsW) <= 2, JSON.stringify(sizes));
    await shot('tools-row');
    // ---------------- Section 10 (exit confirm / time)
    s = await st(); check('S10 pre-check: trades happened, tick unchanged so far', s.visit && s.visit.had === true && s.tick === tick0, JSON.stringify({ had: s.visit && s.visit.had, tick: s.tick }));
    await clickBtn(M + '>.panel-footer', '离开市场'); await sleep(400); s = await st();
    const confirmPanel = await ev(`(()=>{const p=document.querySelector('[data-panel-id="market-exit-confirm"]');if(!p||p.offsetParent===null)return null;return {title:p.querySelector('h2').textContent,text:p.querySelector('.panel-body').innerText.replace(/\\s+/g,' '),footer:[...p.querySelectorAll('.panel-footer button')].map(b=>b.textContent.trim())}})()`);
    check('S10 with trades: 离开市场 → MARKET_EXIT_CONFIRM (summary + 返回市场 | 确认离市), still 0 tick, visit open', confirmPanel && confirmPanel.footer.join('|') === '返回市场|确认离市' && /买入 .* × 2/.test(confirmPanel.text) && /补给 \+3日份/.test(confirmPanel.text) && s.tick === tick0 && s.visit && !s.visit.settled, JSON.stringify({ confirmPanel, tick: s.tick }));
    await shot('exit-confirm');
    await clickBtn('[data-panel-id="market-exit-confirm"]', '返回市场'); await sleep(300); s = await st();
    check('S10 返回市场: same visit, trades kept, market usable again, 0 tick', s.visit && s.visit.id === before.visit.id && !s.visit.settled && s.lots.some(l => l.g === g1) && s.tick === tick0 && await ev(`(()=>{const vis=e=>e&&e.offsetParent!==null;return vis(document.querySelector('${M} .market-product'))&&!vis(document.querySelector('[data-panel-id="market-exit-confirm"]'))})()`), JSON.stringify({ visit: s.visit, tick: s.tick }));
    await cardBtn(g1, 'sell'); await sleep(250); await typeQty('1'); await sleep(120); await clickBtn(M, '确认出售'); await busyWait(); await sleep(400); await ev(`(()=>{const p=Silk.app.state.progress;const ar=p.presentation.activeResult;if(ar)Silk.ui.dispatch('result.ack',{resultId:ar.id});})()`); await busyWait(); await sleep(300);
    await clickBtn(M + '>.panel-footer', '离开市场'); await sleep(400); const confirm2 = await ev(`(()=>{const p=document.querySelector('[data-panel-id="market-exit-confirm"]');return p?p.querySelector('.panel-body').innerText.replace(/\\s+/g,' '):null})()`);
    check('S10 leaving again regenerates the latest summary (now includes 卖出 × 1), still 0 tick', confirm2 && /卖出 .* × 1/.test(confirm2) && (await st()).tick === tick0, JSON.stringify({ confirm2, tick: (await st()).tick }));
    await clickBtn('[data-panel-id="market-exit-confirm"]', '确认离市'); await busyWait(); await sleep(600); s = await st();
    check('S10 确认离市: visit closed + exactly +1 tick, no summary result page, market panel gone', s.visit && s.visit.settled && s.tick === tick0 + 1 && s.result !== 'marketSummary' && await ev(`(()=>{const vis=e=>e&&e.offsetParent!==null;return !vis(document.querySelector('${M}'))&&!vis(document.querySelector('[data-panel-id="market-exit-confirm"]'))})()`), JSON.stringify({ visit: s.visit, tick: s.tick, result: s.result }));
    const again = await ev(`Silk.ui.dispatch('market.leave',{visitId:${JSON.stringify(s.visit.id)}}).then(r=>({r:r===null?null:r.kind}))`); await sleep(300); s = await st();
    check('S10 repeated confirm for the same visit cannot advance again (tick still +1)', s.tick === tick0 + 1, JSON.stringify({ again, tick: s.tick }));
    await shot('after-confirm');
    // ---------------- Section 10-A (no-trade visit) — fresh visit next morning is not needed: reopen now? phase is 午 → market open
    await ev(`(()=>{const p=Silk.app.state.progress;const ev=p.eventSession;if(ev&&ev.status==='AWAITING_CHOICE'){const s=[...document.querySelectorAll('section.paper-panel')].find(x=>!x.hidden&&x.offsetParent!==null&&/商路见闻/.test(x.innerText));const btns=s?[...s.querySelectorAll('button')].filter(b=>!b.disabled&&b.offsetParent!==null&&b.closest('footer')===null):[];if(btns.length)btns[btns.length-1].click();}})()`); await busyWait(); await sleep(400); await ev(`(()=>{const p=Silk.app.state.progress;const ar=p.presentation.activeResult;if(ar)Silk.ui.dispatch('result.ack',{resultId:ar.id});})()`); await busyWait(); await sleep(300);
    await ev(`(()=>{for(const s of document.querySelectorAll('section.paper-panel .close-button'))if(s.offsetParent!==null)s.click();})()`); await sleep(300);
    const opened = await ev(`(()=>{const h=document.querySelector('.city-hotspot[data-hotspot="market"]');if(!h)return false;h.click();return true})()`); await sleep(1000); await busyWait(); s = await st(); const tick1 = s.tick;
    if (opened && s.visit && !s.visit.settled) {
      await cardBtn(g1, 'buy'); await sleep(200); await typeQty('1'); await sleep(100); // expand + edit only, no trade
      await clickBtn(M + '>.panel-footer', '离开市场'); await busyWait(); await sleep(500); s = await st();
      check('S10-A no successful trade (expand/edit only): 离开市场 returns to the city directly, no confirm page, no summary, +0 tick', s.visit && s.visit.settled && s.tick === tick1 && s.result === null && await ev(`(()=>{const vis=e=>e&&e.offsetParent!==null;return !vis(document.querySelector('${M}'))&&!vis(document.querySelector('[data-panel-id="market-exit-confirm"]'))})()`), JSON.stringify({ visit: s.visit, tick: [tick1, s.tick], result: s.result }));
    } else check('S10-A second visit could be opened for the no-trade case', false, JSON.stringify({ opened, visit: s.visit, phase: s.tick % 3 }));
    const errs = c.console.filter(m => m.type === 'error' || m.type === 'exception').map(m => m.text.slice(0, 160)); check('no console errors', errs.length === 0, JSON.stringify(errs.slice(0, 3)));
  } catch (e) { check('script error', false, String(e && e.stack || e).slice(0, 400)); }
  await c.close(); srv.stop();
  const passed = checks.filter(x => x.ok).length;
  fs.writeFileSync(path.join(outDir, 'market-run.json'), JSON.stringify({ label, passed, total: checks.length, checks }, null, 2));
  console.log(`market browser run [${label}]: ${passed}/${checks.length} → ` + outDir);
  process.exit(passed === checks.length ? 0 : 1);
})();
