(function(S){
 'use strict';
 const city={changan:'长安',dunhuang:'敦煌',khotan:'于阗'},scale={lipu:'立铺',chengsi:'成肆',xinghao:'兴号'},tier={small:'小院',medium:'中院',large:'大院'};
 const names={manager_attract:'揽客掌柜',manager_bulk:'大宗掌柜',manager_repeat:'回头客掌柜',manager_rare:'稀货掌柜',assistant_attract:'招呼伙计',assistant_stock:'理货伙计',assistant_repeat:'熟客伙计'};
 const activeStatuses=new Set(['accepted','pending_pickup','in_transit','ready_to_turn_in']);
 function inReturnGrace(c,id){try{return S.trip.returnView(c.p).pendingGraceIds.includes(id);}catch(_){return false;}}
 const merchant=c=>S.merchant.snapshot(c.p),commissions=c=>S.commissions.snapshot(c.p,S.core.context('ui-read'));
 function section(c,b,title){const x=c.el('section','business-section');x.append(c.el('h3','',title));b.append(x);return x;}
 function inspect(c,b,label,reason){const x=c.button(label,()=>c.openSecondary('business-info',{text:reason}),{className:'ui-button is-unavailable'});x.setAttribute('aria-disabled','true');b.append(x);}
 function amount(c,options){c.openSecondary('business-amount',options);}
 function confirm(c,title,text,type,payload){c.showModal({title,body:text,actions:[{label:'返回',run:c.dismissModal},{label:'确认',run:async()=>{const r=await c.dispatch(type,payload);if(r!==null)c.dismissModal();}}]});}
 function mutate(c,b,label,type,payload,cost){let detail=cost!==undefined?'本次花费 '+c.formatMoney(cost)+'。':'';
   if(type==='merchant.hire')detail+='延请费用立即支付，此后每30日需付薪资'+c.formatMoney(S.merchant.staff[payload.staffId].wage)+'。';
   if(type==='merchant.dismiss')detail+='辞退后停止后续雇佣；已经产生的欠薪仍需清偿。';
   if(type==='merchant.buyProperty')detail+='院落购入后不可转卖。可以选择自住、闲置或出租。';
   if(type==='merchant.propertyUse'&&payload.use==='rented')detail+='租期30日，到期默认自动续租。本期租约结束前不能改变用途。';
   if(type==='merchant.setRenewal')detail+=payload.autoRenew?'本期租约结束后自动续租30日。':'本期租约继续，到期后不再续租，院落转为闲置。';
   b.append(c.button(label,()=>detail?confirm(c,label,detail,type,payload):c.dispatch(type,payload)));}
 S.ui.registerPanel('business-info',{title:'办理说明',render(c,b,d){c.paragraph(b,d.text);}});
 S.ui.registerPanel('business-amount',{title:'输入办理数额',render(c,b,d){
   if(d.description)c.paragraph(b,d.description);const form=c.el('form','business-amount-form');form.id='business-amount-form';form.noValidate=true;
   const field=c.el('div','form-field');field.append(c.el('span','field-label',d.label||'输入金额'));const stepper=c.numericStepper({name:'business-amount',value:'',min:d.allowZero?0:1,max:()=>d.max,decimal:Boolean(d.decimal),label:d.label||'输入金额'}),input=stepper.input;field.append(stepper.element);form.append(field);
   if(d.max!==undefined)c.paragraph(form,'当前上限：'+d.max+(d.unit||'钱'),'form-hint');
   function valid(){const text=input.value;return (d.decimal?/^\d+(\.\d{1,4})?$/:/^\d+$/).test(text)&&Number.isFinite(Number(text))&&(d.allowZero?Number(text)>=0:Number(text)>0)&&(d.decimal||Number.isSafeInteger(Number(text)))&&(d.max===undefined||Number(text)<=d.max);}
   input.addEventListener('input',()=>{const v=input.value.replace(d.decimal?/[^0-9.]/g:/[^0-9]/g,'');const clamped=d.max!==undefined&&Number(v)>d.max?String(d.max):v;if(clamped!==input.value)input.value=clamped;const submit=document.getElementById('business-amount-submit');if(submit)submit.disabled=!valid()||S.ui.getState().busy;stepper.refresh();});
   form.addEventListener('submit',e=>{e.preventDefault();if(!valid())return;const n=Number(input.value),payload={...d.payload,[d.field||'amount']:d.percent?n/100:n};if(['merchant.fund','merchant.upgrade'].includes(d.type))confirm(c,'确认投入？','投入 '+c.formatMoney(n)+'，投入后不可撤回。筹齐本项所需金额后，按筹备或扩建规则继续。',d.type,payload);else c.dispatch(d.type,payload);});b.append(form);
 },footer(c,f){const submit=c.button('确认办理',()=>{},{disabled:true});submit.id='business-amount-submit';submit.type='submit';submit.setAttribute('form','business-amount-form');f.append(submit);}});
 S.ui.registerPanel('merchant_business',{title:'商号',render(c,b){
   const m=merchant(c);c.row('当前规模',scale[m.scale]||({locked:'尚未筹办',eligible:'可以筹办',funding:'筹资中',preparing:'筹备中'}[m.status]),b);c.row('商号账款',c.formatMoney(m.businessBalance),b);
   if(m.remote)c.paragraph(b,'远行期间可以查账，回到长安后办理经营事务。','form-hint');
   if(m.status!=='open'){
     const labels={reputation:'商誉达到筹办要求',experience:'已有两次完整商旅经历',onTime:'已有按期返程记录',credit:'没有逾期借款',local:'当前在长安',unstarted:'当前未启程'};
     for(const [key,ok]of Object.entries(m.eligibility))c.row(labels[key],ok?'已满足':'尚未满足',b);
     for(const [part,title]of [['premises','铺面'],['fixtures','铺具'],['workingCapital','周转金']]){c.row(title,c.formatMoney(m.funding[part])+' / '+c.formatMoney(m.fundingTargets[part]),b);if(m.canFund&&['eligible','funding','locked'].includes(m.status)&&m.funding[part]<m.fundingTargets[part])b.append(c.button('投入'+title,()=>amount(c,{type:'merchant.fund',payload:{part},max:Math.min(m.fundingTargets[part]-m.funding[part],c.p.cash+m.businessBalance),description:'投入会从商号账款优先支取，不足部分从随身铜钱补足。'})));}
     if(m.prepareReadyTick!==null)c.row('预计备妥',c.date(m.prepareReadyTick),b);return;
   }
   c.row('货柜',m.cabinets.length+' / '+m.cabinetCapacity,b);if(m.upgrade)c.row('扩建进度',m.upgrade.readyTick!==null?'预计 '+c.date(m.upgrade.readyTick):c.formatMoney(m.upgrade.funded)+'已投入',b);
   for(const [id,label]of [['merchant-cabinets','货柜经营'],['merchant-staff','雇员'],['merchant-funds','调取账款'],['merchant-properties','院落'],['merchant-suppliers','供应往来'],['merchant-expansion','扩建与驼队'],['merchant-ledger','经营记录']])b.append(c.button(label,()=>c.openSecondary(id),{className:'menu-entry'}));
   if(!m.remote){if(S.time.phase(c.p)!==2)mutate(c,b,'坐号经营 · 耗时1个时段','merchant.sit',{});else inspect(c,b,'坐号经营','请在长安晨间或午间坐号经营。');}
 },footer(c,f){const secondary=S.ui.getState().secondary==='merchant_business';f.append(c.button(secondary?'返回返程事务':'离开商号',secondary?c.closeSecondary:c.closePanel));}});
 S.ui.registerPanel('merchant-cabinets',{title:'货柜经营',render(c,b){const m=merchant(c);for(const cabinet of m.cabinets){const card=section(c,b,cabinet.goodId||'空货柜');for(const lot of cabinet.lots)c.row(lot.goodId+(lot.condition==='damaged'?' · 受损':''),lot.quantity+'件',card);c.row('出售底价',cabinet.saleRule?c.formatMoney(cabinet.saleRule.targetPrice):'尚未设置',card);card.append(c.button(m.remote?'查看货柜':'管理货柜',()=>c.openSecondary('merchant-cabinet',{cabinetId:cabinet.cabinetId})));}if(!m.remote&&m.nextCabinetCost!==null)mutate(c,b,'添置货柜','merchant.buyCabinet',{},m.nextCabinetCost);}});
 S.ui.registerPanel('merchant-cabinet',{title:'货柜',render(c,b,d){const m=merchant(c),cab=m.cabinets.find(x=>x.cabinetId===d.cabinetId);if(!cab){c.paragraph(b,'货柜记录已更新。');return;}c.row('经营商品',cab.goodId||'尚未指定',b);if(cab.saleRule)c.row('已锁定出售底价',c.formatMoney(cab.saleRule.targetPrice),b);
   for(const lot of cab.lots){const line=section(c,b,lot.goodId+(lot.condition==='damaged'?' · 受损':''));c.row('数量',lot.quantity+'件',line);c.row('取得单价',c.formatMoney(lot.acquisitionPrice),line);if(!m.remote)line.append(c.button('取回行囊',()=>amount(c,{type:'merchant.unstock',payload:{cabinetId:cab.cabinetId,lotId:lot.id},field:'quantity',max:lot.quantity,label:'输入数量',unit:'件'})));}
   if(m.remote)return;
   const own=c.p.inventory.lots.filter(l=>l.ownership==='playerOwned'&&!l.nonMarketable&&l.condition!=='destroyed'&&(!cab.goodId||cab.goodId===l.goodId));
   if(own.length){const stock=section(c,b,'从行囊补货');for(const lot of own)stock.append(c.button(lot.goodId+' · '+lot.quantity+'件',()=>amount(c,{type:'merchant.stock',payload:{cabinetId:cab.cabinetId,lotId:lot.id},field:'quantity',max:lot.quantity,label:'输入数量',unit:'件'})));}else c.paragraph(b,'当前没有可放入该货柜的自有货物。','form-hint');
   if(cab.goodId){const rules=section(c,b,'出售条件');rules.append(c.button('固定底价',()=>amount(c,{type:'merchant.saleRule',payload:{cabinetId:cab.cabinetId,mode:'fixedPrice'},field:'value',label:'输入每件底价'})));for(const [mode,label]of [['marketMarkup','较设置时市场价加成'],['profitMargin','较设置时平均成本加成']])rules.append(c.button(label,()=>amount(c,{type:'merchant.saleRule',payload:{cabinetId:cab.cabinetId,mode},field:'value',label:'输入百分比',unit:'%',decimal:true,percent:true,allowZero:true,description:'输入10表示10%。办理时由商号锁定底价。'})));if(!cab.lots.length)mutate(c,b,'清空货柜设置','merchant.clearCabinet',{cabinetId:cab.cabinetId});}
 }});
 S.ui.registerPanel('merchant-staff',{title:'雇员',render(c,b){const m=merchant(c);for(const candidate of m.staffCandidates){const hired=m.staff.some(x=>x.staffId===candidate.id),card=section(c,b,names[candidate.id]||'雇员');c.row('延请费用',c.formatMoney(candidate.fee),card);c.row('每30日薪资',c.formatMoney(candidate.wage),card);c.row('状态',hired?'已受雇':'未受雇',card);if(!m.remote){if(hired)mutate(c,card,'辞退','merchant.dismiss',{staffId:candidate.id});else mutate(c,card,'延请','merchant.hire',{staffId:candidate.id},candidate.fee);}}if(m.wageArrears.length){const card=section(c,b,'待付薪资');for(const w of m.wageArrears)c.row(names[w.staffId]||'雇员',c.formatMoney(w.amount),card);c.paragraph(card,'商号账款足够后，会在统一日结中清偿。','form-hint');}}});
 S.ui.registerPanel('merchant-funds',{title:'商号账款',render(c,b){const m=merchant(c);c.row('商号账款',c.formatMoney(m.businessBalance),b);c.row('随身铜钱',c.formatMoney(c.p.cash),b);if(m.remote)return;for(const [direction,label,max]of [['toBusiness','拨入商号',c.p.cash],['toCash','取为随身铜钱',m.businessBalance]])b.append(c.button(label,()=>amount(c,{type:'merchant.transfer',payload:{direction},max})));}});
 S.ui.registerPanel('merchant-expansion',{title:'扩建与驼队',render(c,b){const m=merchant(c);c.row('当前规模',scale[m.scale],b);if(m.nextScale){c.row('下一规模',scale[m.nextScale.stage],b);c.row('扩建所需',c.formatMoney(m.nextScale.cost),b);c.row('筹齐后工期',m.nextScale.ticks+'个时段',b);if(!m.remote&&m.upgrade?.readyTick==null)b.append(c.button('投入扩建',()=>amount(c,{type:'merchant.upgrade',payload:{},max:Math.min(m.nextScale.cost-(m.upgrade?.funded||0),m.businessBalance+c.p.cash)})));}c.row('骆驼',c.p.inventory.camelCount+'匹',b);if(!m.remote&&m.nextCamelCost!==null)mutate(c,b,'添置骆驼','merchant.buyCamel',{},m.nextCamelCost);}});
 S.ui.registerPanel('merchant-suppliers',{title:'供应往来',render(c,b){const m=merchant(c);for(const [good,cfg]of Object.entries(S.merchant.suppliers)){const card=section(c,b,good+' · '+city[cfg.city]),relation=m.suppliers[good];c.row('往来',relation?.stage==='deepened'?'已深化':relation?'已建立':'未建立',card);if(m.remote)continue;if(!relation)mutate(c,card,'建立往来','merchant.supplier',{goodId:good,action:'establish'},cfg.cost);else if(relation.stage==='established'&&cfg.deepCost)mutate(c,card,'深化往来','merchant.supplier',{goodId:good,action:'deepen'},cfg.deepCost);}}});
 S.ui.registerPanel('merchant-properties',{title:'院落',render(c,b){const m=merchant(c);for(const prop of m.properties){const card=section(c,b,tier[prop.tier]),cfg=S.merchant.propertyTypes[prop.tier];c.row('用途',{home:'自住',vacant:'闲置',rented:'出租'}[prop.use],card);c.row('修缮',prop.renovated?'已修缮':'尚未修缮',card);c.row('每30日租金',c.formatMoney(prop.renovated?cfg.renovatedRent:cfg.rent),card);if(m.remote)continue;if(prop.use==='rented')mutate(c,card,prop.autoRenew?'停止下期续租':'恢复自动续租','merchant.setRenewal',{propertyId:prop.propertyId,autoRenew:!prop.autoRenew});else for(const [use,label]of [['home','设为自住'],['vacant','留作闲置'],['rented','租出院落']])if(use!==prop.use)mutate(c,card,label,'merchant.propertyUse',{propertyId:prop.propertyId,use});if(!prop.renovated)mutate(c,card,'修缮院落','merchant.renovate',{propertyId:prop.propertyId},cfg.renovate);}if(!m.remote&&m.properties.length<3){const card=section(c,b,'置办院落');for(const [key,cfg]of Object.entries(S.merchant.propertyTypes))mutate(c,card,'置办'+tier[key],'merchant.buyProperty',{tier:key},cfg.cost);}}});
 S.ui.registerPanel('merchant-ledger',{title:'经营记录',render(c,b){const m=merchant(c);if(!m.ledger.length)c.paragraph(b,'暂无经营记录。');for(const item of [...m.ledger].reverse()){const card=section(c,b,c.date(item.tick));if(item.text)c.paragraph(card,item.text);else{const labels={funding:'筹办投入',opened:'商号开张',expanded:'扩建完成',payroll:'薪资结算',rent:'租金到账',arrearsPaid:'清偿欠薪'};c.paragraph(card,labels[item.type]||'经营事务');for(const [key,label]of [['amount','金额'],['paid','实付'],['arrears','欠薪'],['rent','租金'],['workingCapital','周转金']])if(Number.isSafeInteger(item[key]))c.row(label,c.formatMoney(item[key]),card);}}}});
 const merchantResults={merchantFunding:'筹办投入已记账',merchantUpgrade:'扩建投入已记账',buyCabinet:'货柜已添置',stockCabinet:'货物已放入货柜',unstockCabinet:'货物已取回行囊',clearCabinet:'货柜设置已清空',saleRule:'出售条件已锁定',hire:'雇员已延请',dismiss:'雇员已辞退',sitShop:'坐号经营结束',businessTransfer:'账款已调取',supplier:'供应往来已更新',buyCamel:'骆驼已添置',buyProperty:'院落已置办',propertyUse:'院落用途已更新',renewal:'续租设置已更新',renovate:'院落已修缮'};
 for(const [kind,title]of Object.entries(merchantResults))S.ui.registerResult(kind,(c,b,r)=>{c.paragraph(b,title);for(const [key,label]of [['amount','办理金额'],['cost','本次费用'],['price','本次费用'],['fee','延请费用'],['businessSpent','商号账款支出'],['cashSpent','随身铜钱支出']])if(Number.isSafeInteger(r[key]))c.row(label,c.formatMoney(r[key]),b);if(r.saleRule)c.row('出售底价',c.formatMoney(r.saleRule.targetPrice),b);if(r.quantity)c.row('货物数量',r.quantity+'件',b);if(r.before&&r.after){c.row('随身铜钱',c.formatMoney(r.after.cash),b);c.row('商号账款',c.formatMoney(r.after.businessBalance),b);c.row('时间',c.date(r.after.tick),b);}if(r.askSetHome)c.paragraph(b,'这是你的第一处院落。可在「院落」中将它设为自住。');});
 const ambience=new Map();
 function firstPropertyResult(c,b,r){c.paragraph(b,'院落已置办。');c.row('院落',tier[r.property.tier],b);c.row('本次费用',c.formatMoney(r.cost),b);c.paragraph(b,(r.askSetHome?'这是你的第一处院落，是否设为自住？':'')+'院落不可转卖，之后仍可在院落管理中安排用途。');}
 firstPropertyResult.footer=(c,f,r)=>{async function finish(home){const saved=await c.dispatch('result.ack',{resultId:r.id});if(saved===null)return;if(home)await c.dispatch('merchant.propertyUse',{propertyId:r.property.propertyId,use:'home'});else c.openPanel('merchant_business');}if(r.askSetHome)f.append(c.button('设为自住',()=>finish(true)),c.button('暂不设置',()=>finish(false)));else f.append(c.button('继续',()=>finish(false)));};
 S.ui.registerResult('buyProperty',firstPropertyResult);
 function innCost(c,b,label,key,payload={},available=true,reason='当前不能办理。'){const v=S.inn.snapshot(c.p),cost=v.actionCosts[key],ticks=payload.ticks||cost.ticks,cash=cost.cash*(key==='wait'?ticks:1),text=label+' · '+cash+'钱 / '+ticks+'个时段';if(available)b.append(c.button(text,()=>c.dispatch('inn.'+key,payload)));else inspect(c,b,text,reason);}
 S.ui.registerPanel('inn',{title:'客舍',noClose:true,render(c,b){const v=S.inn.snapshot(c.p);const key=v.city+'/'+c.entryId;if(!ambience.has(key)){const lines=v.ambientLines;ambience.set(key,lines[Math.floor(Math.random()*lines.length)]||'');}const line=ambience.get(key);c.paragraph(b,typeof line==='string'?line:line.text||'','inn-ambient');
   if(v.daytime){innCost(c,b,'听商旅闲谈','talk',{},!v.talkUsed&&v.cash>=v.actionCosts.talk.cash,v.talkUsed?'今日已听过闲谈。':'随身现钱不足。');innCost(c,b,'整理行装','prepare',{},v.canPrepare,v.prepared?'行装已整备。':'需在商旅途中下一路段出发前整理行装。');
     const wait=section(c,b,'歇脚候时');if(v.waitAlternatives.length)c.paragraph(wait,'也可以先去'+v.waitAlternatives.join('、')+'。','form-hint');for(let n=1;n<=v.maxWaitTicks;n++)innCost(c,wait,'候时'+n+'个时段','wait',{ticks:n},v.cash>=v.actionCosts.wait.cash*n,'随身现钱不足。');
     for(const task of commissions(c).active.filter(x=>activeStatuses.has(x.status)&&x.deliveryCity===v.city&&x.handoffPhase!==null&&!x.urgent)){let target;try{target=S.commissions.waitTarget(c.p,task.commissionId);}catch(_){continue;}const ticks=Math.min(target-c.p.world.tick,v.maxWaitTicks);if(ticks>0)wait.append(c.button('等候「'+task.title+'」交付时辰 · '+ticks+'钱 / '+ticks+'个时段',()=>c.dispatch('inn.waitCommission',{commissionId:task.commissionId})));}
   }else{innCost(c,b,'留宿客舍','stay',{},v.canStay,'随身现钱不足。');if(v.canCamp)innCost(c,b,'风餐露宿','camp');if(v.canRestOutside)innCost(c,b,'寻处暂歇','restOutside');if(v.canHome)innCost(c,b,'回院歇息','home');}
 },footer(c,f){f.append(c.button('离开客舍',c.closePanel));}});
 function innResult(c,b,r){const overnight=['stay','camp','restOutside','home'].includes(r.action);if(overnight){b.append(c.el('h3','','新的一天 · '+(['晨','午','暮'][r.phase]||'晨')));c.row('昨夜宿费',c.formatMoney(r.lodgingCost),b);}else{if(r.actionCost>0)c.row('花费',c.formatMoney(r.actionCost),b);c.row('耗时',r.elapsed+'个时段',b);}c.row('当前',r.dateLabel||c.date(r.after.tick),b);c.paragraph(b,r.text||'');if(r.explanation)c.paragraph(b,r.explanation);if(r.action==='talk'||r.story)c.paragraph(b,'已记入「消息 · 市面所见」。','form-hint');if(r.effects)for(const e of r.effects){if(e.goodId)c.row(e.goodId,e.quantity+'件 · '+(e.condition==='damaged'?'受损':e.type==='cargo_remove'?'失去':'状态已更新'),b);else if(e.type==='cash'&&e.delta)c.row('昨夜钱财',(e.delta>0?'+':'−')+c.formatMoney(Math.abs(e.delta)),b);else if(e.type==='reputation'&&e.delta)c.row('商誉',(e.delta>0?'+':'')+e.delta,b);else if(e.type==='provisions'&&e.delta)c.row('补给',(e.delta>0?'+':'')+e.delta+'日份',b);}if(overnight&&r.after)c.row('随身铜钱',c.formatMoney(r.after.cash),b);}
 innResult.footer=(c,f,r)=>{const morning=['stay','camp','restOutside','home'].includes(r.action),returnMorning=morning&&c.p.trip?.phase==='return_tasks';async function ack(destination){const saved=await c.dispatch('result.ack',{resultId:r.id});if(saved===null)return;if(destination)c.openPanel(destination);else c.closePanel();}
   if(returnMorning)f.append(c.button('处理返程事务',()=>ack('trip')));else if(morning&&r.action!=='stay')f.append(c.button('开始新的一日',()=>ack()));else f.append(c.button('留在客舍',()=>ack('inn')),c.button('离开客舍',()=>ack()));};
 S.ui.registerResult('innFeedback',innResult);
 const status={available:'可以承接',unavailable:'本期已无法承接',accepted:'进行中',pending_pickup:'待取货',in_transit:'运送中',ready_to_turn_in:'待交付',completed:'已完成',failed:'未完成'};
 // RC3 BUG-13: attribute labels come from the instance itself (加急/易损/贵重/稀有/远途/晨交/午交, or 普通).
 function labelsOf(task){return task.attributeLabels||(S.commissions.attributeLabels?S.commissions.attributeLabels(task):[]);}
 function commissionCard(c,b,task,brief){const card=section(c,b,task.title);c.row('类型',{delivery:'捎货',procurement:'采买',wanted:'求货'}[task.type]+' · '+{basic:'常契',good:'良契',entrusted:'重托'}[task.scale],card);c.row('属性',labelsOf(task).join('、'),card);c.row('状态',task.draftSelected?'已选定（启程时承接）':status[task.status]||'记录已更新',card);c.row('货物',task.goodId+' × '+task.quantity,card);c.row('交付城市',city[task.deliveryCity],card);if(!brief){c.paragraph(card,task.text);if(task.pickupCity)c.row('取货城市',city[task.pickupCity],card);if(task.procurementCity)c.row('采买城市',city[task.procurementCity],card);c.row('所需货位',task.requiredSlots,card);c.row('约定报酬',c.formatMoney(task.rewardCash),card);c.row('约定商誉',task.reputationReward,card);if(task.handoffPhase!==null&&task.handoffPhase!==undefined)c.row('交付时段',['晨','午'][task.handoffPhase],card);if(task.urgent)c.paragraph(card,'加急：抵达正确交付站点后开窗——晨到可在当日晨、午、暮交付；午到可在当日午、暮交付；暮到可在当刻或紧接着的次日晨交付（只顺延这一次）。返程宽限优先。','form-hint');if(task.urgent&&task.urgentWindow)c.row('加急窗口',(task.urgentOpen?'开放中 · 截止':'已关闭 · 截止')+c.date(task.urgentWindow.deadlineTick),card);if(task.type==='wanted')c.paragraph(card,'求货只收真正运输过的自有货物：在交付城市现买、尚未离城的货物不能用于交付。','form-hint');if(task.longHaul)c.paragraph(card,'途经两个路段。','form-hint');if(task.cargo)c.row('货物准备',task.cargo.complete?(task.cargo.damaged?'已齐备 · 含受损货物':'已齐备'):'还缺'+task.cargo.missing+'件',card);if(task.acceptAt&&task.status==='available'&&!task.acceptableHere&&!task.draftRow)c.paragraph(card,'到达'+task.acceptAt+'后可承接。','form-hint');}return card;}
 S.ui.registerPanel('commission',{title:'委托',render(c,b){const v=commissions(c);c.row('同时进行',v.activeCount+' / '+v.capacity,b);if(v.locked)c.paragraph(b,'商誉达到5后开放普通委托。','form-hint');
   if(v.draft){const group=section(c,b,'出发前候选（点击【开始行程】后才正式承接）');if(!v.draft.rows.length)c.paragraph(group,'暂无候选。');for(const task of v.draft.rows){const card=commissionCard(c,group,{...task,draftSelected:task.selected,draftRow:true},true);if(task.acceptAt)c.paragraph(card,'到达'+task.acceptAt+'后可承接。','form-hint');else if(task.selectable)card.append(c.button(task.selected?'取消选定':'选定（启程时承接）',()=>c.dispatch('trip.draftSelect',{commissionId:task.commissionId,selected:!task.selected})));card.append(c.button('查看委托',()=>c.openSecondary('commission-detail',{commissionId:task.commissionId,draft:true})));}}
   for(const [label,rows]of [['进行中的委托',v.active.filter(x=>activeStatuses.has(x.status))],['本商期委托',v.pool.filter(x=>['available','unavailable'].includes(x.status))]]){const group=section(c,b,label);if(!rows.length)c.paragraph(group,'暂无。');for(const task of rows){const card=commissionCard(c,group,task,true);if(task.status==='available'&&!task.acceptableHere&&task.acceptAt)c.paragraph(card,'到达'+task.acceptAt+'后可承接。','form-hint');card.append(c.button('查看委托',()=>c.openSecondary('commission-detail',{commissionId:task.commissionId})));}}b.append(c.button('委托结果记录',()=>c.openSecondary('commission-history')),c.button('商路奇缘',()=>c.openSecondary('story-lines')));}});
 S.ui.registerPanel('commission-detail',{title:'委托详情',render(c,b,d){const v=commissions(c),draftRow=v.draft?.rows.find(x=>x.commissionId===d.commissionId),task=v.active.find(x=>x.commissionId===d.commissionId)||v.pool.find(x=>x.commissionId===d.commissionId)||(draftRow?{...draftRow,draftSelected:draftRow.selected,draftRow:true}:null);if(d.returnGrace&&!inReturnGrace(c,d.commissionId)){c.paragraph(b,'这份委托已不在本次可处理的返程清单中。');return;}if(!task){c.paragraph(b,'委托记录已更新。');return;}commissionCard(c,b,task,false);
   if(task.draftRow){if(task.acceptAt)inspect(c,b,'承接委托','到达'+task.acceptAt+'后可承接。');else if(task.selectable)b.append(c.button(task.selected?'取消选定':'选定（启程时承接）',()=>c.dispatch('trip.draftSelect',{commissionId:task.commissionId,selected:!task.selected})));else inspect(c,b,'承接委托','本期已无法承接。');return;}
   if(task.status==='available'){if(task.acceptableHere)mutate(c,b,'承接委托','commission.accept',{commissionId:task.commissionId});else inspect(c,b,'承接委托',task.acceptAt?'到达'+task.acceptAt+'后可承接。':'请到张榜城市承接。');}if(task.status==='pending_pickup')mutate(c,b,'领取委托货物','commission.pickup',{commissionId:task.commissionId});if(activeStatuses.has(task.status)){let canDeliver=false,reason='当前城市、时辰、货物或期限尚不符合交付条件。';try{canDeliver=S.commissions.eligibleDelivery(c.p,task,S.core.context('ui-read'));}catch(e){reason=e.message;}if(canDeliver)mutate(c,b,'交付委托','commission.deliver',{commissionId:task.commissionId});else inspect(c,b,'交付委托',reason);b.append(c.button('放弃委托',()=>confirm(c,'放弃这份委托？','本次约定报酬将取消。绑定货物清单：'+(c.p.inventory.lots.filter(l=>l.ownership==='commissionOwned'&&l.commissionId===task.commissionId).map(l=>l.goodId+' × '+l.quantity).join('、')||'无')+'。确认结果后清理上述绑定货物。','commission.abandon',{commissionId:task.commissionId}),{className:'ui-button danger-button'}));}}});
 S.ui.registerPanel('commission-history',{title:'委托结果记录',render(c,b){const rows=commissions(c).results;if(!rows.length)c.paragraph(b,'暂无委托结果。');for(const r of [...rows].reverse()){const card=section(c,b,r.title||'委托结果');c.paragraph(card,r.text||status[r.status]);c.row('实际获得',c.formatMoney(r.actualCash),card);c.row('商誉变化',r.actualReputation,card);}}});
 // ---- 商路奇缘 FINAL v1.0 (2026-09-13): 委托 → 商路奇缘 → six permanent cards; completed cards open the finale directory card (three vertical entries, no default text); all views 0 Tick / read-only.
 const storyRows=c=>S.stories?S.stories.snapshot(S.util.clone(c.p),S.core.context('ui-read')):[];
 const storyView=new Map();   // lineId → null | 'recap' | 'gains' | 'notes'  (finale view) ;  'dir:'+branch (QY06 chapter-1 direction pick). UI state only, never saved.
 const cityLabel=id=>city[id]||'长安或敦煌';
 function storyStatusText(line){switch(line.displayStatus){case 'locked':return '尚未开启';case 'available':return '可以开启';case 'active':return '进行中 · '+line.chapter.title;case 'waitingGoods':return '等待货物 · '+line.neededGoods.goodId+' × '+line.neededGoods.quantity;case 'waitingLocation':return '下一步：前往'+cityLabel(line.nextCity);case 'completed':return '已完成';default:return '';}}
 function storyOpen(c,line){storyView.delete(line.lineId);c.openSecondary('story-detail',{lineId:line.lineId});}
 S.ui.registerPanel('story-lines',{title:'商路奇缘',render(c,b){const rows=storyRows(c);if(!rows.length){c.paragraph(b,'商路奇缘记录尚未载入。');return;}
   for(const line of rows){const card=section(c,b,line.name);card.classList.add('story-card');card.dataset.lineId=line.lineId;card.dataset.status=line.displayStatus;card.setAttribute('role','button');card.tabIndex=0;
     c.paragraph(card,storyStatusText(line),'story-status');
     if(line.displayStatus==='locked')c.paragraph(card,line.triggerText,'form-hint');
     if(line.displayStatus==='active'&&line.nextCity&&(!c.p.world.route&&c.p.world.city!==line.nextCity||c.p.world.route))c.paragraph(card,'下一步：前往'+cityLabel(line.nextCity),'story-next');
     if(line.displayStatus==='waitingGoods')c.paragraph(card,'已备 '+line.neededGoods.held+' / '+line.neededGoods.quantity+'件完好'+line.neededGoods.goodId,'form-hint');
     const label={locked:'查看',available:'查看',active:'继续',waitingGoods:'查看',waitingLocation:'查看',completed:'回看此缘'}[line.displayStatus]||'查看';
     card.append(c.button(label,()=>storyOpen(c,line),{className:'ui-button story-card-action'}));
     card.addEventListener('click',e=>{if(e.target.closest('button'))return;storyOpen(c,line);});card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();storyOpen(c,line);}});}
 }});
 function renderFinale(c,b,line){const f=line.finale,view=storyView.get(line.lineId)||null,box=c.el('div','story-finale');box.dataset.view=view||'directory';
   if(!view){box.append(c.el('div','story-finale-eyebrow',f.eyebrow),c.el('h3','',f.name),c.el('div','story-finale-subtitle',f.subtitle));const entries=c.el('div','story-finale-entries');
     for(const key of ['recap','gains','notes']){const btn=c.button(f.entries[key],()=>{storyView.set(line.lineId,key);S.ui.render(c.state);});btn.dataset.entry=key;btn.setAttribute('aria-pressed','false');entries.append(btn);}
     box.append(entries);b.append(box);return;}
   box.append(c.el('div','story-finale-eyebrow',f.eyebrow+' · '+f.name),c.el('h4','story-finale-detail-title',f.entries[view]));const body=c.el('div','story-finale-body');
   if(view==='recap'){for(const ch of f.recap)c.paragraph(body,ch.label+'：'+(ch.text||''));}
   else if(view==='gains'){body.classList.add('story-gains');const g=f.gains;const money=v=>(v<0?'−':'+')+c.formatMoney(Math.abs(v));
     if(g.cashRows.length){body.append(c.el('h5','','钱财往来'));for(const r of g.cashRows)c.row(r.label,money(r.amount),body);}
     c.row('奇缘所得合计',money(g.netCash),body);
     if(g.repRows.length){body.append(c.el('h5','','商誉所得'));for(const r of g.repRows)c.row(r.label,(r.delta>0?'+':'')+r.delta,body);}
     c.row('商誉合计',(g.repTotal>0?'+':'')+g.repTotal,body);
     if(g.cargoRows.length){body.append(c.el('h5','','沿途交付'));for(const t of g.cargoRows)c.paragraph(body,t);}
     c.paragraph(body,g.footer,'story-gains-footer');}
   else{for(const para of String(f.notes||'').split('\n\n'))c.paragraph(body,para);}
   box.append(body);box.append(c.button(f.backLabel,()=>{storyView.delete(line.lineId);S.ui.render(c.state);},{className:'ui-button secondary-button story-finale-back'}));b.append(box);}
 S.ui.registerPanel('story-detail',{title:'商路奇缘',render(c,b,d){const line=storyRows(c).find(x=>x.lineId===d.lineId);if(!line){c.paragraph(b,'奇缘记录已更新。');return;}
   if(line.displayStatus==='completed'&&line.finale){renderFinale(c,b,line);return;}
   b.append(c.el('h3','',line.name));
   if(line.progress?.activeChapter){const a=line.progress.activeChapter;c.paragraph(b,line.chapter.title,'story-chapter-title');c.paragraph(b,line.chapter.text,'story-chapter-text');
     for(const lot of line.cargo||[])c.row(lot.label,lot.quantity+'件 · '+lot.slots+'货位 · '+lot.states.map(x=>({intact:'完好',damaged:'受损',destroyed:'损毁'})[x]).join('、'),b);for(const v of line.vouchers||[])c.row(v.label,v.text,b);
     if(a.phase==='highDisclosure')c.paragraph(b,'这份高价只收少量药材。你准备怎样向药商说明？');
     if(line.offer)c.paragraph(b,line.offer);
     if(line.neededGoods)c.row('须备完好自有'+line.neededGoods.goodId,line.neededGoods.held+' / '+line.neededGoods.quantity+'件',b);
     if(line.nextCity&&(c.p.world.route||c.p.world.city!==line.nextCity))c.paragraph(b,'下一步：前往'+cityLabel(line.nextCity),'form-hint');
     const choices=line.actionChoices;
     if(line.lineId==='QY06'&&a.chapter===1&&choices.some(x=>x.branch)){const dir=(storyView.get(line.lineId)||'').startsWith('dir:')?storyView.get(line.lineId).slice(4):null;
       if(!dir){for(const branch of ['steady','value','urgent']){const first=choices.find(x=>x.branch===branch);if(first)b.append(c.button(S.content.storyCopy?.QY06?.chapters?.['1']?.choices?.[branch]||branch,()=>{storyView.set(line.lineId,'dir:'+branch);S.ui.render(c.state);}));}}
       else{for(const choice of choices.filter(x=>x.branch===dir))b.append(c.button(choice.goodId,()=>c.dispatch('story.act',{lineId:line.lineId,choiceId:choice.id})));b.append(c.button('重选方向',()=>{storyView.delete(line.lineId);S.ui.render(c.state);},{className:'text-button'}));}}
     else for(const choice of choices)b.append(c.button(choice.text,()=>c.dispatch('story.act',{lineId:line.lineId,choiceId:choice.id})));
     b.append(c.button('暂缓办理',()=>c.closeSecondary(),{className:'text-button'}));}
   else if(line.displayStatus==='locked'){c.paragraph(b,line.triggerText,'form-hint');}
   else if(line.displayStatus==='waitingLocation'){c.paragraph(b,line.chapter.title,'story-chapter-title');c.paragraph(b,'下一步：前往'+cityLabel(line.nextCity),'form-hint');c.paragraph(b,'每个商期最多出现一个新章节。到达后可在此继续。','form-hint');}
   else{c.paragraph(b,line.chapter.title,'story-chapter-title');c.paragraph(b,'每个商期最多出现一个新章节。继续后才会展开本章正文。','form-hint');for(const choice of line.startChoices){const costs=[];if(choice.cashCost)costs.push(choice.cashCost+'钱');if(choice.cargoSlots!==undefined)costs.push(choice.cargoSlots+'货位');b.append(c.button(choice.text+(costs.length?' · '+costs.join(' / '):''),()=>c.dispatch('story.begin',{lineId:line.lineId,choiceId:choice.id})));}b.append(c.button('暂不理会',async()=>{const result=await c.dispatch('story.ignore',{lineId:line.lineId});if(result!==null)c.closeSecondary();},{className:'text-button'}));}
 },footer(c,f,d){const line=storyRows(c).find(x=>x.lineId===d.lineId);if(!line||line.displayStatus!=='completed'||!line.finale)return;if(storyView.get(line.lineId))return;const close=c.button(line.finale.closeLabel,()=>{storyView.delete(line.lineId);c.closeSecondary();});close.dataset.storyClose=line.lineId;f.append(close);}});
 for(const kind of ['storyChapterOpened','storyChapterCompleted','storyStageSettled'])S.ui.registerResult(kind,(c,b,r)=>{for(const para of String(r.text||'').split('\n\n'))if(para)c.paragraph(b,para);for(const lot of r.cargoAdded||[])c.row('特殊货物',(lot.storyLabel||lot.goodId)+' × '+(lot.storyUnits?.length||lot.quantity),b);for(const lot of r.consumedCargo||[])c.row('已交出',(lot.storyLabel||lot.goodId)+' × '+(lot.storyUnits?.length||lot.quantity),b);if(r.voucher)c.row('取得凭据','旧货票',b);for(const l of r.lines||[])c.row(l.label,(l.amount<0?'−':'')+c.formatMoney(Math.abs(l.amount)),b);if(Number.isSafeInteger(r.actualCash)&&(r.actualCash||!(r.lines||[]).length))c.row(r.actualCash<0?'实际支出':'实际获得',c.formatMoney(Math.abs(r.actualCash)),b);if(Number.isSafeInteger(r.actualReputation)&&r.actualReputation)c.row('商誉变化',(r.actualReputation>0?'+':'')+r.actualReputation,b);});
 for(const kind of ['commissionPickup','commissionAccepted','commissionDelivered','commissionFailed'])S.ui.registerResult(kind,(c,b,r)=>{c.paragraph(b,r.text||{commissionPickup:'委托货物已收入行囊。',commissionAccepted:'委托已承接。',commissionDelivered:'委托已经交付。',commissionFailed:'这份委托未能完成。'}[kind]);if(r.lot)c.row('收到货物',r.lot.goodId+' × '+r.lot.quantity,b);if(r.missingSlots)c.row('取货仍需空位',r.missingSlots,b);if(Number.isSafeInteger(r.actualCash))c.row('实际获得',c.formatMoney(r.actualCash),b);if(Number.isSafeInteger(r.actualReputation))c.row('商誉变化',r.actualReputation,b);if(r.rewardRatio!==undefined&&r.rewardRatio<1){c.row('原约定报酬',c.formatMoney(r.originalReward),b);c.row('受损折算',Math.round(r.rewardRatio*100)+'%',b);}if(r.removedCargo?.length){for(const lot of r.removedCargo)c.row(lot.goodId+' · 待清理',lot.quantity+'件',b);c.paragraph(b,'确认后清理上述失效委托的绑定货物。','form-hint');}});
})(globalThis.Silk=globalThis.Silk||{});
