#!/usr/bin/env python3
"""Generates caravan.css from caravan-demo/style.css (the standalone archive stylesheet).
Every rule is scoped under .caravan-shell; page-shell rules (body / main / test bar / loading overlay) are dropped and replaced by the
host block below; :root custom properties move onto .caravan-shell; keyframes get a cv- prefix; camel / saddlebag art comes from
S.assets at runtime (caravan-ui.js) instead of CSS urls. Rerun after any change to caravan-demo/style.css."""
import re, os
ROOT = os.path.join(os.path.dirname(__file__), '..', '..')
src = open(os.path.join(ROOT, 'caravan-demo', 'style.css')).read()
def parse(css):
    out = []; i = 0; n = len(css)
    while i < n:
        m = re.match(r'\s*(/\*.*?\*/\s*)*', css[i:], re.S); i += m.end() if m else 0
        if i >= n: break
        j = css.index('{', i); sel = css[i:j].strip(); depth = 1; k = j + 1
        while depth:
            if css[k] == '{': depth += 1
            elif css[k] == '}': depth -= 1
            k += 1
        out.append((sel, css[j + 1:k - 1])); i = k
    return out
DROP = re.compile(r'^(\*|body|html|\.shell|\.tools|main|#debug-panel|#error|body\.debug-mobile|\.prototype-note|#loading|\.loading-|\.outer|\.fixed-timer|@media\s*\(prefers-reduced-motion)')
KF = {'popIn': 'cv-popIn', 'wobble': 'cv-wobble', 'bagPulse': 'cv-bagPulse', 'bagShake': 'cv-bagShake'}
def fix_decl(body):
    body = body.replace("url('assets/camel.png')", 'none')
    for a, b in KF.items(): body = re.sub(r'\b' + a + r'\b', b, body)
    return body
def prefix(sel):
    parts = []
    for s in sel.split(','):
        s = s.strip()
        if not s or DROP.match(s): continue
        parts.append('.caravan-shell' if s == ':root' else '.caravan-shell ' + s)
    return ','.join(parts)
def emit(blocks, out):
    for sel, body in blocks:
        if sel.startswith('@keyframes'):
            name = sel.split()[1]; out.append('@keyframes ' + KF.get(name, 'cv-' + name) + '{' + body.strip() + '}'); continue
        if sel.startswith('@media'):
            if DROP.match(sel): continue
            inner = []; emit(parse(body), inner)
            if inner: out.append(sel + '{' + ''.join(inner) + '}')
            continue
        if sel.startswith('.bag::before') or sel.startswith('.bag.target::before'): continue
        ps = prefix(sel)
        if not ps: continue
        out.append(ps + '{' + fix_decl(body).strip() + '}')
out = []; emit(parse(src), out)
host = '''/* 驼队装货 — main-game host styling. GENERATED by tests/tools/gen-caravan-css.py from caravan-demo/style.css (standalone archive
   v1.0): every rule scoped under .caravan-shell; the panel-level rules below replace the standalone page shell (body / main / test bar).
   Camel and saddlebag art come from S.assets at runtime (caravan_camel_v0, caravan_saddlebag_v0) instead of CSS urls. */
.paper-panel[data-panel-id="caravan"]>.panel-body{padding:6px 6px 4px;overflow:hidden;display:flex;flex-direction:column}
.paper-panel[data-panel-id="caravan"]>.panel-footer{display:none}
.paper-panel[data-panel-id="caravan"]>.panel-header h2,.paper-panel[data-panel-id="dunhuang-work"]>.panel-header h2{font-size:1.02rem;letter-spacing:.18em;font-weight:500}
.caravan-shell{position:relative;display:flex;flex-direction:column;flex:1 1 auto;min-height:0;height:100%;font-family:system-ui,-apple-system,'PingFang SC',sans-serif;color:#302b22;font-size:16px;line-height:1.4;background:#f6ead0;border:1px solid #bb9b64;border-radius:12px;overflow:hidden}
.caravan-shell *{box-sizing:border-box}
.caravan-shell button,.caravan-shell select,.caravan-shell input{font:inherit}
.caravan-shell>section{flex:1 1 auto;min-height:0}
.caravan-shell .head{height:36px;padding:0 12px;border-bottom:1px solid #cbb991;display:flex;align-items:center;gap:8px}
.caravan-shell .head .batch{flex:1;font-size:14px}
.caravan-shell .game{height:calc(100% - 36px)}
.caravan-shell .ready,.caravan-shell .how,.caravan-shell .settlement{height:100%}
.caravan-shell .bag .bag-art{position:absolute;inset:0;width:100%;height:100%;display:block;pointer-events:none;transition:filter .25s}
.caravan-shell .bag.target .bag-art{animation:cv-bagPulse 1.1s ease-in-out infinite alternate}
.caravan-shell .inline-error{color:#9a2f1e;font-size:13px;text-align:center;margin:6px 0 0}
.caravan-job-card{padding:12px 14px;border:1px solid rgba(122,65,41,.22);border-radius:6px;background:rgba(255,250,236,.7)}
.caravan-job-card h3{margin:0 0 4px;font-size:1rem;letter-spacing:.12em}
.caravan-job-desc{margin:0 0 6px;font-size:.92rem;line-height:1.7}
.caravan-job-meta{display:flex;gap:14px;font-size:.82rem;color:#7a5a3a;margin-bottom:8px}
.caravan-job-art{height:110px;margin:4px 0 10px;background-size:200% 100%;background-position:left center;background-repeat:no-repeat;opacity:.94}
.caravan-job-note{font-size:.82rem;color:#8a4a36;margin:0 0 8px}
/* Round-4 art pages (READY / SETTLEMENT): the panel frame steps back, the host close button floats over the art, the panel title is carried by the art page itself */
.paper-panel.caravan-art{padding:0;background:#e9d8b8;border-color:#b58a3c}
.paper-panel.caravan-art::before{display:none}
.paper-panel.caravan-art>.panel-header{position:absolute;top:0;right:0;left:auto;z-index:3;border:0;min-height:0;padding:8px 8px 0 0;background:transparent;pointer-events:none}
.paper-panel.caravan-art>.panel-header h2{display:none}
.paper-panel.caravan-art>.panel-header .close-button{pointer-events:auto;width:38px;height:38px;flex:0 0 38px;padding:7px;border-radius:50%;background:#f6ead2e6;border:1.5px solid #7a2e1e;box-shadow:0 1px 3px #0004}
.paper-panel.caravan-art>.panel-body{padding:0;overflow:hidden}
.paper-panel.caravan-no-close>.panel-header .close-button{display:none}
.paper-panel.caravan-art .caravan-shell{border:0;border-radius:inherit;background:#e9d8b8}
@media(prefers-reduced-motion:reduce){.caravan-shell *{animation-duration:.01ms!important;transition-duration:.01ms!important}}
'''
open(os.path.join(ROOT, 'caravan.css'), 'w').write('\n'.join(out) + '\n' + host)   # host block last so its shell/background rules win over the mapped :root
print('caravan.css', len(host) + sum(len(x) for x in out), 'bytes;', len(out), 'rules')
