import { bridge } from './bridge.js?v=f96fa352e9';
import { icon } from './cargo-icons.js?v=f96fa352e9';
const app=document.querySelector('#app'),sec=document.querySelector('#seconds'),group=document.querySelector('#group'),dbg=document.querySelector('#debug');
const art=kind=>`<img class="glyph" src="${icon(kind)}" alt="" draggable="false">`;
const tier={RICH:'出色',NORMAL:'合格',MODEST:'完成'};
let data=null,selected=null,contextHint='',hintUntil=0,busy=false,polling=false,revision=0,lastKey='',prevState='',prevBatch=0;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function error(s){const el=document.querySelector('#error');el.textContent=s;el.hidden=false;setTimeout(()=>el.hidden=true,4000)}
async function action(op,extra={}){if(busy)return;busy=true;window.__appBusy=true;revision++;try{data=await bridge.action({op,...extra});render();}catch(e){error(e.message)}finally{busy=false;window.__appBusy=false}}
async function poll(){if(busy||polling)return;polling=true;const rev=revision;try{const x=await bridge.state();if(rev===revision&&!busy){data=x;render()}}catch(e){error(e.message)}finally{polling=false}}
function head(game=false,close=true){return `<header class="head"><h1>驼队装货</h1>${game?`<span class="batch">${data.mode==='TRIAL'?'试玩 · ':''}第${data.batch}批</span><span class="timer" aria-label="剩余时间"></span>`:''}${close?'<button class="close" data-op="close" aria-label="关闭">×</button>':''}</header>`}
function context(){if(Date.now()<hintUntil)return contextHint;if(!selected)return '选中货物，再点击袋口上方的【放入 ↓】';const c=data.cargo[selected.id];return c?`${c.name}｜${c.weightLabel} · ${c.attributes.join(' · ')}`:''}
function bag(side){const a=data[side],lock=data.state!=='GAMEPLAY';let act='';if(selected?.side==='waiting')act=`<button class="action" data-insert="${side}" ${lock||a.length===4?'disabled':''}>${a.length===4?'已满':'放入 ↓'}</button>`;else if(selected?.side===side&&a.at(-1)===selected.id)act=`<button class="action" data-remove="${side}" ${lock?'disabled':''}>取出 ↑</button>`;
return `<div class="bag ${side}" aria-label="${side==='left'?'左侧鞍袋':'右侧鞍袋'}">${act}${a.map((id,i)=>{const c=data.cargo[id];return `<button class="bag-item ${selected?.id===id?'selected':''}" style="bottom:${12+i*27}px;z-index:${i+2};margin-left:${i%2?2:-2}px" data-id="${id}" data-side="${side}" aria-label="${c.name}${i===a.length-1?'，顶层':'，下层'}" ${lock?'disabled':''}>${art(c.kind)}<span class="mini-name">${esc(c.name)}</span>${data.warnings.includes(id)?'<b class="warn">!</b>':''}</button>`}).join('')}</div>`}
function game(){const lock=data.state!=='GAMEPLAY',rise=['EVALUATING','FEEDBACK'].includes(data.state),msg=data.state==='EVALUATING'?'骆驼起身试载…':data.state==='FEEDBACK'?(data.feedback==='PASS'?'装好了 · '+tier[data.lastTier]:'还不够稳，再调一调'):data.state==='TRANSITION'?'下一匹骆驼来了':data.state==='TIMEOUT'?'时辰到了':'';
return head(true)+`<section class="game"><div class="balance-wrap"><div class="balance-track" aria-label="装驮平衡"><i class="bead"></i></div><div class="context" role="status">${esc(context())}</div></div><div class="stage ${rise?'rise':''} ${data.feedback==='NOT_PASS'&&data.state==='FEEDBACK'?'wobble':''} ${data.state==='TRANSITION'?'fade':''}"><div class="camel" role="img" aria-label="${rise?'起身试载的骆驼':'卧姿骆驼'}"></div>${msg?`<div class="feedback" role="status">${msg}</div>`:''}${bag('left')}${bag('right')}</div><div class="waiting ${data.slots.length===4?'one-row':''}">${data.slots.map(id=>{const c=data.cargo[id];return `<button class="cargo ${data.waiting.includes(id)?'':'absent'} ${selected?.id===id?'selected':''}" data-id="${id}" data-side="waiting" ${lock||!data.waiting.includes(id)?'disabled':''} aria-label="${esc(c.name+'，'+c.weightLabel+'，'+c.attributes.join('、'))}">${art(c.kind)}<span class="name">${esc(c.name)}</span><span class="meta">${c.weightLabel} · ${c.attributes[0]}</span></button>`}).join('')}${data.canSubmit?'<button class="primary submit" data-op="submit">确认装好</button>':''}</div></section>${data.state==='ABORT_CONFIRM'?'<section class="abort-layer" role="alertdialog" aria-modal="true" aria-label="结束装货确认"><h2>要结束这次装货吗？</h2><p>已完成的进度不会保留，本次也不会获得工钱或消耗时间。</p><button class="primary" data-op="cancel_abort">继续装货</button><button class="secondary" data-op="confirm_abort">结束装货</button></section>':''}`}
function render(){if(!data)return;const state=data.state;if(data.batch!==prevBatch||(!['GAMEPLAY','ABORT_CONFIRM'].includes(state)&&state!==prevState))selected=null;prevBatch=data.batch;
const active=['GAMEPLAY','EVALUATING','FEEDBACK','TRANSITION','TIMEOUT','ABORT_CONFIRM'].includes(state);sec.disabled=group.disabled=active;
const key=JSON.stringify({...data,remaining:0,debug:undefined,selected,contextHint:Date.now()<hintUntil?contextHint:''});
if(key!==lastKey){lastKey=key;
if(state==='READY'){const ready=data.prepared.includes(Number(group.value)),failed=data.errors[group.value];app.innerHTML=head()+`<section class="ready"><div class="emblem"><div class="camel" role="img" aria-label="骆驼"></div></div><h2>驼队待发</h2><p>替货栈将货物稳妥装上驼背。<br>左右装匀，货物放稳，可多得工钱。</p><button class="primary" data-mode="FORMAL" ${ready?'':'disabled'}>开始装货</button><button class="secondary" data-mode="TRIAL" ${ready?'':'disabled'}>试玩</button><button class="text-button" data-op="how">玩法说明 ⓘ</button><div class="status">${failed?'题目准备未完成，请换一组再试':ready?'':'正在备货…'}</div></section>`;}
else if(state==='HOW_TO_PLAY')app.innerHTML=head()+`<section class="how"><div><h2>怎么玩</h2><p>选中货物，再点击袋口上方的【放入 ↓】。<br>后放的货会叠在上面。<br>只能从最上层取出货物。</p></div><div><h2>怎么装得稳</h2><p>两边尽量装匀。<br>重货放低些更稳。<br>怕压的货不要垫在重货下面。<br>易损的货尽量别让重货压在上面。</p></div><div><h2>试玩</h2><p>试玩可以完整体验三批装货。<br>不消耗时间，也不会获得实际工钱。</p></div><button class="primary" data-op="ready">知道了</button></section>`;
else if(active)app.innerHTML=game();
else if(state==='SETTLEMENT'){const r=data.settlement;app.innerHTML=head(false,false)+`<section class="settlement"><h2>${r.completed?'驼队装货完成':'驼队装货结束'}</h2><div class="tiers">${[0,1,2].map(i=>`<span>第${i+1}批<br><b>${tier[r.tiers[i]]||'未完成'}</b></span>`).join('')}</div>${r.completed?`<div class="payrow"><span>基础工钱</span><b>${r.base} 钱</b></div><div class="payrow"><span>额外工钱</span><b>${r.extra} 钱</b></div>`:'<p>未完成有效装驮</p>'}<div class="payrow total"><span>${data.mode==='TRIAL'?'模拟所得':'今日所得'}</span><span>${r.cash} 钱</span></div>${data.mode==='TRIAL'?'<p>试玩不消耗时间，也不会获得实际工钱。</p>':''}<div class="outlets"><button class="primary" data-dest="LIVELIHOOD_LIST">返回营生</button><button class="secondary" data-dest="CITY">退出营生</button></div></section>`}
else app.innerHTML=`<section class="outer"><h1>${state==='CITY'?'敦煌':'敦煌 · 营生'}</h1><p>${state==='CITY'?'歇一歇，再上路。':'货栈的驼队正等着装货。'}</p><button class="primary" data-op="${state==='CITY'?'livelihood':'ready'}">${state==='CITY'?'营生':'驼队装货'}</button></section>`;
if(state!==prevState){app.querySelector('button:not([disabled])')?.focus({preventScroll:true})}
}
const timer=app.querySelector('.timer');if(timer){timer.textContent=`${Math.ceil(data.remaining)}s`;timer.className='timer'+(data.remaining<=5?' urgent':data.remaining<=15?' low':'')}
const bead=app.querySelector('.bead');if(bead){const b=data.balance,r=b.ratio;let offset=r===null?0:r>=.85?(1-r)/.15*15:r>=.8?15+(.85-r)/.05*15:30+(.8-r)/.8*18;bead.style.left=`${50+b.direction*offset}%`;bead.classList.toggle('empty',r===null);bead.dataset.band=b.band}
dbg.checked=data.debugEnabled;document.querySelector('#debug-panel').hidden=!data.debugEnabled;document.body.classList.toggle('debug-mobile',data.debugEnabled&&innerWidth<1120);document.querySelector('#debug-data').textContent=data.debugEnabled?JSON.stringify(data.debug||{state},null,2):'';prevState=state;}
app.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled||busy)return;
if(b.dataset.id){if(data.state!=='GAMEPLAY')return;selected={id:b.dataset.id,side:b.dataset.side};if(selected.side!=='waiting'&&data[selected.side].at(-1)!==selected.id){contextHint='先取出上层货物';hintUntil=Date.now()+1700;}lastKey='';render();return}
if(b.dataset.insert){const id=selected.id;selected=null;return action('insert',{id,side:b.dataset.insert})}
if(b.dataset.remove){const id=selected.id;selected=null;return action('remove',{id,side:b.dataset.remove})}
if(b.dataset.mode)return action('start',{mode:b.dataset.mode,seconds:Number(sec.value),index:Number(group.value)});
if(b.dataset.dest)return action('navigate',{destination:b.dataset.dest});
if(b.dataset.op){let op=b.dataset.op;if(op==='close'&&data.state==='GAMEPLAY')op='abort';if(op==='close'&&!['READY','HOW_TO_PLAY','GAMEPLAY'].includes(data.state))return;return action(op)}
});
group.addEventListener('change',()=>{group.value=String(Math.max(0,Math.min(499,Math.trunc(Number(group.value)||0))));lastKey='';action('prepare',{index:Number(group.value)})});dbg.addEventListener('change',()=>action('debug',{enabled:dbg.checked}));addEventListener('resize',()=>{lastKey='';render()});
const loading=document.querySelector('#loading'),loadingText=document.querySelector('#loading-text');bridge.onStatus(m=>{if(m.type==='progress')loadingText.textContent=m.text;if(m.type==='fatal'){loadingText.textContent='装货台加载失败：'+m.error+'（请刷新重试）';}});
try{await bridge.ready;}catch(e){throw e;}
loadingText.textContent='正在备货…';await poll();render();await action('prepare',{index:Number(group.value)});loading.hidden=true;setInterval(poll,120);
