import { bridge } from './bridge.js?v=7ce23d98f1';
import { icon } from './cargo-icons.js?v=7ce23d98f1';
const app=document.querySelector('#app'),sec=document.querySelector('#seconds'),group=document.querySelector('#group'),dbg=document.querySelector('#debug');
const art=kind=>`<img class="glyph" src="${icon(kind)}" alt="" draggable="false">`;
const tier={RICH:'出色',NORMAL:'合格',MODEST:'完成'};
let data=null,selected=null,contextHint='',hintUntil=0,busy=false,polling=false,revision=0,lastKey='',prevState='',prevBatch=0,firstPop=false,popShown=false,beadLeft=50;
function hint(text,ms=1700){contextHint=text;hintUntil=Date.now()+ms;lastKey='';render()}
function shake(side){const el=app.querySelector('.bag.'+side);if(!el)return;el.classList.remove('shake');void el.offsetWidth;el.classList.add('shake');setTimeout(()=>el.classList.remove('shake'),450)}
async function putInto(side){if(!selected||selected.side!=='waiting'||data.state!=='GAMEPLAY')return;if(data[side].length===4){hint('这只驼袋已满');shake(side);return}const id=selected.id;selected=null;firstPop=false;return action('insert',{id,side})}
function fitRig(){const stage=app.querySelector('.stage'),rig=app.querySelector('.rig');if(!stage||!rig)return;const w=stage.clientWidth,h=stage.clientHeight-8;const rh=Math.max(190,Math.min(h,w*.72,330));rig.style.height=rh+'px';rig.style.width=Math.min(w,rh/.72)+'px';}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function error(s){const el=document.querySelector('#error');el.textContent=s;el.hidden=false;setTimeout(()=>el.hidden=true,4000)}
async function action(op,extra={}){if(busy)return;busy=true;window.__appBusy=true;revision++;try{data=await bridge.action({op,...extra});render();}catch(e){error(e.message)}finally{busy=false;window.__appBusy=false}}
async function poll(){if(busy||polling)return;polling=true;const rev=revision;try{const x=await bridge.state();if(rev===revision&&!busy){data=x;render()}}catch(e){error(e.message)}finally{polling=false}}
function head(game=false,close=true){return `<header class="head"><h1>驼队装货</h1>${game?`<span class="batch">${data.mode==='TRIAL'?'试玩 · ':''}第${data.batch}批</span><span class="timer" aria-label="剩余时间"></span>`:''}${close?'<button class="close" data-op="close" aria-label="关闭">×</button>':''}</header>`}
function context(){if(Date.now()<hintUntil)return contextHint;if(!selected)return '选中货物，点驼袋放入；点袋中最上面的货物可取出';const c=data.cargo[selected.id];return c?`${c.name}｜${c.weightLabel} · ${c.attributes.join(' · ')}`:''}
function bag(side){const a=data[side],lock=data.state!=='GAMEPLAY',full=a.length===4,target=!lock&&selected?.side==='waiting';const pop=firstPop?' pop':'';
const act=target?`<button class="action${pop}${full?' full':''}" data-insert="${side}" ${full?'disabled':''}>${full?'已满':'放入 ↓'}</button>`:'';
return `<div class="bag ${side}${target?' target':''}${full?' is-full':''}" data-bag="${side}" role="group" aria-label="${side==='left'?'左侧驼袋':'右侧驼袋'}，${a.length}/4 件">${act}<div class="bag-stack">${[0,1,2,3].map(i=>`<i class="slot l${i}" aria-hidden="true"></i>`).join('')}${a.map((id,i)=>{const c=data.cargo[id],top=i===a.length-1;return `<button class="bag-item l${i} ${top?'top':'lower'}" style="z-index:${i+2}" data-id="${id}" data-side="${side}" aria-label="${esc(c.name)}${top?'，顶层，点击取出':'，下层'}" ${lock?'disabled':''}>${art(c.kind)}${data.warnings.includes(id)?'<b class="warn" aria-label="有问题">!</b>':''}</button>`}).join('')}</div></div>`}
function game(){const lock=data.state!=='GAMEPLAY',rise=['EVALUATING','FEEDBACK'].includes(data.state),msg=data.state==='EVALUATING'?'骆驼起身试载…':data.state==='FEEDBACK'?(data.feedback==='PASS'?'装好了 · '+tier[data.lastTier]:'还不够稳，再调一调'):data.state==='TRANSITION'?'下一匹骆驼来了':data.state==='TIMEOUT'?'时辰到了':'';
return head(true)+`<section class="game"><div class="balance-wrap"><div class="balance-track" aria-label="装驮平衡"><i class="bead" style="left:${beadLeft}%"></i></div><div class="context" role="status">${esc(context())}</div></div><div class="stage ${rise?'rise':''} ${data.feedback==='NOT_PASS'&&data.state==='FEEDBACK'?'wobble':''} ${data.state==='TRANSITION'?'fade':''}">${msg?`<div class="feedback" role="status">${msg}</div>`:''}<div class="rig"><div class="camel" role="img" aria-label="${rise?'起身试载的骆驼':'卧姿骆驼'}"></div><i class="ground" aria-hidden="true"></i>${bag('left')}${bag('right')}</div></div><div class="waiting ${data.slots.length===4?'one-row':''}">${data.slots.map(id=>{const c=data.cargo[id];return `<button class="cargo ${data.waiting.includes(id)?'':'absent'} ${selected?.id===id?'selected':''}" data-id="${id}" data-side="waiting" ${lock||!data.waiting.includes(id)?'disabled':''} aria-label="${esc(c.name+'，'+c.weightLabel+'，'+c.attributes.join('、'))}">${art(c.kind)}<span class="name">${esc(c.name)}</span><span class="meta">${c.weightLabel} · ${c.attributes[0]}</span></button>`}).join('')}${data.canSubmit?'<button class="primary submit" data-op="submit">确认装好</button>':''}</div></section>${data.state==='ABORT_CONFIRM'?'<section class="abort-layer" role="alertdialog" aria-modal="true" aria-label="结束装货确认"><h2>要结束这次装货吗？</h2><p>已完成的进度不会保留，本次也不会获得工钱或消耗时间。</p><button class="primary" data-op="cancel_abort">继续装货</button><button class="secondary" data-op="confirm_abort">结束装货</button></section>':''}`}
function render(){if(!data)return;const state=data.state;if(data.batch!==prevBatch||(!['GAMEPLAY','ABORT_CONFIRM'].includes(state)&&state!==prevState))selected=null;prevBatch=data.batch;
const active=['GAMEPLAY','EVALUATING','FEEDBACK','TRANSITION','TIMEOUT','ABORT_CONFIRM'].includes(state);sec.disabled=group.disabled=active;
const key=JSON.stringify({...data,remaining:0,debug:undefined,selected,contextHint:Date.now()<hintUntil?contextHint:''});
if(key!==lastKey){lastKey=key;
if(state==='READY'){const ready=data.prepared.includes(Number(group.value)),failed=data.errors[group.value];app.innerHTML=head()+`<section class="ready"><div class="emblem"><div class="camel" role="img" aria-label="骆驼"></div></div><h2>驼队待发</h2><p>替货栈将货物稳妥装上驼背。<br>左右装匀，货物放稳，可多得工钱。</p><button class="primary" data-mode="FORMAL" ${ready?'':'disabled'}>开始装货</button><button class="secondary" data-mode="TRIAL" ${ready?'':'disabled'}>试玩</button><button class="text-button" data-op="how">玩法说明 ⓘ</button><div class="status">${failed?'题目准备未完成，请换一组再试':ready?'':'正在备货…'}</div></section>`;}
else if(state==='HOW_TO_PLAY')app.innerHTML=head()+`<section class="how"><div><h2>怎么玩</h2><p>选中货物，再点驼袋放入；点袋中最上面的货物可取出。<br>每只驼袋最多装 4 件，两袋共 8 件。<br>后放的货会叠在上面，只能从最上层取出。</p></div><div><h2>怎么装得稳</h2><p>两边尽量装匀。<br>重货放低些更稳。<br>怕压的货不要垫在重货下面。<br>易损的货尽量别让重货压在上面。</p></div><div><h2>试玩</h2><p>试玩可以完整体验三批装货。<br>不消耗时间，也不会获得实际工钱。</p></div><button class="primary" data-op="ready">知道了</button></section>`;
else if(active)app.innerHTML=game();
else if(state==='SETTLEMENT'){const r=data.settlement;app.innerHTML=head(false,false)+`<section class="settlement"><h2>${r.completed?'驼队装货完成':'驼队装货结束'}</h2><div class="tiers">${[0,1,2].map(i=>`<span>第${i+1}批<br><b>${tier[r.tiers[i]]||'未完成'}</b></span>`).join('')}</div>${r.completed?`<div class="payrow"><span>基础工钱</span><b>${r.base} 钱</b></div><div class="payrow"><span>额外工钱</span><b>${r.extra} 钱</b></div>`:'<p>未完成有效装驮</p>'}<div class="payrow total"><span>${data.mode==='TRIAL'?'模拟所得':'今日所得'}</span><span>${r.cash} 钱</span></div>${data.mode==='TRIAL'?'<p>试玩不消耗时间，也不会获得实际工钱。</p>':''}<div class="outlets"><button class="primary" data-dest="LIVELIHOOD_LIST">返回营生</button><button class="secondary" data-dest="CITY">退出营生</button></div></section>`}
else app.innerHTML=`<section class="outer"><h1>${state==='CITY'?'敦煌':'敦煌 · 营生'}</h1><p>${state==='CITY'?'歇一歇，再上路。':'货栈的驼队正等着装货。'}</p><button class="primary" data-op="${state==='CITY'?'livelihood':'ready'}">${state==='CITY'?'营生':'驼队装货'}</button></section>`;
if(state!==prevState){app.querySelector('button:not([disabled])')?.focus({preventScroll:true})}
}
fitRig();
const timer=app.querySelector('.timer');if(timer){timer.textContent=`${Math.ceil(data.remaining)}s`;timer.className='timer'+(data.remaining<=5?' urgent':data.remaining<=15?' low':'')}
const bead=app.querySelector('.bead');if(bead){const b=data.balance,r=b.ratio;let offset=r===null?0:r>=.85?(1-r)/.15*15:r>=.8?15+(.85-r)/.05*15:30+(.8-r)/.8*18;const next=Math.round(Math.min(95.5,Math.max(4.5,50+b.direction*offset))*10)/10;if(next!==beadLeft){bead.style.transitionDuration=`${Math.min(.7,.2+Math.abs(next-beadLeft)*.012).toFixed(2)}s, .25s`;bead.style.left=`${next}%`;beadLeft=next}bead.classList.toggle('empty',r===null);bead.dataset.band=b.band}
dbg.checked=data.debugEnabled;document.querySelector('#debug-panel').hidden=!data.debugEnabled;document.body.classList.toggle('debug-mobile',data.debugEnabled&&innerWidth<1120);document.querySelector('#debug-data').textContent=data.debugEnabled?JSON.stringify(data.debug||{state},null,2):'';prevState=state;}
app.addEventListener('click',async e=>{if(busy)return;const b=e.target.closest('button');const bagEl=e.target.closest('.bag');
if(!b){if(bagEl&&selected?.side==='waiting')return putInto(bagEl.dataset.bag);return}
if(b.disabled)return;
if(b.dataset.id){if(data.state!=='GAMEPLAY')return;const id=b.dataset.id,side=b.dataset.side;
if(side==='waiting'){if(selected?.id===id){selected=null;firstPop=false}else{selected={id,side:'waiting'};firstPop=!popShown;if(firstPop)popShown=true}lastKey='';render();return}
if(selected?.side==='waiting')return putInto(side);
if(data[side].at(-1)!==id){hint('先取出上层货物');shake(side);return}
selected=null;return action('remove',{id,side})}
if(b.dataset.insert)return putInto(b.dataset.insert);
if(b.dataset.mode){popShown=false;firstPop=false;return action('start',{mode:b.dataset.mode,seconds:Number(sec.value),index:Number(group.value)});}
if(b.dataset.dest)return action('navigate',{destination:b.dataset.dest});
if(b.dataset.op){let op=b.dataset.op;if(op==='close'&&data.state==='GAMEPLAY')op='abort';if(op==='close'&&!['READY','HOW_TO_PLAY','GAMEPLAY'].includes(data.state))return;return action(op)}
});
group.addEventListener('change',()=>{group.value=String(Math.max(0,Math.min(499,Math.trunc(Number(group.value)||0))));lastKey='';action('prepare',{index:Number(group.value)})});dbg.addEventListener('change',()=>action('debug',{enabled:dbg.checked}));addEventListener('resize',()=>{lastKey='';render();fitRig()});
const loading=document.querySelector('#loading'),loadingText=document.querySelector('#loading-text');bridge.onStatus(m=>{if(m.type==='progress')loadingText.textContent=m.text;if(m.type==='fatal'){loadingText.textContent='装货台加载失败：'+m.error+'（请刷新重试）';}});
try{await bridge.ready;}catch(e){throw e;}
loadingText.textContent='正在备货…';await poll();render();await action('prepare',{index:Number(group.value)});loading.hidden=true;setInterval(poll,120);
