// Generates engine/data.js from the frozen authority JSON (byte-identical data, no hand edits).
const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..');
const cargo = fs.readFileSync(path.join(root, 'py/vendor/p0/authority/CARGO_DATA.json'), 'utf8');
const config = fs.readFileSync(path.join(root, 'py/vendor/p0/authority/PROTOTYPE_CONFIG.json'), 'utf8');
const out = '// GENERATED by tools/gen-data.js from py/vendor/p0/authority/*.json (frozen v0.3 data). Do not edit.\n' +
  'export const CARGO_DATA = ' + JSON.stringify(JSON.parse(cargo)) + ';\n' +
  'export const PROTOTYPE_CONFIG = ' + JSON.stringify(JSON.parse(config)) + ';\n';
fs.writeFileSync(path.join(root, 'engine/data.js'), out); console.log('engine/data.js written', out.length, 'bytes');
