# -*- coding: utf-8 -*-
"""于阗织坊 modal 合成底图生成器（v5.0 modal 迁移）。
输入：art/bg_sort.jpg / bg_warp.jpg / bg_warp_done.jpg / bg_weave.jpg（FINAL v5.0 八图裁出的整页画作，864×1536，canonical）
      art/src/ui09_settle_template_v1.1.png（UI-09 今日收工空模板，954×1649，canonical，来自 YUTIAN_MODAL_AUTHORITY_CONFLICT_RESOLUTION_FINAL_v1.1）
输出：art/modal/body_<phase>.webp —— 只裁织机本体（x 82..782），去掉画作里纯装饰留白的横向切片后按原顺序重新拼接（切口处 10 行羽化），
      不缩放、不重绘；art/modal/body_settle.webp —— UI-09 去掉顶部 HUD 条（y<168）后的原尺寸模板；art/modal/LAYOUT.json —— 运行时与测试共用的布局表。
运行时（weaving-ui.js）把活动部件按画作坐标经 cy() 映射到合成图坐标，再乘以 k（= modal body 高度 / 合成图高度）。
用法：python3 weaving-v5/tools/gen-modal-art.py（在仓库根目录）"""
import json, os, hashlib
from PIL import Image
import numpy as np
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
ART = os.path.join(ROOT, 'art'); OUT = os.path.join(ART, 'modal')
X0, X1, TOP, END = 82, 782, 158, 1336
FEATHER = 10
# removed [a, b) painting rows per phase — every one lies in a decorative region (plain warp threads / plank wood / tassel fringe); no live piece is ever placed inside
PHASES = {
    'sort':      {'src': 'bg_sort.jpg',      'end': END,  'removed': [[708, 795]]},
    'warp':      {'src': 'bg_warp.jpg',      'end': END,  'removed': [[550, 577], [787, 803], [953, 983], [1320, 1334]]},
    'warp_done': {'src': 'bg_warp_done.jpg', 'end': 1349, 'removed': [[505, 550], [989, 1044]]},
    'weave':     {'src': 'bg_weave.jpg',     'end': END,  'removed': [[976, 991], [1136, 1185], [1237, 1260]]},
}
SETTLE = {'src': 'src/ui09_settle_template_v1.1.png', 'top': 168}
def sha(p):
    h = hashlib.sha256(); h.update(open(p, 'rb').read()); return h.hexdigest()
def compose(img, removed, end):
    a = np.asarray(img.convert('RGB')).astype(np.float32)[:, X0:X1]
    keep = []; y = TOP
    for (ra, rb) in removed: keep.append((y, ra)); y = rb
    keep.append((y, end))
    out = a[keep[0][0]:keep[0][1]]
    for (ra, rb), (s, e) in zip(removed, keep[1:]):
        # feather: the last FEATHER kept rows above the cut cross-fade into the FEATHER removed rows that sit just above the lower kept part
        # (their upward continuation), so the composed height stays exactly the sum of the kept rows and every mapping is exact
        w = np.linspace(0, 1, FEATHER, endpoint=False).reshape(-1, 1, 1)
        out = np.concatenate([out[:-FEATHER], out[-FEATHER:] * (1 - w) + a[rb - FEATHER:rb] * w, a[s:e]], axis=0)
    assert out.shape[0] == sum(e - s for (s, e) in keep)
    return Image.fromarray(np.clip(out + 0.5, 0, 255).astype(np.uint8))
def main():
    os.makedirs(OUT, exist_ok=True)
    layout = {'art': {'w': 864, 'h': 1536}, 'crop': {'x0': X0, 'x1': X1, 'w': X1 - X0}, 'top': TOP, 'feather': FEATHER, 'phases': {}, 'settle': None, 'sources': {}}
    heights = set()
    for name, ph in PHASES.items():
        src = os.path.join(ART, ph['src']); img = Image.open(src)
        comp = compose(img, ph['removed'], ph['end']); comp.save(os.path.join(OUT, 'body_%s.webp' % name), 'WEBP', quality=88, method=6)
        h = comp.height; heights.add(h)
        layout['phases'][name] = {'img': 'art/modal/body_%s.webp' % name, 'src': 'art/' + ph['src'], 'w': comp.width, 'h': h, 'end': ph['end'], 'removed': ph['removed']}
        layout['sources']['art/' + ph['src']] = sha(src)
        print(name, comp.size)
    assert len(heights) == 1, heights  # every gameplay phase composes to the same height so k never changes between phases
    s = Image.open(os.path.join(ART, SETTLE['src'])).convert('RGB'); c = s.crop((0, SETTLE['top'], s.width, s.height)); c.save(os.path.join(OUT, 'body_settle.webp'), 'WEBP', quality=88, method=6)
    layout['settle'] = {'img': 'art/modal/body_settle.webp', 'src': 'art/' + SETTLE['src'], 'srcW': s.width, 'srcH': s.height, 'top': SETTLE['top'], 'w': c.width, 'h': c.height}
    layout['sources']['art/' + SETTLE['src']] = sha(os.path.join(ART, SETTLE['src']))
    print('settle', c.size)
    json.dump(layout, open(os.path.join(OUT, 'LAYOUT.json'), 'w'), ensure_ascii=False, indent=1)
    # the same table as a script for the page (single source of truth for weaving-ui.js and the browser tests)
    with open(os.path.join(OUT, 'layout.js'), 'w') as f:
        f.write('/* generated by weaving-v5/tools/gen-modal-art.py — do not edit; see LAYOUT.json */\n')
        f.write('window.YutianWeavingLayout = ' + json.dumps(layout, ensure_ascii=False, separators=(',', ':')) + ';\n')
if __name__ == '__main__': main()
