/* 于阗织坊 FINAL v5.0 — screen layer, 360×620 modal edition (YUTIAN_MODAL_AUTHORITY_CONFLICT_RESOLUTION_FINAL_v1.1).
   The FINAL v5.0 paintings are still the UI: each gameplay phase shows its loom — the painting cropped to the loom (art x 82..782) with its purely
   decorative slices removed (art/modal/LAYOUT.json, generated by tools/gen-modal-art.py) — as the modal body, and only the live parts (hanger tags,
   silk bundles, tension scales, rings, threads, target plaques, the red urgent bar, HUD) are laid on top at their painted positions.
   今日收工 renders on the UI-09 empty template: transparent text at the template's blank positions, every number read from run.wages.
   Coordinates: painting px → composed px (cx / cy) → CSS px (× k, k = modal body height / composed height). No transform: scale() is used to fit. */
(function () {
  'use strict';
  const E = window.YutianWeavingEngine, IDS = E.IDENTITIES.map(i => i.id), ID = Object.fromEntries(E.IDENTITIES.map(i => [i.id, i]));
  const LAYOUT = window.YutianWeavingLayout;
  // painted positions of the live parts in the FINAL v5.0 art space (864×1536) — unchanged from the full-page edition
  const ART = { w: 864, h: 1536, cols: [217, 325, 433, 541, 648], rows: [553, 646, 738, 831, 923], tagX: [227, 328, 429, 534, 636], tagY: 395, trayX: [209, 320, 432, 543, 655], trayY: 1058, scaleX: [214, 321, 431, 541, 650], scaleY: 588, weightX: [213, 320, 431, 543, 655], weightY: 1036, bundleTopY: 322, targetY: 1013, warpDoneBtn: [249, 1268, 363, 78] };
  // UI-09 today's-settlement template (954×1649): the blank positions that receive the dynamic text, and the two painted buttons
  const T9 = { statusBox: [232, 498, 490, 90], rows: [757, 864, 965], totalY: 1111, labelX: 318, labelW: 240, valueX: 655, valueW: 97, stay: [110, 1358, 370, 130], leave: [480, 1358, 370, 130] };
  const BODY = { sort: mkBody('sort'), warp: mkBody('warp'), warp_done: mkBody('warp_done'), weave: mkBody('weave'), settle: { key: 'settle', img: LAYOUT.settle.img, w: LAYOUT.settle.w, h: LAYOUT.settle.h, x0: 0, top: LAYOUT.settle.top, removed: [] } };
  function mkBody(key) { const p = LAYOUT.phases[key]; return { key, img: p.img, w: p.w, h: p.h, x0: LAYOUT.crop.x0, top: LAYOUT.top, removed: p.removed }; }
  const GLYPH = {
    red: '<path d="M24 5C29.5 11.5 30.5 22 24 30.5 17.5 22 18.5 11.5 24 5Z"/><path d="M24 30.5C13 29 7 20.5 7.5 11.5 16 14 22 21 24 30.5Z"/><path d="M24 30.5C35 29 41 20.5 40.5 11.5 32 14 26 21 24 30.5Z"/><path d="M6.5 34.5C15 41 33 41 41.5 34.5 33 37.5 15 37.5 6.5 34.5Z"/>',
    white: '<circle cx="24" cy="24" r="4"/>' + [0, 45, 90, 135, 180, 225, 270, 315].map(a => `<circle cx="${(24 + 15 * Math.cos(a * Math.PI / 180)).toFixed(2)}" cy="${(24 + 15 * Math.sin(a * Math.PI / 180)).toFixed(2)}" r="2.9"/>`).join(''),
    teal: [0, 45, 90, 135, 180, 225, 270, 315].map(a => `<ellipse cx="24" cy="12.5" rx="5.2" ry="10" transform="rotate(${a} 24 24)"/>`).join('') + '<circle cx="24" cy="24" r="5.5" fill="#fff" fill-opacity=".85"/><circle cx="24" cy="24" r="3"/>',
    yellow: '<path fill-rule="evenodd" d="M24 4L44 24 24 44 4 24Z M24 13L35 24 24 35 13 24Z"/><path d="M24 18l6 6-6 6-6-6z"/>',
    purple: [0, 90, 180, 270].map(a => `<ellipse cx="24" cy="12" rx="6.5" ry="11" transform="rotate(${a} 24 24)"/>`).join('') + '<circle cx="24" cy="24" r="4.2" fill="#fff" fill-opacity=".8"/><circle cx="24" cy="24" r="2.2"/>'
  };
  const glyph = (id, cls) => `<svg class="glyph ${cls || ''}" viewBox="0 0 48 48" fill="currentColor" aria-hidden="true">${GLYPH[id] || GLYPH.red}</svg>`; // PATCH B: an unknown id never yields an empty (blank) glyph
  const $ = id => document.getElementById(id), el = (tag, cls, html) => { const e = document.createElement(tag); if (cls) e.className = cls; if (html !== undefined) e.innerHTML = html; return e; };
  const nodes = { modal: $('modal'), stage: $('stage'), bg: $('bg'), layer: $('layer'), lines: $('lines'), chips: $('chips'), hud: $('hud'), hudCount: $('hud-count'), hudFill: $('hud-fill'), hudSun: $('hud-sun'), hudSecs: $('hud-secs'), pause: $('pause'), overlay: $('overlay'), rotate: $('rotate') };
  const ui = { run: null, mode: 'entry', body: null, k: 1, ox: 0, oy: 0, phaseShown: null, drag: null, refit: false, lastFrame: 0, raf: 0, overlay: null, teachQueue: [], seenTeach: {} };
  let L = null; // composed-space tables of the current body (built from ART by cx / cy when a phase is rendered)
  // ---------------- coordinates: painting px → composed px (the removed decorative slices are subtracted; a point inside one lands on the seam)
  const cx = px => px - ui.body.x0;
  const cy = py => { let y = py - ui.body.top; for (const [a, b] of ui.body.removed) { if (py >= b) y -= b - a; else if (py > a) { y -= py - a; break; } } return y; };
  function tables() { return { cols: ART.cols.map(cx), rows: ART.rows.map(cy), tagX: ART.tagX.map(cx), tagY: cy(ART.tagY), trayX: ART.trayX.map(cx), trayY: cy(ART.trayY), scaleX: ART.scaleX.map(cx), scaleY: cy(ART.scaleY), weightX: ART.weightX.map(cx), weightY: cy(ART.weightY), bundleTopY: cy(ART.bundleTopY), targetY: cy(ART.targetY) }; }
  // ---------------- modal fit: k = body height / composed height (the loom keeps its size; on narrower modals the market edges are cropped, never scaled down);
  // only when the viewport is too short does the width limit k instead (the modal itself already shrinks with the viewport, see weaving.css)
  function fit() {
    const b = ui.body || BODY.sort, sw = nodes.stage.clientWidth, sh = nodes.stage.clientHeight;
    ui.k = Math.max(sh / b.h, sw / b.w); ui.ox = (sw - b.w * ui.k) / 2; ui.oy = 0;
    for (const e of [nodes.bg, nodes.lines]) { e.style.left = ui.ox + 'px'; e.style.top = '0px'; e.style.width = (b.w * ui.k) + 'px'; e.style.height = (b.h * ui.k) + 'px'; }
    nodes.lines.setAttribute('viewBox', `0 0 ${b.w} ${b.h}`); nodes.stage.style.setProperty('--k', String(ui.k));
    nodes.modal.classList.toggle('narrow', nodes.modal.clientWidth < 348);
  }
  function setBody(key) { const b = BODY[key]; if (ui.body !== b) { ui.body = b; nodes.bg.src = b.img; } fit(); }
  const toArt = ev => { const r = nodes.stage.getBoundingClientRect(); return { x: (ev.clientX - r.left - ui.ox) / ui.k, y: (ev.clientY - r.top - ui.oy) / ui.k }; }; // pointer → composed px
  const place = (e, x, y, w, h) => { e.style.left = (ui.ox + x * ui.k) + 'px'; e.style.top = (ui.oy + y * ui.k) + 'px'; if (w) e.style.width = (w * ui.k) + 'px'; if (h) e.style.height = (h * ui.k) + 'px'; return e; }; // composed px → CSS px
  // ---------------- HUD (always in the modal's top band; frozen values on 今日收工, defaults on the entry screen)
  function hud() {
    const run = ui.run;
    if (!run) { nodes.hudCount.innerHTML = '已理丝线 <b>0</b>/5'; nodes.hudSecs.textContent = String(E.CONFIG.totalSeconds); nodes.hudFill.style.width = '100%'; nodes.hudSun.style.left = '100%'; return; }
    const ph = run.phase; let label = '已完成', n = 0, total = 5;
    if (ph === 'SORT') { label = '已理丝线'; n = run.sort.count; } else if (ph === 'WARP' || ph === 'WARP_DONE') { label = '已定经线'; n = run.warp.count; }
    else if (ph === 'URGENT') { label = '急线'; n = run.urgent.required.filter(id => run.urgent.board.lit[id]).length; total = 2; }
    else n = run.weave.board.roundCount;
    nodes.hudCount.innerHTML = `${label} <b>${n}</b>/${total}`;
    const secs = ph === 'URGENT' ? Math.ceil(run.urgent.msLeft / 1000) : Math.ceil(run.timeLeftMs / 1000), frac = ph === 'URGENT' ? run.urgent.msLeft / 8000 : run.timeLeftMs / (E.CONFIG.totalSeconds * 1000);
    nodes.hudSecs.textContent = run.mode === 'trial' ? '—' : String(Math.max(0, secs)); nodes.hudFill.style.width = (run.mode === 'trial' ? 100 : Math.max(0, frac) * 100) + '%'; nodes.hudSun.style.left = (run.mode === 'trial' ? 100 : Math.max(0, frac) * 100) + '%';
  }
  // ---------------- phases
  function showPhase(force) {
    const run = ui.run, key = run.phase + (run.phase === 'WEAVE' ? ':' + run.weave.round : '');
    if (!force && ui.phaseShown === key) { refresh(); return; }
    ui.phaseShown = key; nodes.layer.replaceChildren(); nodes.lines.replaceChildren(); nodes.chips.replaceChildren();
    if (run.phase === 'SORT') renderSort(); else if (run.phase === 'WARP') renderWarp(); else if (run.phase === 'WARP_DONE') renderWarpDone(); else if (run.phase === 'WEAVE' || run.phase === 'URGENT' || run.phase === 'ROUND_TRANSITION') renderWeave(); else if (run.phase === 'SETTLED') renderSettle();
    refresh();
  }
  function refresh() { const run = ui.run; hud(); if (!run) return; if (run.phase === 'SORT') refreshSort(); else if (run.phase === 'WARP') refreshWarp(); else if (['WEAVE', 'URGENT', 'ROUND_TRANSITION'].includes(run.phase)) refreshWeave(); }
  // ---- 理丝 (UI-01 / UI-02)
  function renderSort() {
    setBody('sort'); L = tables(); const run = ui.run;
    for (let i = 0; i < 5; i++) { const id = IDS[i], t = place(el('div', 'piece paper tag', glyph(id) + `<div class="bar" style="background:${ID[id].hex}"></div>`), L.tagX[i] - 38, L.tagY, 76, 88); t.dataset.slot = id; t.dataset.x = L.tagX[i] - 38; t.dataset.y = L.tagY; t.style.color = id === 'white' ? '#c9b58f' : ID[id].hex; nodes.layer.append(t); }
    for (let i = 0; i < 5; i++) { const sl = place(el('div', 'piece slot'), L.trayX[i] - 60, L.trayY, 120, 178); sl.style.backgroundImage = 'url(art/slot_empty.png)'; nodes.layer.append(sl); }
    run.sort.tray.forEach((id, i) => { const b = place(el('div', 'piece bundle'), L.trayX[i] - 60, L.trayY, 120, 178); b.style.backgroundImage = `url(art/bundle_tray_${id}.png)`; b.dataset.id = id; b.dataset.home = i; nodes.layer.append(b);
      if (run.sort.placed[id]) { b.classList.add('placed'); b.style.transform = placedTransform(id, i); } else b.addEventListener('pointerdown', ev => startBundleDrag(ev, b)); });
  }
  const placedTransform = (id, home) => { const i = IDS.indexOf(id); return `translate(${((L.tagX[i] - 60) - (L.trayX[home] - 60)) * ui.k}px,${(L.tagY + 60 - L.trayY) * ui.k}px) scale(.62)`; }; // the bundle shrinks onto its tag (piece animation, not page fitting)
  function refreshSort() { const run = ui.run; for (const t of nodes.layer.querySelectorAll('.tag')) t.classList.toggle('locked', Boolean(run.sort.placed[t.dataset.slot])); }
  function startBundleDrag(ev, b) {
    const run = ui.run; if (run.phase !== 'SORT' || run.paused || b.classList.contains('placed') || ui.drag) return; ev.preventDefault();
    const p = toArt(ev), home = { x: L.trayX[+b.dataset.home] - 60, y: L.trayY }; ui.drag = { kind: 'bundle', el: b, id: b.dataset.id, off: { x: p.x - home.x, y: p.y - home.y }, home };
    b.classList.add('drag'); b.setPointerCapture && b.setPointerCapture(ev.pointerId);
  }
  function hoverTag(p) { for (const t of nodes.layer.querySelectorAll('.tag')) { const x = +t.dataset.x, y = +t.dataset.y, hit = p.x >= x - 18 && p.x <= x + 94 && p.y >= y - 60 && p.y <= y + 110; t.classList.toggle('hover', hit && !t.classList.contains('locked')); if (hit) return t; } return null; }
  function moveBundle(ev) { const d = ui.drag, p = toArt(ev); d.el.style.transform = `translate(${(p.x - d.off.x - d.home.x) * ui.k}px,${(p.y - d.off.y - d.home.y) * ui.k}px)`; hoverTag({ x: p.x - d.off.x + 60, y: p.y - d.off.y + 70 }); }
  function endBundle(ev) {
    const d = ui.drag, p = toArt(ev), tag = hoverTag({ x: p.x - d.off.x + 60, y: p.y - d.off.y + 70 }); ui.drag = null; d.el.classList.remove('drag');
    for (const t of nodes.layer.querySelectorAll('.tag')) t.classList.remove('hover');
    const r = tag ? E.sortDrop(ui.run, d.id, tag.dataset.slot) : { ok: false };
    if (r.ok) { d.el.classList.add('placed'); d.el.style.transform = placedTransform(d.id, +d.el.dataset.home); tag.classList.add('hit'); setTimeout(() => tag.classList.remove('hit'), 500); if (r.done) setTimeout(() => showPhase(), 420); }
    else { d.el.style.transform = 'translate(0,0)'; if (tag) { tag.classList.add('shake'); setTimeout(() => tag.classList.remove('shake'), 400); } }
    refresh();
  }
  // ---- 定经 (UI-03 / UI-04)
  function renderWarp() {
    setBody('warp'); L = tables(); const run = ui.run;
    for (let i = 0; i < 5; i++) {
      const id = IDS[i]; const s = place(el('div', 'piece paper scale', `<div class="lbl">过紧</div><div class="track" style="--silk:${ID[id].hex}"><div class="band">合宜</div><div class="ind"></div></div><div class="lbl">过松</div>`), L.scaleX[i] - 31, L.scaleY, 62, 286); s.dataset.group = i; nodes.layer.append(s);
      const wp = place(el('div', 'piece woodpatch'), L.weightX[i] - 42, L.weightY - 8, 84, 198); wp.style.backgroundImage = 'url(art/wood_patch.png)'; nodes.layer.append(wp);
      const w = place(el('div', 'piece weight'), L.weightX[i] - 42, L.weightY, 84, 182); w.style.backgroundImage = 'url(art/weight.png)'; w.dataset.group = i; nodes.layer.append(w);
      for (const target of [s, w]) target.addEventListener('pointerdown', ev => { if (run.phase !== 'WARP' || run.paused || ui.drag) return; ev.preventDefault(); ui.drag = { kind: 'warp', group: i, y0: toArt(ev).y, v0: run.warp.values[i] }; target.setPointerCapture && target.setPointerCapture(ev.pointerId); });
    }
  }
  function refreshWarp() {
    const run = ui.run; nodes.layer.querySelectorAll('.scale').forEach(s => { const i = +s.dataset.group, v = run.warp.values[i], track = s.querySelector('.track'), h = track.clientHeight || 190 * ui.k; const band = s.querySelector('.band'), lo = E.CONFIG.warpBand[0], hi = E.CONFIG.warpBand[1];
      band.style.top = ((1 - hi) * h) + 'px'; band.style.height = ((hi - lo) * h) + 'px'; s.querySelector('.ind').style.top = ((1 - v) * h - 9 * ui.k) + 'px'; s.classList.toggle('ok', run.warp.done[i]); });
    nodes.layer.querySelectorAll('.weight').forEach(w => { const v = run.warp.values[+w.dataset.group]; w.style.transform = `translateY(${((0.5 - v) * 60 * ui.k).toFixed(1)}px)`; });
  }
  function moveWarp(ev) { const d = ui.drag, p = toArt(ev); E.warpSet(ui.run, d.group, d.v0 + (d.y0 - p.y) / 230); if (ui.run.phase === 'WARP_DONE') { ui.drag = null; showPhase(); } else refresh(); }
  function renderWarpDone() {
    setBody('warp_done'); L = tables();
    const [bx, by, bw, bh] = ART.warpDoneBtn, btn = place(el('div', 'piece hit-btn'), cx(bx), cy(by), bw, bh); btn.setAttribute('role', 'button'); btn.setAttribute('aria-label', '进入开工'); btn.addEventListener('pointerdown', ev => { ev.preventDefault(); if (E.warpSkip(ui.run).ok) showPhase(); }); nodes.layer.append(btn);
  }
  // ---- 开工 / 急束 (UI-05 / UI-06 / UI-07)
  function boardOf() { const run = ui.run; return run.phase === 'URGENT' ? run.urgent.board : run.weave.board; }
  function renderWeave() {
    setBody('weave'); L = tables(); const run = ui.run;
    for (let i = 0; i < 5; i++) { const id = IDS[i], b = place(el('div', 'piece bundle-top'), L.cols[i] - 58, L.bundleTopY, 116, 164); b.style.backgroundImage = `url(art/bundle_top_${id}.png)`; b.dataset.id = id; nodes.layer.append(b); b.addEventListener('pointerdown', ev => startLine(ev, id)); }
    for (let r = 0; r < 5; r++) for (let c = 0; c < 5; c++) { const n = E.node(r, c), ring = place(el('div', 'piece ring', '<div class="bead"></div>'), L.cols[c] - 31, L.rows[r] - 31, 62, 62); ring.style.backgroundImage = 'url(art/ring.png)'; ring.dataset.node = n; nodes.layer.append(ring); ring.addEventListener('pointerdown', ev => ringDown(ev, n)); }
    for (let j = 0; j < 5; j++) { const t = place(el('div', 'piece paper target'), L.cols[j] - 42, L.targetY, 84, 104); t.dataset.slot = j; nodes.layer.append(t); }
    refreshWeave();
  }
  function refreshWeave() {
    const run = ui.run, b = boardOf(), urgent = run.phase === 'URGENT';
    // PATCH B: the finished-pattern plaques are driven only by the persistent board state (targets / lit); a plaque is never re-rendered from an invalid id — the last valid glyph is kept — and a lit 素白 plaque is outlined so it never blends into the parchment (see weaving.css).
    nodes.layer.querySelectorAll('.target').forEach(t => { const j = +t.dataset.slot, raw = b.targets[j], id = ID[raw] ? raw : (ID[t.dataset.id] ? t.dataset.id : null); if (!id) return; if (t.dataset.id !== id || !t.querySelector('.glyph')) { t.dataset.id = id; t.innerHTML = glyph(id); t.style.setProperty('--silk', ID[id].hex); } t.classList.toggle('lit', Boolean(b.lit[id])); t.classList.toggle('urgent-req', urgent && run.urgent.required.includes(id)); });
    nodes.layer.querySelectorAll('.bundle-top').forEach(x => { x.classList.toggle('done', Boolean(b.lit[x.dataset.id])); x.classList.toggle('urgent-req', urgent && run.urgent.required.includes(x.dataset.id)); });
    const litNodes = {}; for (const [id, p] of Object.entries(b.paths)) for (const n of p) litNodes[n] = id; if (b.current) for (const n of b.current.nodes) litNodes[n] = b.current.identity;
    const loose = !urgent && run.weave.loose, knot = !urgent && run.weave.knot;
    nodes.layer.querySelectorAll('.ring').forEach(r => { const n = +r.dataset.node, id = litNodes[n]; r.classList.toggle('lit', Boolean(id)); if (id) r.style.setProperty('--silk', ID[id].hex); r.classList.toggle('loose-from', Boolean(loose && (n === loose.from || n === loose.to))); r.classList.toggle('knot', Boolean(knot && knot.node === n)); });
    drawLines(); drawChips();
  }
  const pt = n => ({ x: L.cols[E.colOf(n)], y: L.rows[E.rowOf(n)] });
  function pathD(id, pts) { const k = IDS.indexOf(id) - 2, o = k * 3; return pts.map((p, i) => (i ? 'L' : 'M') + (p.x + o).toFixed(1) + ' ' + (p.y + o).toFixed(1)).join(' '); }
  function drawLines() {
    const run = ui.run, b = boardOf(), svg = nodes.lines; svg.replaceChildren(); const loose = run.phase === 'WEAVE' ? run.weave.loose : null;
    const draw = (id, pts, cls) => { const d = pathD(id, pts); for (const [c, extra] of [['line-shadow', ''], ['line-core', `stroke:${ID[id].hex}`], ['line-twist', '']]) { const p = document.createElementNS('http://www.w3.org/2000/svg', 'path'); p.setAttribute('d', d); p.setAttribute('class', c + (cls ? ' ' + cls : '')); if (extra) p.setAttribute('style', extra); svg.append(p); } };
    for (const [id, path] of Object.entries(b.paths)) {
      const i = IDS.indexOf(id), j = b.targets.indexOf(id), pts = [{ x: L.cols[i], y: L.bundleTopY + 150 }, ...path.map(pt), { x: L.cols[j], y: L.targetY + 4 }];
      if (loose && loose.identity === id) { const s = loose.segment + 1; draw(id, pts.slice(0, s + 1)); draw(id, pts.slice(s, s + 2), 'line-loose'); draw(id, pts.slice(s + 1)); } else draw(id, pts);
    }
    if (b.current) { const i = IDS.indexOf(b.current.identity), pts = [{ x: L.cols[i], y: L.bundleTopY + 150 }, ...b.current.nodes.map(pt)]; if (ui.drag && ui.drag.kind === 'line' && ui.drag.at) pts.push(ui.drag.at); draw(b.current.identity, pts); }
    if (ui.drag && ui.drag.kind === 'repair' && ui.drag.at && loose) draw(loose.identity, [pt(ui.drag.from), ui.drag.at], 'line-loose');
  }
  function drawChips() {
    const run = ui.run; nodes.chips.replaceChildren();
    if (run.phase === 'URGENT') { nodes.chips.append(place(el('div', 'piece urgent-bar', `<span>⌛</span><span>急束！<b>${Math.max(0, Math.ceil(run.urgent.msLeft / 1000))}</b>秒内完结</span>`), cx(165), cy(266), 534, 50)); return; }
    if (run.phase !== 'WEAVE') return;
    if (run.weave.loose) nodes.chips.append(place(el('div', 'chip red', `丝头松脱 · 拖回接上<b>${Math.max(0, Math.ceil(run.weave.loose.msLeft / 1000))}</b>`), cx(432), cy(495)));
    else if (run.weave.knot) { nodes.chips.append(place(el('div', 'chip', '丝结缠住 · 点开线结'), cx(432), cy(495))); const k = pt(run.weave.knot.node), m = place(el('div', 'knot-mark', '结'), k.x, k.y); m.addEventListener('pointerdown', ev => { ev.preventDefault(); ev.stopPropagation(); if (E.knotUntie(ui.run, ui.run.weave.knot.node).ok) refresh(); }); nodes.chips.append(m); }
  }
  const hitRadius = () => Math.max(36, 19 / ui.k); // ring hit circle ≥ 38 CSS px in diameter whatever the modal width
  function nearestNode(p) { let best = null, bd = 1e9; for (let r = 0; r < 5; r++) for (let c = 0; c < 5; c++) { const dx = p.x - L.cols[c], dy = p.y - L.rows[r], d = dx * dx + dy * dy; if (d < bd) { bd = d; best = E.node(r, c); } } const rad = hitRadius(); return bd <= rad * rad ? best : null; }
  function slotAt(p) { if (p.y < L.targetY - 10 || p.y > L.targetY + 150) return null; for (let j = 0; j < 5; j++) if (Math.abs(p.x - L.cols[j]) <= 48) return j; return null; }
  function startLine(ev, id) {
    const run = ui.run; if (!(run.phase === 'WEAVE' || run.phase === 'URGENT') || run.paused || ui.drag) return; ev.preventDefault();
    const r = E.weaveStart(run, id); if (!r.ok) { if (r.reason === 'KNOT' || r.reason === 'LOOSE') flashChips(); return; }
    ui.drag = { kind: 'line', id, at: toArt(ev) }; nodes.stage.setPointerCapture && nodes.stage.setPointerCapture(ev.pointerId); refreshWeave();
  }
  function ringDown(ev, n) { // repairing a loose thread starts from one of its two rings
    const run = ui.run; if (run.phase !== 'WEAVE' || !run.weave.loose || ui.drag) return; const l = run.weave.loose; if (n !== l.from && n !== l.to) return; ev.preventDefault(); ui.drag = { kind: 'repair', from: n, at: toArt(ev) };
  }
  function moveLine(ev) { const d = ui.drag, p = toArt(ev); d.at = p; const n = nearestNode(p); if (n !== null) E.weaveExtend(ui.run, n); refreshWeave(); }
  function endLine(ev) {
    const d = ui.drag, p = toArt(ev); ui.drag = null; const slot = slotAt(p); const r = E.weaveRelease(ui.run, slot);
    if (!r.ok && slot !== null) { const t = nodes.layer.querySelector(`.target[data-slot="${slot}"]`); if (t) { t.classList.add('shake'); setTimeout(() => t.classList.remove('shake'), 400); } }
    afterAction(r);
  }
  function moveRepair(ev) { ui.drag.at = toArt(ev); drawLines(); }
  function endRepair(ev) { const d = ui.drag, p = toArt(ev); ui.drag = null; const n = nearestNode(p); if (n !== null && n !== d.from) E.looseRepair(ui.run, d.from, n); refreshWeave(); }
  function flashChips() { nodes.chips.classList.add('flash'); setTimeout(() => nodes.chips.classList.remove('flash'), 300); }
  function afterAction(r) {
    const run = ui.run; if (run.phase === 'SETTLED') { showSettled(); return; }
    if (r && r.events) for (const e of r.events) { if (e.type === 'LOOSE_START' && e.teach) teach('loose'); if (e.type === 'KNOT' && e.teach) teach('knot'); if (e.type === 'URGENT_START') showPhase(true); }
    if (run.phase === 'URGENT' || run.phase === 'ROUND_TRANSITION') showPhase(true); else refresh();
  }
  // ---- 今日收工 on the UI-09 empty template (UI-08 = target look): status in the painted frame, the four income lines beside the painted icons
  // and coins, transparent text only (no card, no stats line, no 获得手艺); every number is the settlement state (run.wages), never recomputed.
  function showSettled() { ui.mode = 'settled'; ui.drag = null; showPhase(true); } // a drag in flight when the sun runs out is dropped with the board
  function renderSettle() {
    setBody('settle'); L = null; const run = ui.run, w = run.wages;
    if (run.status === 'trial') { openOverlay('trialEnd'); return; }
    const P = (e, x, y, wd, h) => place(e, x, y - BODY.settle.top, wd, h); // UI-09 template coordinates (954×1649)
    const [sx, sy, sw, sh] = T9.statusBox; nodes.layer.append(P(el('div', 'piece settle-status', '顺利收工'), sx, sy, sw, sh)); // PATCH A A1: the work result is the status; the end reason is not a headline
    const rows = [[T9.rows[0], '基础工钱', w.base], [T9.rows[1], '常规加赏', w.regular], [T9.rows[2], '急束加成', w.urgent]];
    for (const [y, label, v] of rows) { nodes.layer.append(P(el('div', 'piece settle-label', label), T9.labelX, y - 32, T9.labelW, 64)); nodes.layer.append(P(el('div', 'piece settle-value', String(v)), T9.valueX, y - 34, T9.valueW, 68)); }
    nodes.layer.append(P(el('div', 'piece settle-label total', '合计收入'), T9.labelX, T9.totalY - 36, T9.labelW, 72)); nodes.layer.append(P(el('div', 'piece settle-value total', String(w.total)), T9.valueX - 25, T9.totalY - 54, T9.valueW + 25, 108));
    const stay = P(el('div', 'piece hit-btn'), ...T9.stay), leave = P(el('div', 'piece hit-btn'), ...T9.leave);
    stay.setAttribute('role', 'button'); stay.setAttribute('aria-label', '继续留坊'); leave.setAttribute('role', 'button'); leave.setAttribute('aria-label', '离开织坊');
    stay.addEventListener('pointerdown', ev => { ev.preventDefault(); startRun('formal'); }); leave.addEventListener('pointerdown', ev => { ev.preventDefault(); toEntry(); }); nodes.layer.append(stay, leave);
  }
  // ---------------- overlays: entry / pause / help / confirm / teaching cards (all inside the modal)
  function openOverlay(kind, data) {
    ui.overlay = kind; const run = ui.run; if (run && ['SORT', 'WARP', 'WARP_DONE', 'WEAVE', 'ROUND_TRANSITION', 'URGENT'].includes(run.phase)) E.pause(run);
    const card = el('div', 'card' + (kind === 'help' ? ' wide' : '')); nodes.overlay.replaceChildren(card); nodes.overlay.hidden = false;
    const btn = (label, fn, cls) => { const b = el('button', 'btn ' + (cls || ''), label); b.type = 'button'; b.addEventListener('click', fn); return b; };
    if (kind === 'entry') { card.innerHTML = '<h2>于阗织坊</h2><p class="sub">帮工试玩 · FINAL v5.0 · 未接入主游戏</p><p class="sub">理丝 → 定经 → 开工（三轮 × 五根） → 今日收工</p>'; const m = el('div', 'menu'); m.append(btn('正式帮工', () => startRun('formal'), 'primary'), btn('先试一试', () => startRun('trial')), btn('玩法说明', () => openOverlay('help', { back: 'entry' }), 'quiet')); card.append(m); }
    if (kind === 'pause') { card.innerHTML = '<h2>暂停</h2><p class="sub">日影已停</p>'; const m = el('div', 'menu'); m.append(btn('继续游戏', closeOverlay, 'primary'), btn('重新开始', () => { closeOverlay(); startRun(ui.run.mode); }), btn('玩法说明', () => openOverlay('help', { back: 'pause' }), 'quiet'), btn('退出游戏', () => openOverlay('quit'), 'quiet')); card.append(m); }
    if (kind === 'quit') { card.innerHTML = '<h2>尚未收工</h2><p style="text-align:center">此时离开，今日工钱不作结，也不耗去时辰。</p>'; const m = el('div', 'menu'); m.append(btn('继续理丝', () => openOverlay('pause'), 'primary'), btn('离开织坊', () => { E.abandon(ui.run); toEntry(); }, 'quiet')); card.append(m); }
    if (kind === 'help') { card.innerHTML = helpHtml(); const m = el('div', 'menu'); m.append(btn('返回', () => data && data.back === 'pause' ? openOverlay('pause') : data && data.back === 'entry' ? openOverlay('entry') : closeOverlay(), 'primary')); card.append(m); }
    if (kind === 'teach') { card.innerHTML = data.html; const m = el('div', 'menu'); m.append(btn('知道了', () => { closeOverlay(); nextTeach(); }, 'primary')); card.append(m); }
    if (kind === 'trialEnd') { card.innerHTML = '<h2>试工结束</h2><p style="text-align:center">三道工序都试过了。正式帮工时，日影七十五息共享理丝、定经与开工，工钱按当日织成的根数结算。</p>'; const m = el('div', 'menu'); m.append(btn('正式帮工', () => startRun('formal'), 'primary'), btn('返回', toEntry, 'quiet')); card.append(m); }
    card.scrollTop = 0;
  }
  function closeOverlay() { ui.overlay = null; nodes.overlay.hidden = true; nodes.overlay.replaceChildren(); const run = ui.run; if (run) { E.resume(run); ui.lastFrame = performance.now(); } }
  function teach(kind) { ui.teachQueue.push(kind); if (ui.overlay !== 'teach') nextTeach(); }
  function nextTeach() { const kind = ui.teachQueue.shift(); if (!kind) return; openOverlay('teach', { html: kind === 'loose' ? TEACH.loose : TEACH.knot }); }
  const TEACH = {
    loose: '<h2>丝头松脱</h2><div class="teach"><p>织到一半，线路上有一处丝头从圆环脱开了。脱开的那一段会变成虚线，两端的圆环发亮。</p><p>在五息之内，从发亮的圆环按住，拖到相邻那一环，把丝头重新接回。</p><p>接回了，这根线照旧算数；没接回，这根线会散掉，要重新织。</p></div><p class="sub">正式帮工时只有一条小提示与倒数，不会再弹出这张说明。</p>',
    knot: '<h2>丝结缠住</h2><div class="teach"><p>两根丝线在同一个圆环交叉时，可能缠成一个线结。线结会标在交叉的圆环上。</p><p>点一下线结，把它解开，再继续连线。线结没解开之前，新的丝线不能起头。</p></div><p class="sub">正式帮工时只有一条小提示，不会再弹出这张说明。</p>'
  };
  function helpHtml() { return '<h2>玩法说明</h2><h3>理丝</h3><p>按丝色与纹样，把下方的散丝拖到上方对应挂位。颜色与纹样都对才会挂住；不对的丝束回到原处。</p><h3>定经</h3><p>上下拖动配重，让五组经线都落入绿色「合宜」。五组齐了，中央出现「经线已齐，可开工织造」，一息半后自动开工，也可以直接点「进入开工」。</p><h3>开工</h3><p>从上方丝线起头，沿相邻的圆环走，最后接到下方对应的纹样。直接拖到纹样、没有经过圆环，不算。每轮五根，连织三轮，共十五根；每轮下方纹样重新打乱，全部灰色，接上的才亮起。</p><h3>日影</h3><p>正式帮工共七十五息，理丝、定经、开工共用。暂停、急束、定经转场时停表。日影尽时按已织成的根数照常结算。</p><h3>急束</h3><p>开工到七根以后可能来一单急束：独立八息，完成两根指定急线得一钱加赏；没完成不扣钱。急束期间日影停表。</p>' + TEACH.loose.replace('<h2>', '<h3>').replace('</h2>', '</h3>').replace(/<p class="sub">.*<\/p>/, '') + TEACH.knot.replace('<h2>', '<h3>').replace('</h2>', '</h3>').replace(/<p class="sub">.*<\/p>/, '') + '<h3>工钱</h3><p>织成 0–4 根 9 钱；5–9 根 11 钱；10–14 根 15 钱；15 根 19 钱。每织完一轮加赏 1 钱（最多 3 钱）；急束成功另加 1 钱；最高 23 钱。</p><h3>中途离开</h3><p>只有主动离开织坊不作结、不耗时辰；时间到、只完成一部分，都照常结算。</p>'; }
  // ---------------- run control
  function startRun(mode, options) { closeOverlay(); ui.run = E.createRun(Object.assign({ mode }, options || {})); ui.mode = 'run'; ui.phaseShown = null; ui.drag = null; ui.teachQueue = []; showPhase(true); ui.lastFrame = performance.now(); }
  function toEntry() { closeOverlay(); ui.run = null; ui.mode = 'entry'; ui.phaseShown = null; nodes.layer.replaceChildren(); nodes.lines.replaceChildren(); nodes.chips.replaceChildren(); setBody('sort'); hud(); openOverlay('entry'); }
  function frame(now) {
    ui.raf = requestAnimationFrame(frame); const run = ui.run; if (!run || ui.mode !== 'run') return;
    const dt = Math.min(250, now - (ui.lastFrame || now)); ui.lastFrame = now; if (!dt) return;
    const events = E.tick(run, dt); if (run.phase === 'SETTLED') { showSettled(); return; }
    for (const e of events) { if (['WEAVE_START', 'ROUND_START', 'URGENT_END'].includes(e.type)) { ui.drag = null; showPhase(true); } if (e.type === 'LOOSE_FAILED') { ui.drag = null; refresh(); } }
    if (run.phase === 'URGENT' || run.weave.loose) drawChips(); hud();
  }
  // ---------------- input plumbing
  nodes.stage.addEventListener('pointermove', ev => { if (!ui.drag) return; ev.preventDefault(); if (!L) { ui.drag = null; return; } if (ui.drag.kind === 'bundle') moveBundle(ev); else if (ui.drag.kind === 'warp') moveWarp(ev); else if (ui.drag.kind === 'line') moveLine(ev); else if (ui.drag.kind === 'repair') moveRepair(ev); });
  const up = ev => { if (!ui.drag) return; if (!L) { ui.drag = null; return; } if (ui.drag.kind === 'bundle') endBundle(ev); else if (ui.drag.kind === 'warp') { ui.drag = null; refresh(); } else if (ui.drag.kind === 'line') endLine(ev); else if (ui.drag.kind === 'repair') endRepair(ev); if (ui.refit) { ui.refit = false; refit(); } };
  nodes.stage.addEventListener('pointerup', up); nodes.stage.addEventListener('pointercancel', up); window.addEventListener('pointerup', up);
  nodes.pause.addEventListener('click', () => { if (ui.run && ui.mode === 'run') openOverlay('pause'); });
  function refit() { fit(); if (ui.run && ui.mode !== 'entry') showPhase(true); else fit(); }
  function orient() { nodes.rotate.hidden = !(window.innerWidth > window.innerHeight && window.innerHeight < 520); }
  window.addEventListener('resize', () => { orient(); if (ui.drag) { fit(); ui.refit = true; } else refit(); });
  window.addEventListener('keydown', ev => { if (ev.key === 'Escape' && ui.run && ui.mode === 'run' && !ui.overlay) openOverlay('pause'); });
  // test / host access: geometry of the current body and painting-px → client-px mapping
  const geom = () => { const r = nodes.stage.getBoundingClientRect(), m = nodes.modal.getBoundingClientRect(), b = ui.body; return { k: ui.k, ox: ui.ox, oy: ui.oy, left: r.left, top: r.top, width: r.width, height: r.height, body: b.key, x0: b.x0, artTop: b.top, removed: b.removed, modal: { x: m.x, y: m.y, width: m.width, height: m.height } }; };
  const screenOf = (px, py) => { const r = nodes.stage.getBoundingClientRect(); return { x: r.left + ui.ox + cx(px) * ui.k, y: r.top + ui.oy + cy(py) * ui.k }; };
  orient(); setBody('sort'); hud(); openOverlay('entry'); ui.raf = requestAnimationFrame(frame);
  window.YutianWeavingUI = { ui, startRun, toEntry, E, openOverlay, closeOverlay, showPhase, refresh, LAYOUT, ART, T9, geom, screenOf, screenOfMany: pts => pts.map(p => screenOf(p[0], p[1])) };
})();
